// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tblnursegrade

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

var (
	Name       = dialect.Field{Name: "name", Json: "name", Table: "nurse_grade", Type: "types.String", IsRelation: false}
	Type       = dialect.Field{Name: "type", Json: "type", Table: "nurse_grade", Type: "types.String", IsRelation: false}
	DelFlag    = dialect.Field{Name: "del_flag", Json: "del_flag", Table: "nurse_grade", Type: "types.String", IsRelation: false}
	Id         = dialect.Field{Name: "id", Json: "id", Table: "nurse_grade", Type: "types.BigInt", IsRelation: false}
	MonthPrice = dialect.Field{Name: "month_price", Json: "month_price", Table: "nurse_grade", Type: "types.Float64", IsRelation: false}
	CreateId   = dialect.Field{Name: "create_id", Json: "create_id", Table: "nurse_grade", Type: "types.BigInt", IsRelation: false}
	CreateTime = dialect.Field{Name: "create_time", Json: "create_time", Table: "nurse_grade", Type: "types.Time", IsRelation: false}
	UpdateId   = dialect.Field{Name: "update_id", Json: "update_id", Table: "nurse_grade", Type: "types.BigInt", IsRelation: false}
	UpdateTime = dialect.Field{Name: "update_time", Json: "update_time", Table: "nurse_grade", Type: "types.Time", IsRelation: false}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		Name,
		Type,
		DelFlag,
		Id,
		MonthPrice,
		CreateId,
		CreateTime,
		UpdateId,
		UpdateTime,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		Name,
		Type,
		DelFlag,
		Id,
		MonthPrice,
		CreateId,
		CreateTime,
		UpdateId,
		UpdateTime,
	}
)
