// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tblelder

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

const TableName = "elder"

var (
	Address        = dialect.Field{Name: "address", Json: "address", Table: "elder", Type: "types.String", IsRelation: false}
	IdNum          = dialect.Field{Name: "id_num", Json: "id_num", Table: "elder", Type: "types.String", IsRelation: false}
	Name           = dialect.Field{Name: "name", Json: "name", Table: "elder", Type: "types.String", IsRelation: false}
	Phone          = dialect.Field{Name: "phone", Json: "phone", Table: "elder", Type: "types.String", IsRelation: false}
	Sex            = dialect.Field{Name: "sex", Json: "sex", Table: "elder", Type: "types.String", IsRelation: false}
	Balance        = dialect.Field{Name: "balance", Json: "balance", Table: "elder", Type: "types.Money", IsRelation: false}
	BedId          = dialect.Field{Name: "bed_id", Json: "bed_id", Table: "elder", Type: "types.BigInt", IsRelation: false}
	CateringSetId  = dialect.Field{Name: "catering_set_id", Json: "catering_set_id", Table: "elder", Type: "types.BigInt", IsRelation: false}
	CreateId       = dialect.Field{Name: "create_id", Json: "create_id", Table: "elder", Type: "types.BigInt", IsRelation: false}
	CreateTime     = dialect.Field{Name: "create_time", Json: "create_time", Table: "elder", Type: "types.Time", IsRelation: false}
	Id             = dialect.Field{Name: "id", Json: "id", Table: "elder", Type: "types.BigInt", IsRelation: false}
	NursingGradeId = dialect.Field{Name: "nursing_grade_id", Json: "nursing_grade_id", Table: "elder", Type: "types.BigInt", IsRelation: false}
	TenantId       = dialect.Field{Name: "tenant_id", Json: "tenant_id", Table: "elder", Type: "types.BigInt", IsRelation: false}
	UpdateId       = dialect.Field{Name: "update_id", Json: "update_id", Table: "elder", Type: "types.BigInt", IsRelation: false}
	UpdateTime     = dialect.Field{Name: "update_time", Json: "update_time", Table: "elder", Type: "types.Time", IsRelation: false}
	Age            = dialect.Field{Name: "age", Json: "age", Table: "elder", Type: "types.Int32", IsRelation: false}
	Status         = dialect.Field{Name: "status", Json: "status", Table: "elder", Type: "types.Int8", IsRelation: false}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		Address,
		IdNum,
		Name,
		Phone,
		Sex,
		Balance,
		BedId,
		CateringSetId,
		CreateId,
		CreateTime,
		Id,
		NursingGradeId,
		TenantId,
		UpdateId,
		UpdateTime,
		Age,
		Status,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		Address,
		IdNum,
		Name,
		Phone,
		Sex,
		Balance,
		BedId,
		CateringSetId,
		CreateId,
		CreateTime,
		Id,
		NursingGradeId,
		TenantId,
		UpdateId,
		UpdateTime,
		Age,
		Status,
	}
)
