// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tbloutboundrecorditem

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

const TableName = "outbound_record_item"

var (
	CreateId   = dialect.Field{Name: "create_id", Json: "create_id", Table: "outbound_record_item", Type: "types.BigInt", IsRelation: false}
	CreateTime = dialect.Field{Name: "create_time", Json: "create_time", Table: "outbound_record_item", Type: "types.Time", IsRelation: false}
	Id         = dialect.Field{Name: "id", Json: "id", Table: "outbound_record_item", Type: "types.BigInt", IsRelation: false}
	MaterialId = dialect.Field{Name: "material_id", Json: "material_id", Table: "outbound_record_item", Type: "types.BigInt", IsRelation: false}
	RecordId   = dialect.Field{Name: "record_id", Json: "record_id", Table: "outbound_record_item", Type: "types.BigInt", IsRelation: false}
	StockId    = dialect.Field{Name: "stock_id", Json: "stock_id", Table: "outbound_record_item", Type: "*types.BigInt", IsRelation: false}
	TenantId   = dialect.Field{Name: "tenant_id", Json: "tenant_id", Table: "outbound_record_item", Type: "types.BigInt", IsRelation: false}
	UpdateId   = dialect.Field{Name: "update_id", Json: "update_id", Table: "outbound_record_item", Type: "types.BigInt", IsRelation: false}
	UpdateTime = dialect.Field{Name: "update_time", Json: "update_time", Table: "outbound_record_item", Type: "types.Time", IsRelation: false}
	Qty        = dialect.Field{Name: "qty", Json: "qty", Table: "outbound_record_item", Type: "types.Int32", IsRelation: false}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		CreateId,
		CreateTime,
		Id,
		MaterialId,
		RecordId,
		TenantId,
		UpdateId,
		UpdateTime,
		Qty,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		CreateId,
		CreateTime,
		Id,
		MaterialId,
		RecordId,
		TenantId,
		UpdateId,
		UpdateTime,
		Qty,
	}
)
