// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tblauth

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

const TableName = "auth"

var (
	Title      = dialect.Field{Name: "title", Json: "title", Table: "auth", Type: "types.String", IsRelation: false}
	Name       = dialect.Field{Name: "name", Json: "name", Table: "auth", Type: "types.String", IsRelation: false}
	Path       = dialect.Field{Name: "path", Json: "path", Table: "auth", Type: "types.String", IsRelation: false}
	Icon       = dialect.Field{Name: "icon", Json: "icon", Table: "auth", Type: "types.String", IsRelation: false}
	Url        = dialect.Field{Name: "url", Json: "url", Table: "auth", Type: "types.String", IsRelation: false}
	Type       = dialect.Field{Name: "type", Json: "type", Table: "auth", Type: "types.String", IsRelation: false}
	Method     = dialect.Field{Name: "method", Json: "method", Table: "auth", Type: "types.String", IsRelation: false}
	Id         = dialect.Field{Name: "id", Json: "id", Table: "auth", Type: "types.BigInt", IsRelation: false}
	ParentId   = dialect.Field{Name: "parent_id", Json: "parent_id", Table: "auth", Type: "types.BigInt", IsRelation: false}
	CreateId   = dialect.Field{Name: "create_id", Json: "create_id", Table: "auth", Type: "types.BigInt", IsRelation: false}
	CreateTime = dialect.Field{Name: "create_time", Json: "create_time", Table: "auth", Type: "types.Time", IsRelation: false}
	UpdateId   = dialect.Field{Name: "update_id", Json: "update_id", Table: "auth", Type: "types.BigInt", IsRelation: false}
	UpdateTime = dialect.Field{Name: "update_time", Json: "update_time", Table: "auth", Type: "types.Time", IsRelation: false}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		Title,
		Name,
		Path,
		Icon,
		Url,
		Type,
		Method,
		Id,
		ParentId,
		CreateId,
		CreateTime,
		UpdateId,
		UpdateTime,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		Title,
		Name,
		Path,
		Icon,
		Url,
		Type,
		Method,
		Id,
		ParentId,
		CreateId,
		CreateTime,
		UpdateId,
		UpdateTime,
	}
)
