// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tblbillitem

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

const TableName = "bill_item"

var (
	Description = dialect.Field{Name: "description", Json: "description", Table: "bill_item", Type: "types.String", IsRelation: false}
	Amount      = dialect.Field{Name: "amount", Json: "amount", Table: "bill_item", Type: "types.Money", IsRelation: false}
	BillId      = dialect.Field{Name: "bill_id", Json: "bill_id", Table: "bill_item", Type: "types.BigInt", IsRelation: false}
	CreatedTime = dialect.Field{Name: "created_time", Json: "created_time", Table: "bill_item", Type: "types.Time", IsRelation: false}
	FeeItemId   = dialect.Field{Name: "fee_item_id", Json: "fee_item_id", Table: "bill_item", Type: "types.BigInt", IsRelation: false}
	Id          = dialect.Field{Name: "id", Json: "id", Table: "bill_item", Type: "types.BigInt", IsRelation: false}
	Quantity    = dialect.Field{Name: "quantity", Json: "quantity", Table: "bill_item", Type: "types.Float64", IsRelation: false}
	UnitPrice   = dialect.Field{Name: "unit_price", Json: "unit_price", Table: "bill_item", Type: "types.Money", IsRelation: false}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		Description,
		Amount,
		BillId,
		FeeItemId,
		Id,
		Quantity,
		UnitPrice,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		Description,
		Amount,
		BillId,
		CreatedTime,
		FeeItemId,
		Id,
		Quantity,
		UnitPrice,
	}
)
