// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblstock"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

var (
	stockPool = pool.New[*Stock](func() any {
		_obj := &Stock{}
		return _obj
	})
)

func NewStock() *Stock {
	_obj := stockPool.Get()
	return _obj
}

// MarshalJSON
func (p *Stock) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(12 * 50)
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if !p.ExpireDate.IsZero() {
		write.WriteRaw("expire_date", types.Marshal(p.ExpireDate))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.MaterialId != 0 {
		write.WriteRaw("material_id", types.Marshal(p.MaterialId))
	}
	if !p.ProductDate.IsZero() {
		write.WriteRaw("product_date", types.Marshal(p.ProductDate))
	}
	if p.TenantId != 0 {
		write.WriteRaw("tenant_id", types.Marshal(p.TenantId))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	if p.WarehouseId != 0 {
		write.WriteRaw("warehouse_id", types.Marshal(p.WarehouseId))
	}
	if p.Qty != 0 {
		write.WriteRaw("qty", types.Marshal(p.Qty))
	}
	if p.BatchNo != "" {
		write.WriteRaw("batch_no", types.Marshal(p.BatchNo))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *Stock) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "expire_date":
			p.ExpireDate = types.Time{Time: value.Time()}
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "material_id":
			p.MaterialId = types.BigInt(value.Uint())
		case "product_date":
			p.ProductDate = types.Time{Time: value.Time()}
		case "tenant_id":
			p.TenantId = types.BigInt(value.Uint())
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		case "warehouse_id":
			p.WarehouseId = types.BigInt(value.Uint())
		case "qty":
			p.Qty = types.Int32(value.Int())
		case "batch_no":
			p.BatchNo = types.String(value.Str)
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *Stock) Free() {
	if p == nil {
		return
	}

	stockPool.Put(p)
}

// Reset
func (p *Stock) Reset() {
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.ExpireDate = types.Time{}
	p.Id = 0
	p.MaterialId = 0
	p.ProductDate = types.Time{}
	p.TenantId = 0
	p.UpdateId = 0
	p.UpdateTime = types.Time{}
	p.WarehouseId = 0
	p.Qty = 0
	p.BatchNo = ""

}

func (p *Stock) TableName() string {
	return "stock"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var stockFieldToPtrFunc = map[string]func(*Stock) any{
	tblstock.CreateId.Name:    func(p *Stock) any { return &p.CreateId },
	tblstock.CreateTime.Name:  func(p *Stock) any { return &p.CreateTime },
	tblstock.ExpireDate.Name:  func(p *Stock) any { return &p.ExpireDate },
	tblstock.Id.Name:          func(p *Stock) any { return &p.Id },
	tblstock.MaterialId.Name:  func(p *Stock) any { return &p.MaterialId },
	tblstock.ProductDate.Name: func(p *Stock) any { return &p.ProductDate },
	tblstock.TenantId.Name:    func(p *Stock) any { return &p.TenantId },
	tblstock.UpdateId.Name:    func(p *Stock) any { return &p.UpdateId },
	tblstock.UpdateTime.Name:  func(p *Stock) any { return &p.UpdateTime },
	tblstock.WarehouseId.Name: func(p *Stock) any { return &p.WarehouseId },
	tblstock.Qty.Name:         func(p *Stock) any { return &p.Qty },
	tblstock.BatchNo.Name:     func(p *Stock) any { return &p.BatchNo },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *Stock) fieldPtr(args ...dialect.Field) []func(*Stock) any {
	if len(args) == 0 {
		args = tblstock.ReadableFields
	}
	fs := make([]func(*Stock) any, 0, len(args))
	for _, col := range args {
		if f, ok := stockFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *Stock) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *Stock) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if f, ok := stockFieldToPtrFunc[col]; ok {
			_vals = append(_vals, f(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *Stock) Slice(rows *sql.Rows, args ...dialect.Field) ([]*Stock, bool, error) {
	defer rows.Close()
	stocks := make([]*Stock, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewStock()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		stocks = append(stocks, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return stocks, len(stocks) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Stock) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblstock.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var stockFieldToValueFunc = map[dialect.Field]func(*Stock) (any, bool){
	tblstock.CreateId: func(p *Stock) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblstock.CreateTime: func(p *Stock) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblstock.ExpireDate: func(p *Stock) (any, bool) {
		return p.ExpireDate, p.ExpireDate.IsZero()
	},
	tblstock.Id: func(p *Stock) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblstock.MaterialId: func(p *Stock) (any, bool) {
		return p.MaterialId, p.MaterialId == 0
	},
	tblstock.ProductDate: func(p *Stock) (any, bool) {
		return p.ProductDate, p.ProductDate.IsZero()
	},
	tblstock.TenantId: func(p *Stock) (any, bool) {
		return p.TenantId, p.TenantId == 0
	},
	tblstock.UpdateId: func(p *Stock) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblstock.UpdateTime: func(p *Stock) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
	tblstock.WarehouseId: func(p *Stock) (any, bool) {
		return p.WarehouseId, p.WarehouseId == 0
	},
	tblstock.Qty: func(p *Stock) (any, bool) {
		return p.Qty, p.Qty == 0
	},
	tblstock.BatchNo: func(p *Stock) (any, bool) {
		return p.BatchNo, p.BatchNo == ""
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Stock) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblstock.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if f, has := stockFieldToValueFunc[arg]; has {
			value, isZero := f(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *Stock) AssignKeys() (dialect.Field, any) {
	return tblstock.PrimaryKey, p.Id
}

func (p *Stock) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
