// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblwarehouserecord"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

var (
	warehouserecordPool = pool.New[*WarehouseRecord](func() any {
		_obj := &WarehouseRecord{}
		return _obj
	})
)

func NewWarehouseRecord() *WarehouseRecord {
	_obj := warehouserecordPool.Get()
	return _obj
}

// MarshalJSON
func (p *WarehouseRecord) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(11 * 50)
	if p.Source != "" {
		write.WriteRaw("source", types.Marshal(p.Source))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.WarehouseId != 0 {
		write.WriteRaw("warehouse_id", types.Marshal(p.WarehouseId))
	}
	if p.StaffId != 0 {
		write.WriteRaw("staff_id", types.Marshal(p.StaffId))
	}
	if !p.WarehouseDate.IsZero() {
		write.WriteRaw("warehouse_date", types.Marshal(p.WarehouseDate))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	if p.WarehouseFlag != 0 {
		write.WriteRaw("warehouse_flag", types.Marshal(p.WarehouseFlag))
	}
	if p.DelFlag != 0 {
		write.WriteRaw("del_flag", types.Marshal(p.DelFlag))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *WarehouseRecord) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "source":
			p.Source = types.String(value.Str)
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "warehouse_id":
			p.WarehouseId = types.BigInt(value.Uint())
		case "staff_id":
			p.StaffId = types.BigInt(value.Uint())
		case "warehouse_date":
			p.WarehouseDate = types.Time{Time: value.Time()}
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		case "warehouse_flag":
			p.WarehouseFlag = types.Int8(value.Int())
		case "del_flag":
			p.DelFlag = types.Int8(value.Int())
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *WarehouseRecord) Free() {
	if p == nil {
		return
	}

	warehouserecordPool.Put(p)
}

// Reset
func (p *WarehouseRecord) Reset() {
	p.Source = ""
	p.Id = 0
	p.WarehouseId = 0
	p.StaffId = 0
	p.WarehouseDate = types.Time{}
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}
	p.WarehouseFlag = 0
	p.DelFlag = 0

}

func (p *WarehouseRecord) TableName() string {
	return "warehouse_record"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var warehouserecordFieldToPtrFunc = map[string]func(*WarehouseRecord) any{
	tblwarehouserecord.Source.Name:        func(p *WarehouseRecord) any { return &p.Source },
	tblwarehouserecord.Id.Name:            func(p *WarehouseRecord) any { return &p.Id },
	tblwarehouserecord.WarehouseId.Name:   func(p *WarehouseRecord) any { return &p.WarehouseId },
	tblwarehouserecord.StaffId.Name:       func(p *WarehouseRecord) any { return &p.StaffId },
	tblwarehouserecord.WarehouseDate.Name: func(p *WarehouseRecord) any { return &p.WarehouseDate },
	tblwarehouserecord.CreateId.Name:      func(p *WarehouseRecord) any { return &p.CreateId },
	tblwarehouserecord.CreateTime.Name:    func(p *WarehouseRecord) any { return &p.CreateTime },
	tblwarehouserecord.UpdateId.Name:      func(p *WarehouseRecord) any { return &p.UpdateId },
	tblwarehouserecord.UpdateTime.Name:    func(p *WarehouseRecord) any { return &p.UpdateTime },
	tblwarehouserecord.WarehouseFlag.Name: func(p *WarehouseRecord) any { return &p.WarehouseFlag },
	tblwarehouserecord.DelFlag.Name:       func(p *WarehouseRecord) any { return &p.DelFlag },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *WarehouseRecord) fieldPtr(args ...dialect.Field) []func(*WarehouseRecord) any {
	if len(args) == 0 {
		args = tblwarehouserecord.ReadableFields
	}
	fs := make([]func(*WarehouseRecord) any, 0, len(args))
	for _, col := range args {
		if f, ok := warehouserecordFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *WarehouseRecord) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *WarehouseRecord) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if f, ok := warehouserecordFieldToPtrFunc[col]; ok {
			_vals = append(_vals, f(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *WarehouseRecord) Slice(rows *sql.Rows, args ...dialect.Field) ([]*WarehouseRecord, bool, error) {
	defer rows.Close()
	warehouse_records := make([]*WarehouseRecord, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewWarehouseRecord()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		warehouse_records = append(warehouse_records, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return warehouse_records, len(warehouse_records) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *WarehouseRecord) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblwarehouserecord.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var warehouserecordFieldToValueFunc = map[dialect.Field]func(*WarehouseRecord) (any, bool){
	tblwarehouserecord.Source: func(p *WarehouseRecord) (any, bool) {
		return p.Source, p.Source == ""
	},
	tblwarehouserecord.Id: func(p *WarehouseRecord) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblwarehouserecord.WarehouseId: func(p *WarehouseRecord) (any, bool) {
		return p.WarehouseId, p.WarehouseId == 0
	},
	tblwarehouserecord.StaffId: func(p *WarehouseRecord) (any, bool) {
		return p.StaffId, p.StaffId == 0
	},
	tblwarehouserecord.WarehouseDate: func(p *WarehouseRecord) (any, bool) {
		return p.WarehouseDate, p.WarehouseDate.IsZero()
	},
	tblwarehouserecord.CreateId: func(p *WarehouseRecord) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblwarehouserecord.CreateTime: func(p *WarehouseRecord) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblwarehouserecord.UpdateId: func(p *WarehouseRecord) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblwarehouserecord.UpdateTime: func(p *WarehouseRecord) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
	tblwarehouserecord.WarehouseFlag: func(p *WarehouseRecord) (any, bool) {
		return p.WarehouseFlag, p.WarehouseFlag == 0
	},
	tblwarehouserecord.DelFlag: func(p *WarehouseRecord) (any, bool) {
		return p.DelFlag, p.DelFlag == 0
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *WarehouseRecord) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblwarehouserecord.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if f, has := warehouserecordFieldToValueFunc[arg]; has {
			value, isZero := f(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *WarehouseRecord) AssignKeys() (dialect.Field, any) {
	return tblwarehouserecord.PrimaryKey, p.Id
}

func (p *WarehouseRecord) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
