// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblfamilyrecharge"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

var (
	familyrechargePool = pool.New[*FamilyRecharge](func() any {
		_obj := &FamilyRecharge{}
		return _obj
	})
)

func NewFamilyRecharge() *FamilyRecharge {
	_obj := familyrechargePool.Get()
	return _obj
}

// MarshalJSON
func (p *FamilyRecharge) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(10 * 50)
	if p.OrderNo != "" {
		write.WriteRaw("order_no", types.Marshal(p.OrderNo))
	}
	if p.Phone != "" {
		write.WriteRaw("phone", types.Marshal(p.Phone))
	}
	if p.PrepayId != "" {
		write.WriteRaw("prepay_id", types.Marshal(p.PrepayId))
	}
	if p.Amount != 0 {
		write.WriteRaw("amount", types.Marshal(p.Amount))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.ElderId != 0 {
		write.WriteRaw("elder_id", types.Marshal(p.ElderId))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	if p.State != 0 {
		write.WriteRaw("state", types.Marshal(p.State))
	}
	if p.Status != 0 {
		write.WriteRaw("status", types.Marshal(p.Status))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *FamilyRecharge) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "order_no":
			p.OrderNo = types.String(value.Str)
		case "phone":
			p.Phone = types.String(value.Str)
		case "prepay_id":
			p.PrepayId = types.String(value.Str)
		case "amount":
			e = types.Unmarshal(value, &p.Amount)
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "elder_id":
			e = types.Unmarshal(value, &p.ElderId)
		case "id":
			e = types.Unmarshal(value, &p.Id)
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		case "state":
			p.State = types.Int8(value.Int())
		case "status":
			p.Status = types.Uint8(value.Uint())
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *FamilyRecharge) Free() {
	if p == nil {
		return
	}

	familyrechargePool.Put(p)
}

// Reset
func (p *FamilyRecharge) Reset() {
	p.OrderNo = ""
	p.Phone = ""
	p.PrepayId = ""
	p.Amount = 0
	p.CreateTime = types.Time{}
	p.ElderId = 0
	p.Id = 0
	p.UpdateTime = types.Time{}
	p.State = 0
	p.Status = 0

}

func (p *FamilyRecharge) TableName() string {
	return "family_recharge"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var familyrechargeFieldToPtrFunc = map[string]func(*FamilyRecharge) any{
	tblfamilyrecharge.OrderNo.Name:    func(p *FamilyRecharge) any { return &p.OrderNo },
	tblfamilyrecharge.Phone.Name:      func(p *FamilyRecharge) any { return &p.Phone },
	tblfamilyrecharge.PrepayId.Name:   func(p *FamilyRecharge) any { return &p.PrepayId },
	tblfamilyrecharge.Amount.Name:     func(p *FamilyRecharge) any { return &p.Amount },
	tblfamilyrecharge.CreateTime.Name: func(p *FamilyRecharge) any { return &p.CreateTime },
	tblfamilyrecharge.ElderId.Name:    func(p *FamilyRecharge) any { return &p.ElderId },
	tblfamilyrecharge.Id.Name:         func(p *FamilyRecharge) any { return &p.Id },
	tblfamilyrecharge.UpdateTime.Name: func(p *FamilyRecharge) any { return &p.UpdateTime },
	tblfamilyrecharge.State.Name:      func(p *FamilyRecharge) any { return &p.State },
	tblfamilyrecharge.Status.Name:     func(p *FamilyRecharge) any { return &p.Status },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *FamilyRecharge) fieldPtr(args ...dialect.Field) []func(*FamilyRecharge) any {
	if len(args) == 0 {
		args = tblfamilyrecharge.ReadableFields
	}
	fs := make([]func(*FamilyRecharge) any, 0, len(args))
	for _, col := range args {
		if f, ok := familyrechargeFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *FamilyRecharge) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *FamilyRecharge) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if f, ok := familyrechargeFieldToPtrFunc[col]; ok {
			_vals = append(_vals, f(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *FamilyRecharge) Slice(rows *sql.Rows, args ...dialect.Field) ([]*FamilyRecharge, bool, error) {
	defer rows.Close()
	family_recharges := make([]*FamilyRecharge, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewFamilyRecharge()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		family_recharges = append(family_recharges, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return family_recharges, len(family_recharges) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *FamilyRecharge) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblfamilyrecharge.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var familyrechargeFieldToValueFunc = map[dialect.Field]func(*FamilyRecharge) (any, bool){
	tblfamilyrecharge.OrderNo: func(p *FamilyRecharge) (any, bool) {
		return p.OrderNo, p.OrderNo == ""
	},
	tblfamilyrecharge.Phone: func(p *FamilyRecharge) (any, bool) {
		return p.Phone, p.Phone == ""
	},
	tblfamilyrecharge.PrepayId: func(p *FamilyRecharge) (any, bool) {
		return p.PrepayId, p.PrepayId == ""
	},
	tblfamilyrecharge.Amount: func(p *FamilyRecharge) (any, bool) {
		return p.Amount, p.Amount == 0
	},
	tblfamilyrecharge.CreateTime: func(p *FamilyRecharge) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblfamilyrecharge.ElderId: func(p *FamilyRecharge) (any, bool) {
		return p.ElderId, p.ElderId == 0
	},
	tblfamilyrecharge.Id: func(p *FamilyRecharge) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblfamilyrecharge.UpdateTime: func(p *FamilyRecharge) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
	tblfamilyrecharge.State: func(p *FamilyRecharge) (any, bool) {
		return p.State, p.State == 0
	},
	tblfamilyrecharge.Status: func(p *FamilyRecharge) (any, bool) {
		return p.Status, p.Status == 0
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *FamilyRecharge) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblfamilyrecharge.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if f, has := familyrechargeFieldToValueFunc[arg]; has {
			value, isZero := f(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *FamilyRecharge) AssignKeys() (dialect.Field, any) {
	return tblfamilyrecharge.PrimaryKey, p.Id
}

func (p *FamilyRecharge) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
