// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblstaff"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

var (
	staffPool = pool.New[*Staff](func() any {
		_obj := &Staff{}
		return _obj
	})
)

func NewStaff() *Staff {
	_obj := staffPool.Get()
	return _obj
}

// MarshalJSON
func (p *Staff) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(17 * 50)
	if p.Address != "" {
		write.WriteRaw("address", types.Marshal(p.Address))
	}
	if p.Avator != "" {
		write.WriteRaw("avator", types.Marshal(p.Avator))
	}
	if p.Email != "" {
		write.WriteRaw("email", types.Marshal(p.Email))
	}
	if p.IdNum != "" {
		write.WriteRaw("id_num", types.Marshal(p.IdNum))
	}
	if p.Name != "" {
		write.WriteRaw("name", types.Marshal(p.Name))
	}
	if p.Pass != "" {
		write.WriteRaw("pass", types.Marshal(p.Pass))
	}
	if p.Phone != "" {
		write.WriteRaw("phone", types.Marshal(p.Phone))
	}
	if p.Sex != "" {
		write.WriteRaw("sex", types.Marshal(p.Sex))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.RoleId != 0 {
		write.WriteRaw("role_id", types.Marshal(p.RoleId))
	}
	if p.TenantId != 0 {
		write.WriteRaw("tenant_id", types.Marshal(p.TenantId))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	if p.Age != 0 {
		write.WriteRaw("age", types.Marshal(p.Age))
	}
	if p.Status != 0 {
		write.WriteRaw("status", types.Marshal(p.Status))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *Staff) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "address":
			p.Address = types.String(value.Str)
		case "avator":
			p.Avator = types.String(value.Str)
		case "email":
			p.Email = types.String(value.Str)
		case "id_num":
			p.IdNum = types.String(value.Str)
		case "name":
			p.Name = types.String(value.Str)
		case "pass":
			p.Pass = types.String(value.Str)
		case "phone":
			p.Phone = types.String(value.Str)
		case "sex":
			p.Sex = types.String(value.Str)
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "role_id":
			p.RoleId = types.BigInt(value.Uint())
		case "tenant_id":
			p.TenantId = types.BigInt(value.Uint())
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		case "age":
			p.Age = types.Int32(value.Int())
		case "status":
			p.Status = types.Int8(value.Int())
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *Staff) Free() {
	if p == nil {
		return
	}

	staffPool.Put(p)
}

// Reset
func (p *Staff) Reset() {
	p.Address = ""
	p.Avator = ""
	p.Email = ""
	p.IdNum = ""
	p.Name = ""
	p.Pass = ""
	p.Phone = ""
	p.Sex = ""
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.Id = 0
	p.RoleId = 0
	p.TenantId = 0
	p.UpdateId = 0
	p.UpdateTime = types.Time{}
	p.Age = 0
	p.Status = 0

}

func (p *Staff) TableName() string {
	return "staff"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var staffFieldToPtrFunc = map[string]func(*Staff) any{
	tblstaff.Address.Name:    func(p *Staff) any { return &p.Address },
	tblstaff.Avator.Name:     func(p *Staff) any { return &p.Avator },
	tblstaff.Email.Name:      func(p *Staff) any { return &p.Email },
	tblstaff.IdNum.Name:      func(p *Staff) any { return &p.IdNum },
	tblstaff.Name.Name:       func(p *Staff) any { return &p.Name },
	tblstaff.Pass.Name:       func(p *Staff) any { return &p.Pass },
	tblstaff.Phone.Name:      func(p *Staff) any { return &p.Phone },
	tblstaff.Sex.Name:        func(p *Staff) any { return &p.Sex },
	tblstaff.CreateId.Name:   func(p *Staff) any { return &p.CreateId },
	tblstaff.CreateTime.Name: func(p *Staff) any { return &p.CreateTime },
	tblstaff.Id.Name:         func(p *Staff) any { return &p.Id },
	tblstaff.RoleId.Name:     func(p *Staff) any { return &p.RoleId },
	tblstaff.TenantId.Name:   func(p *Staff) any { return &p.TenantId },
	tblstaff.UpdateId.Name:   func(p *Staff) any { return &p.UpdateId },
	tblstaff.UpdateTime.Name: func(p *Staff) any { return &p.UpdateTime },
	tblstaff.Age.Name:        func(p *Staff) any { return &p.Age },
	tblstaff.Status.Name:     func(p *Staff) any { return &p.Status },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *Staff) fieldPtr(args ...dialect.Field) []func(*Staff) any {
	if len(args) == 0 {
		args = tblstaff.ReadableFields
	}
	fs := make([]func(*Staff) any, 0, len(args))
	for _, col := range args {
		if f, ok := staffFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *Staff) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *Staff) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if f, ok := staffFieldToPtrFunc[col]; ok {
			_vals = append(_vals, f(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *Staff) Slice(rows *sql.Rows, args ...dialect.Field) ([]*Staff, bool, error) {
	defer rows.Close()
	staffs := make([]*Staff, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewStaff()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		staffs = append(staffs, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return staffs, len(staffs) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Staff) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblstaff.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var staffFieldToValueFunc = map[dialect.Field]func(*Staff) (any, bool){
	tblstaff.Address: func(p *Staff) (any, bool) {
		return p.Address, p.Address == ""
	},
	tblstaff.Avator: func(p *Staff) (any, bool) {
		return p.Avator, p.Avator == ""
	},
	tblstaff.Email: func(p *Staff) (any, bool) {
		return p.Email, p.Email == ""
	},
	tblstaff.IdNum: func(p *Staff) (any, bool) {
		return p.IdNum, p.IdNum == ""
	},
	tblstaff.Name: func(p *Staff) (any, bool) {
		return p.Name, p.Name == ""
	},
	tblstaff.Pass: func(p *Staff) (any, bool) {
		return p.Pass, p.Pass == ""
	},
	tblstaff.Phone: func(p *Staff) (any, bool) {
		return p.Phone, p.Phone == ""
	},
	tblstaff.Sex: func(p *Staff) (any, bool) {
		return p.Sex, p.Sex == ""
	},
	tblstaff.CreateId: func(p *Staff) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblstaff.CreateTime: func(p *Staff) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblstaff.Id: func(p *Staff) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblstaff.RoleId: func(p *Staff) (any, bool) {
		return p.RoleId, p.RoleId == 0
	},
	tblstaff.TenantId: func(p *Staff) (any, bool) {
		return p.TenantId, p.TenantId == 0
	},
	tblstaff.UpdateId: func(p *Staff) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblstaff.UpdateTime: func(p *Staff) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
	tblstaff.Age: func(p *Staff) (any, bool) {
		return p.Age, p.Age == 0
	},
	tblstaff.Status: func(p *Staff) (any, bool) {
		return p.Status, p.Status == 0
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Staff) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblstaff.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if f, has := staffFieldToValueFunc[arg]; has {
			value, isZero := f(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *Staff) AssignKeys() (dialect.Field, any) {
	return tblstaff.PrimaryKey, p.Id
}

func (p *Staff) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
