// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tbloutboundmaterial"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

var (
	outboundmaterialPool = pool.New[*OutboundMaterial](func() any {
		_obj := &OutboundMaterial{}
		return _obj
	})
)

func NewOutboundMaterial() *OutboundMaterial {
	_obj := outboundmaterialPool.Get()
	return _obj
}

// MarshalJSON
func (p *OutboundMaterial) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(10 * 50)
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.TenantId != 0 {
		write.WriteRaw("tenant_id", types.Marshal(p.TenantId))
	}
	if p.OutboundRecordId != 0 {
		write.WriteRaw("outbound_record_id", types.Marshal(p.OutboundRecordId))
	}
	if p.WarehouseMaterialId != 0 {
		write.WriteRaw("warehouse_material_id", types.Marshal(p.WarehouseMaterialId))
	}
	if p.MaterialId != 0 {
		write.WriteRaw("material_id", types.Marshal(p.MaterialId))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	if p.OutboundNum != 0 {
		write.WriteRaw("outbound_num", types.Marshal(p.OutboundNum))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *OutboundMaterial) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "tenant_id":
			p.TenantId = types.BigInt(value.Uint())
		case "outbound_record_id":
			p.OutboundRecordId = types.BigInt(value.Uint())
		case "warehouse_material_id":
			p.WarehouseMaterialId = types.BigInt(value.Uint())
		case "material_id":
			p.MaterialId = types.BigInt(value.Uint())
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		case "outbound_num":
			p.OutboundNum = types.Int32(value.Int())
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *OutboundMaterial) Free() {
	if p == nil {
		return
	}

	outboundmaterialPool.Put(p)
}

// Reset
func (p *OutboundMaterial) Reset() {
	p.Id = 0
	p.TenantId = 0
	p.OutboundRecordId = 0
	p.WarehouseMaterialId = 0
	p.MaterialId = 0
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}
	p.OutboundNum = 0

}

func (p *OutboundMaterial) TableName() string {
	return "outbound_material"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var outboundmaterialFieldToPtrFunc = map[string]func(*OutboundMaterial) any{
	tbloutboundmaterial.Id.Name:                  func(p *OutboundMaterial) any { return &p.Id },
	tbloutboundmaterial.TenantId.Name:            func(p *OutboundMaterial) any { return &p.TenantId },
	tbloutboundmaterial.OutboundRecordId.Name:    func(p *OutboundMaterial) any { return &p.OutboundRecordId },
	tbloutboundmaterial.WarehouseMaterialId.Name: func(p *OutboundMaterial) any { return &p.WarehouseMaterialId },
	tbloutboundmaterial.MaterialId.Name:          func(p *OutboundMaterial) any { return &p.MaterialId },
	tbloutboundmaterial.CreateId.Name:            func(p *OutboundMaterial) any { return &p.CreateId },
	tbloutboundmaterial.CreateTime.Name:          func(p *OutboundMaterial) any { return &p.CreateTime },
	tbloutboundmaterial.UpdateId.Name:            func(p *OutboundMaterial) any { return &p.UpdateId },
	tbloutboundmaterial.UpdateTime.Name:          func(p *OutboundMaterial) any { return &p.UpdateTime },
	tbloutboundmaterial.OutboundNum.Name:         func(p *OutboundMaterial) any { return &p.OutboundNum },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *OutboundMaterial) fieldPtr(args ...dialect.Field) []func(*OutboundMaterial) any {
	if len(args) == 0 {
		args = tbloutboundmaterial.ReadableFields
	}
	fs := make([]func(*OutboundMaterial) any, 0, len(args))
	for _, col := range args {
		if f, ok := outboundmaterialFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *OutboundMaterial) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *OutboundMaterial) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if f, ok := outboundmaterialFieldToPtrFunc[col]; ok {
			_vals = append(_vals, f(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *OutboundMaterial) Slice(rows *sql.Rows, args ...dialect.Field) ([]*OutboundMaterial, bool, error) {
	defer rows.Close()
	outbound_materials := make([]*OutboundMaterial, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewOutboundMaterial()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		outbound_materials = append(outbound_materials, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return outbound_materials, len(outbound_materials) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *OutboundMaterial) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tbloutboundmaterial.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var outboundmaterialFieldToValueFunc = map[dialect.Field]func(*OutboundMaterial) (any, bool){
	tbloutboundmaterial.Id: func(p *OutboundMaterial) (any, bool) {
		return p.Id, p.Id == 0
	},
	tbloutboundmaterial.TenantId: func(p *OutboundMaterial) (any, bool) {
		return p.TenantId, p.TenantId == 0
	},
	tbloutboundmaterial.OutboundRecordId: func(p *OutboundMaterial) (any, bool) {
		return p.OutboundRecordId, p.OutboundRecordId == 0
	},
	tbloutboundmaterial.WarehouseMaterialId: func(p *OutboundMaterial) (any, bool) {
		return p.WarehouseMaterialId, p.WarehouseMaterialId == 0
	},
	tbloutboundmaterial.MaterialId: func(p *OutboundMaterial) (any, bool) {
		return p.MaterialId, p.MaterialId == 0
	},
	tbloutboundmaterial.CreateId: func(p *OutboundMaterial) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tbloutboundmaterial.CreateTime: func(p *OutboundMaterial) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tbloutboundmaterial.UpdateId: func(p *OutboundMaterial) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tbloutboundmaterial.UpdateTime: func(p *OutboundMaterial) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
	tbloutboundmaterial.OutboundNum: func(p *OutboundMaterial) (any, bool) {
		return p.OutboundNum, p.OutboundNum == 0
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *OutboundMaterial) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tbloutboundmaterial.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if f, has := outboundmaterialFieldToValueFunc[arg]; has {
			value, isZero := f(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *OutboundMaterial) AssignKeys() (dialect.Field, any) {
	return tbloutboundmaterial.PrimaryKey, p.Id
}

func (p *OutboundMaterial) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
