// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblhealthinfo"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

var (
	healthinfoPool = pool.New[*HealthInfo](func() any {
		_obj := &HealthInfo{}
		return _obj
	})
)

func NewHealthInfo() *HealthInfo {
	_obj := healthinfoPool.Get()
	return _obj
}

// MarshalJSON
func (p *HealthInfo) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(16 * 50)
	if p.SelfCare != "" {
		write.WriteRaw("self_care", types.Marshal(p.SelfCare))
	}
	if p.TenantId != 0 {
		write.WriteRaw("tenant_id", types.Marshal(p.TenantId))
	}
	if p.Vision != "" {
		write.WriteRaw("vision", types.Marshal(p.Vision))
	}
	if p.Hearing != "" {
		write.WriteRaw("hearing", types.Marshal(p.Hearing))
	}
	if p.Hospital != "" {
		write.WriteRaw("hospital", types.Marshal(p.Hospital))
	}
	if p.Doctor != "" {
		write.WriteRaw("doctor", types.Marshal(p.Doctor))
	}
	if p.Phone != "" {
		write.WriteRaw("phone", types.Marshal(p.Phone))
	}
	if p.AllergyDrug != "" {
		write.WriteRaw("allergy_drug", types.Marshal(p.AllergyDrug))
	}
	if p.MedicalHistory != "" {
		write.WriteRaw("medical_history", types.Marshal(p.MedicalHistory))
	}
	if p.MajorDisease != "" {
		write.WriteRaw("major_disease", types.Marshal(p.MajorDisease))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.ElderId != 0 {
		write.WriteRaw("elder_id", types.Marshal(p.ElderId))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *HealthInfo) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "self_care":
			p.SelfCare = types.String(value.Str)
		case "tenant_id":
			p.TenantId = types.BigInt(value.Uint())
		case "vision":
			p.Vision = types.String(value.Str)
		case "hearing":
			p.Hearing = types.String(value.Str)
		case "hospital":
			p.Hospital = types.String(value.Str)
		case "doctor":
			p.Doctor = types.String(value.Str)
		case "phone":
			p.Phone = types.String(value.Str)
		case "allergy_drug":
			p.AllergyDrug = types.String(value.Str)
		case "medical_history":
			p.MedicalHistory = types.String(value.Str)
		case "major_disease":
			p.MajorDisease = types.String(value.Str)
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "elder_id":
			p.ElderId = types.BigInt(value.Uint())
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *HealthInfo) Free() {
	if p == nil {
		return
	}

	healthinfoPool.Put(p)
}

// Reset
func (p *HealthInfo) Reset() {
	p.SelfCare = ""
	p.TenantId = 0
	p.Vision = ""
	p.Hearing = ""
	p.Hospital = ""
	p.Doctor = ""
	p.Phone = ""
	p.AllergyDrug = ""
	p.MedicalHistory = ""
	p.MajorDisease = ""
	p.Id = 0
	p.ElderId = 0
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}

}

func (p *HealthInfo) TableName() string {
	return "health_info"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var healthinfoFieldToPtrFunc = map[string]func(*HealthInfo) any{
	tblhealthinfo.SelfCare.Name:       func(p *HealthInfo) any { return &p.SelfCare },
	tblhealthinfo.TenantId.Name:       func(p *HealthInfo) any { return &p.TenantId },
	tblhealthinfo.Vision.Name:         func(p *HealthInfo) any { return &p.Vision },
	tblhealthinfo.Hearing.Name:        func(p *HealthInfo) any { return &p.Hearing },
	tblhealthinfo.Hospital.Name:       func(p *HealthInfo) any { return &p.Hospital },
	tblhealthinfo.Doctor.Name:         func(p *HealthInfo) any { return &p.Doctor },
	tblhealthinfo.Phone.Name:          func(p *HealthInfo) any { return &p.Phone },
	tblhealthinfo.AllergyDrug.Name:    func(p *HealthInfo) any { return &p.AllergyDrug },
	tblhealthinfo.MedicalHistory.Name: func(p *HealthInfo) any { return &p.MedicalHistory },
	tblhealthinfo.MajorDisease.Name:   func(p *HealthInfo) any { return &p.MajorDisease },
	tblhealthinfo.Id.Name:             func(p *HealthInfo) any { return &p.Id },
	tblhealthinfo.ElderId.Name:        func(p *HealthInfo) any { return &p.ElderId },
	tblhealthinfo.CreateId.Name:       func(p *HealthInfo) any { return &p.CreateId },
	tblhealthinfo.CreateTime.Name:     func(p *HealthInfo) any { return &p.CreateTime },
	tblhealthinfo.UpdateId.Name:       func(p *HealthInfo) any { return &p.UpdateId },
	tblhealthinfo.UpdateTime.Name:     func(p *HealthInfo) any { return &p.UpdateTime },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *HealthInfo) fieldPtr(args ...dialect.Field) []func(*HealthInfo) any {
	if len(args) == 0 {
		args = tblhealthinfo.ReadableFields
	}
	fs := make([]func(*HealthInfo) any, 0, len(args))
	for _, col := range args {
		if f, ok := healthinfoFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *HealthInfo) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *HealthInfo) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if f, ok := healthinfoFieldToPtrFunc[col]; ok {
			_vals = append(_vals, f(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *HealthInfo) Slice(rows *sql.Rows, args ...dialect.Field) ([]*HealthInfo, bool, error) {
	defer rows.Close()
	health_infos := make([]*HealthInfo, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewHealthInfo()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		health_infos = append(health_infos, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return health_infos, len(health_infos) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *HealthInfo) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblhealthinfo.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var healthinfoFieldToValueFunc = map[dialect.Field]func(*HealthInfo) (any, bool){
	tblhealthinfo.SelfCare: func(p *HealthInfo) (any, bool) {
		return p.SelfCare, p.SelfCare == ""
	},
	tblhealthinfo.TenantId: func(p *HealthInfo) (any, bool) {
		return p.TenantId, p.TenantId == 0
	},
	tblhealthinfo.Vision: func(p *HealthInfo) (any, bool) {
		return p.Vision, p.Vision == ""
	},
	tblhealthinfo.Hearing: func(p *HealthInfo) (any, bool) {
		return p.Hearing, p.Hearing == ""
	},
	tblhealthinfo.Hospital: func(p *HealthInfo) (any, bool) {
		return p.Hospital, p.Hospital == ""
	},
	tblhealthinfo.Doctor: func(p *HealthInfo) (any, bool) {
		return p.Doctor, p.Doctor == ""
	},
	tblhealthinfo.Phone: func(p *HealthInfo) (any, bool) {
		return p.Phone, p.Phone == ""
	},
	tblhealthinfo.AllergyDrug: func(p *HealthInfo) (any, bool) {
		return p.AllergyDrug, p.AllergyDrug == ""
	},
	tblhealthinfo.MedicalHistory: func(p *HealthInfo) (any, bool) {
		return p.MedicalHistory, p.MedicalHistory == ""
	},
	tblhealthinfo.MajorDisease: func(p *HealthInfo) (any, bool) {
		return p.MajorDisease, p.MajorDisease == ""
	},
	tblhealthinfo.Id: func(p *HealthInfo) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblhealthinfo.ElderId: func(p *HealthInfo) (any, bool) {
		return p.ElderId, p.ElderId == 0
	},
	tblhealthinfo.CreateId: func(p *HealthInfo) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblhealthinfo.CreateTime: func(p *HealthInfo) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblhealthinfo.UpdateId: func(p *HealthInfo) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblhealthinfo.UpdateTime: func(p *HealthInfo) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *HealthInfo) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblhealthinfo.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if f, has := healthinfoFieldToValueFunc[arg]; has {
			value, isZero := f(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *HealthInfo) AssignKeys() (dialect.Field, any) {
	return tblhealthinfo.PrimaryKey, p.Id
}

func (p *HealthInfo) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
