// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblelderaccountledger"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

var (
	elderaccountledgerPool = pool.New[*ElderAccountLedger](func() any {
		_obj := &ElderAccountLedger{}
		return _obj
	})
)

func NewElderAccountLedger() *ElderAccountLedger {
	_obj := elderaccountledgerPool.Get()
	return _obj
}

// MarshalJSON
func (p *ElderAccountLedger) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(12 * 50)
	if p.BusinessNo != "" {
		write.WriteRaw("business_no", types.Marshal(p.BusinessNo))
	}
	if p.Remark != "" {
		write.WriteRaw("remark", types.Marshal(p.Remark))
	}
	if p.SourceType != "" {
		write.WriteRaw("source_type", types.Marshal(p.SourceType))
	}
	if p.Amount != 0 {
		write.WriteRaw("amount", types.Marshal(p.Amount))
	}
	if p.BalanceAfter != 0 {
		write.WriteRaw("balance_after", types.Marshal(p.BalanceAfter))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.ElderId != 0 {
		write.WriteRaw("elder_id", types.Marshal(p.ElderId))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.OperatorId != 0 {
		write.WriteRaw("operator_id", types.Marshal(p.OperatorId))
	}
	if p.SourceId != 0 {
		write.WriteRaw("source_id", types.Marshal(p.SourceId))
	}
	if p.TenantId != 0 {
		write.WriteRaw("tenant_id", types.Marshal(p.TenantId))
	}
	if p.Direction != 0 {
		write.WriteRaw("direction", types.Marshal(p.Direction))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *ElderAccountLedger) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "business_no":
			p.BusinessNo = types.String(value.Str)
		case "remark":
			p.Remark = types.String(value.Str)
		case "source_type":
			p.SourceType = types.String(value.Str)
		case "amount":
			e = types.Unmarshal(value, &p.Amount)
		case "balance_after":
			e = types.Unmarshal(value, &p.BalanceAfter)
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "elder_id":
			p.ElderId = types.BigInt(value.Uint())
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "operator_id":
			p.OperatorId = types.BigInt(value.Uint())
		case "source_id":
			p.SourceId = types.BigInt(value.Uint())
		case "tenant_id":
			p.TenantId = types.BigInt(value.Uint())
		case "direction":
			p.Direction = types.Int8(value.Int())
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *ElderAccountLedger) Free() {
	if p == nil {
		return
	}

	elderaccountledgerPool.Put(p)
}

// Reset
func (p *ElderAccountLedger) Reset() {
	p.BusinessNo = ""
	p.Remark = ""
	p.SourceType = ""
	p.Amount = 0
	p.BalanceAfter = 0
	p.CreateTime = types.Time{}
	p.ElderId = 0
	p.Id = 0
	p.OperatorId = 0
	p.SourceId = 0
	p.TenantId = 0
	p.Direction = 0

}

func (p *ElderAccountLedger) TableName() string {
	return "elder_account_ledger"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var elderaccountledgerFieldToPtrFunc = map[string]func(*ElderAccountLedger) any{
	tblelderaccountledger.BusinessNo.Name:   func(p *ElderAccountLedger) any { return &p.BusinessNo },
	tblelderaccountledger.Remark.Name:       func(p *ElderAccountLedger) any { return &p.Remark },
	tblelderaccountledger.SourceType.Name:   func(p *ElderAccountLedger) any { return &p.SourceType },
	tblelderaccountledger.Amount.Name:       func(p *ElderAccountLedger) any { return &p.Amount },
	tblelderaccountledger.BalanceAfter.Name: func(p *ElderAccountLedger) any { return &p.BalanceAfter },
	tblelderaccountledger.CreateTime.Name:   func(p *ElderAccountLedger) any { return &p.CreateTime },
	tblelderaccountledger.ElderId.Name:      func(p *ElderAccountLedger) any { return &p.ElderId },
	tblelderaccountledger.Id.Name:           func(p *ElderAccountLedger) any { return &p.Id },
	tblelderaccountledger.OperatorId.Name:   func(p *ElderAccountLedger) any { return &p.OperatorId },
	tblelderaccountledger.SourceId.Name:     func(p *ElderAccountLedger) any { return &p.SourceId },
	tblelderaccountledger.TenantId.Name:     func(p *ElderAccountLedger) any { return &p.TenantId },
	tblelderaccountledger.Direction.Name:    func(p *ElderAccountLedger) any { return &p.Direction },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *ElderAccountLedger) fieldPtr(args ...dialect.Field) []func(*ElderAccountLedger) any {
	if len(args) == 0 {
		args = tblelderaccountledger.ReadableFields
	}
	fs := make([]func(*ElderAccountLedger) any, 0, len(args))
	for _, col := range args {
		if f, ok := elderaccountledgerFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *ElderAccountLedger) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *ElderAccountLedger) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if f, ok := elderaccountledgerFieldToPtrFunc[col]; ok {
			_vals = append(_vals, f(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *ElderAccountLedger) Slice(rows *sql.Rows, args ...dialect.Field) ([]*ElderAccountLedger, bool, error) {
	defer rows.Close()
	elder_account_ledgers := make([]*ElderAccountLedger, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewElderAccountLedger()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		elder_account_ledgers = append(elder_account_ledgers, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return elder_account_ledgers, len(elder_account_ledgers) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *ElderAccountLedger) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblelderaccountledger.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var elderaccountledgerFieldToValueFunc = map[dialect.Field]func(*ElderAccountLedger) (any, bool){
	tblelderaccountledger.BusinessNo: func(p *ElderAccountLedger) (any, bool) {
		return p.BusinessNo, p.BusinessNo == ""
	},
	tblelderaccountledger.Remark: func(p *ElderAccountLedger) (any, bool) {
		return p.Remark, p.Remark == ""
	},
	tblelderaccountledger.SourceType: func(p *ElderAccountLedger) (any, bool) {
		return p.SourceType, p.SourceType == ""
	},
	tblelderaccountledger.Amount: func(p *ElderAccountLedger) (any, bool) {
		return p.Amount, p.Amount == 0
	},
	tblelderaccountledger.BalanceAfter: func(p *ElderAccountLedger) (any, bool) {
		return p.BalanceAfter, p.BalanceAfter == 0
	},
	tblelderaccountledger.CreateTime: func(p *ElderAccountLedger) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblelderaccountledger.ElderId: func(p *ElderAccountLedger) (any, bool) {
		return p.ElderId, p.ElderId == 0
	},
	tblelderaccountledger.Id: func(p *ElderAccountLedger) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblelderaccountledger.OperatorId: func(p *ElderAccountLedger) (any, bool) {
		return p.OperatorId, p.OperatorId == 0
	},
	tblelderaccountledger.SourceId: func(p *ElderAccountLedger) (any, bool) {
		return p.SourceId, p.SourceId == 0
	},
	tblelderaccountledger.TenantId: func(p *ElderAccountLedger) (any, bool) {
		return p.TenantId, p.TenantId == 0
	},
	tblelderaccountledger.Direction: func(p *ElderAccountLedger) (any, bool) {
		return p.Direction, p.Direction == 0
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *ElderAccountLedger) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblelderaccountledger.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if f, has := elderaccountledgerFieldToValueFunc[arg]; has {
			value, isZero := f(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *ElderAccountLedger) AssignKeys() (dialect.Field, any) {
	return tblelderaccountledger.PrimaryKey, p.Id
}

func (p *ElderAccountLedger) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
