// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblaccident"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

var (
	accidentPool = pool.New[*Accident](func() any {
		_obj := &Accident{}
		return _obj
	})
)

func NewAccident() *Accident {
	_obj := accidentPool.Get()
	return _obj
}

// MarshalJSON
func (p *Accident) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(12 * 50)
	if p.Description != "" {
		write.WriteRaw("description", types.Marshal(p.Description))
	}
	if p.Picture != "" {
		write.WriteRaw("picture", types.Marshal(p.Picture))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.TenantId != 0 {
		write.WriteRaw("tenant_id", types.Marshal(p.TenantId))
	}
	if p.ElderId != 0 {
		write.WriteRaw("elder_id", types.Marshal(p.ElderId))
	}
	if p.StaffId != 0 {
		write.WriteRaw("staff_id", types.Marshal(p.StaffId))
	}
	if !p.OccurDate.IsZero() {
		write.WriteRaw("occur_date", types.Marshal(p.OccurDate))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	if p.DelFlag != 0 {
		write.WriteRaw("del_flag", types.Marshal(p.DelFlag))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *Accident) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "description":
			p.Description = types.String(value.Str)
		case "picture":
			p.Picture = types.String(value.Str)
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "tenant_id":
			p.TenantId = types.BigInt(value.Uint())
		case "elder_id":
			p.ElderId = types.BigInt(value.Uint())
		case "staff_id":
			p.StaffId = types.BigInt(value.Uint())
		case "occur_date":
			p.OccurDate = types.Time{Time: value.Time()}
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		case "del_flag":
			p.DelFlag = types.Int8(value.Int())
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *Accident) Free() {
	if p == nil {
		return
	}

	accidentPool.Put(p)
}

// Reset
func (p *Accident) Reset() {
	p.Description = ""
	p.Picture = ""
	p.Id = 0
	p.TenantId = 0
	p.ElderId = 0
	p.StaffId = 0
	p.OccurDate = types.Time{}
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}
	p.DelFlag = 0

}

func (p *Accident) TableName() string {
	return "accident"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var accidentFieldToPtrFunc = map[string]func(*Accident) any{
	tblaccident.Description.Name: func(p *Accident) any { return &p.Description },
	tblaccident.Picture.Name:     func(p *Accident) any { return &p.Picture },
	tblaccident.Id.Name:          func(p *Accident) any { return &p.Id },
	tblaccident.TenantId.Name:    func(p *Accident) any { return &p.TenantId },
	tblaccident.ElderId.Name:     func(p *Accident) any { return &p.ElderId },
	tblaccident.StaffId.Name:     func(p *Accident) any { return &p.StaffId },
	tblaccident.OccurDate.Name:   func(p *Accident) any { return &p.OccurDate },
	tblaccident.CreateId.Name:    func(p *Accident) any { return &p.CreateId },
	tblaccident.CreateTime.Name:  func(p *Accident) any { return &p.CreateTime },
	tblaccident.UpdateId.Name:    func(p *Accident) any { return &p.UpdateId },
	tblaccident.UpdateTime.Name:  func(p *Accident) any { return &p.UpdateTime },
	tblaccident.DelFlag.Name:     func(p *Accident) any { return &p.DelFlag },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *Accident) fieldPtr(args ...dialect.Field) []func(*Accident) any {
	if len(args) == 0 {
		args = tblaccident.ReadableFields
	}
	fs := make([]func(*Accident) any, 0, len(args))
	for _, col := range args {
		if f, ok := accidentFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *Accident) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *Accident) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if f, ok := accidentFieldToPtrFunc[col]; ok {
			_vals = append(_vals, f(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *Accident) Slice(rows *sql.Rows, args ...dialect.Field) ([]*Accident, bool, error) {
	defer rows.Close()
	accidents := make([]*Accident, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewAccident()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		accidents = append(accidents, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return accidents, len(accidents) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Accident) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblaccident.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var accidentFieldToValueFunc = map[dialect.Field]func(*Accident) (any, bool){
	tblaccident.Description: func(p *Accident) (any, bool) {
		return p.Description, p.Description == ""
	},
	tblaccident.Picture: func(p *Accident) (any, bool) {
		return p.Picture, p.Picture == ""
	},
	tblaccident.Id: func(p *Accident) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblaccident.TenantId: func(p *Accident) (any, bool) {
		return p.TenantId, p.TenantId == 0
	},
	tblaccident.ElderId: func(p *Accident) (any, bool) {
		return p.ElderId, p.ElderId == 0
	},
	tblaccident.StaffId: func(p *Accident) (any, bool) {
		return p.StaffId, p.StaffId == 0
	},
	tblaccident.OccurDate: func(p *Accident) (any, bool) {
		return p.OccurDate, p.OccurDate.IsZero()
	},
	tblaccident.CreateId: func(p *Accident) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblaccident.CreateTime: func(p *Accident) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblaccident.UpdateId: func(p *Accident) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblaccident.UpdateTime: func(p *Accident) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
	tblaccident.DelFlag: func(p *Accident) (any, bool) {
		return p.DelFlag, p.DelFlag == 0
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Accident) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblaccident.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if f, has := accidentFieldToValueFunc[arg]; has {
			value, isZero := f(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *Accident) AssignKeys() (dialect.Field, any) {
	return tblaccident.PrimaryKey, p.Id
}

func (p *Accident) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
