// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblretreat"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

var (
	retreatPool = pool.New[*Retreat](func() any {
		_obj := &Retreat{}
		return _obj
	})
)

func NewRetreat() *Retreat {
	_obj := retreatPool.Get()
	return _obj
}

// MarshalJSON
func (p *Retreat) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(10 * 50)
	if p.RetreatForm != "" {
		write.WriteRaw("retreat_form", types.Marshal(p.RetreatForm))
	}
	if p.RetreatCause != "" {
		write.WriteRaw("retreat_cause", types.Marshal(p.RetreatCause))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.TenantId != 0 {
		write.WriteRaw("tenant_id", types.Marshal(p.TenantId))
	}
	if p.ElderId != 0 {
		write.WriteRaw("elder_id", types.Marshal(p.ElderId))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	if p.Evaluate != 0 {
		write.WriteRaw("evaluate", types.Marshal(p.Evaluate))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *Retreat) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "retreat_form":
			p.RetreatForm = types.String(value.Str)
		case "retreat_cause":
			p.RetreatCause = types.String(value.Str)
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "tenant_id":
			p.TenantId = types.BigInt(value.Uint())
		case "elder_id":
			p.ElderId = types.BigInt(value.Uint())
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		case "evaluate":
			p.Evaluate = types.Int32(value.Int())
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *Retreat) Free() {
	if p == nil {
		return
	}

	retreatPool.Put(p)
}

// Reset
func (p *Retreat) Reset() {
	p.RetreatForm = ""
	p.RetreatCause = ""
	p.Id = 0
	p.TenantId = 0
	p.ElderId = 0
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}
	p.Evaluate = 0

}

func (p *Retreat) TableName() string {
	return "retreat"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var retreatFieldToPtrFunc = map[string]func(*Retreat) any{
	tblretreat.RetreatForm.Name:  func(p *Retreat) any { return &p.RetreatForm },
	tblretreat.RetreatCause.Name: func(p *Retreat) any { return &p.RetreatCause },
	tblretreat.Id.Name:           func(p *Retreat) any { return &p.Id },
	tblretreat.TenantId.Name:     func(p *Retreat) any { return &p.TenantId },
	tblretreat.ElderId.Name:      func(p *Retreat) any { return &p.ElderId },
	tblretreat.CreateId.Name:     func(p *Retreat) any { return &p.CreateId },
	tblretreat.CreateTime.Name:   func(p *Retreat) any { return &p.CreateTime },
	tblretreat.UpdateId.Name:     func(p *Retreat) any { return &p.UpdateId },
	tblretreat.UpdateTime.Name:   func(p *Retreat) any { return &p.UpdateTime },
	tblretreat.Evaluate.Name:     func(p *Retreat) any { return &p.Evaluate },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *Retreat) fieldPtr(args ...dialect.Field) []func(*Retreat) any {
	if len(args) == 0 {
		args = tblretreat.ReadableFields
	}
	fs := make([]func(*Retreat) any, 0, len(args))
	for _, col := range args {
		if f, ok := retreatFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *Retreat) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *Retreat) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if f, ok := retreatFieldToPtrFunc[col]; ok {
			_vals = append(_vals, f(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *Retreat) Slice(rows *sql.Rows, args ...dialect.Field) ([]*Retreat, bool, error) {
	defer rows.Close()
	retreats := make([]*Retreat, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewRetreat()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		retreats = append(retreats, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return retreats, len(retreats) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Retreat) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblretreat.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var retreatFieldToValueFunc = map[dialect.Field]func(*Retreat) (any, bool){
	tblretreat.RetreatForm: func(p *Retreat) (any, bool) {
		return p.RetreatForm, p.RetreatForm == ""
	},
	tblretreat.RetreatCause: func(p *Retreat) (any, bool) {
		return p.RetreatCause, p.RetreatCause == ""
	},
	tblretreat.Id: func(p *Retreat) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblretreat.TenantId: func(p *Retreat) (any, bool) {
		return p.TenantId, p.TenantId == 0
	},
	tblretreat.ElderId: func(p *Retreat) (any, bool) {
		return p.ElderId, p.ElderId == 0
	},
	tblretreat.CreateId: func(p *Retreat) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblretreat.CreateTime: func(p *Retreat) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblretreat.UpdateId: func(p *Retreat) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblretreat.UpdateTime: func(p *Retreat) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
	tblretreat.Evaluate: func(p *Retreat) (any, bool) {
		return p.Evaluate, p.Evaluate == 0
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Retreat) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblretreat.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if f, has := retreatFieldToValueFunc[arg]; has {
			value, isZero := f(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *Retreat) AssignKeys() (dialect.Field, any) {
	return tblretreat.PrimaryKey, p.Id
}

func (p *Retreat) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
