// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tbluser"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

var (
	userPool = pool.New[*User](func() any {
		_obj := &User{}
		return _obj
	})
)

func NewUser() *User {
	_obj := userPool.Get()
	return _obj
}

// MarshalJSON
func (p *User) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(10 * 50)
	write.WriteRaw("id", types.Marshal(p.Id))
	write.WriteRaw("union_id", types.Marshal(p.UnionId))
	write.WriteRaw("openid", types.Marshal(p.Openid))
	write.WriteRaw("phone", types.Marshal(p.Phone))
	write.WriteRaw("pass", types.Marshal(p.Pass))
	write.WriteRaw("name", types.Marshal(p.Name))
	write.WriteRaw("avator", types.Marshal(p.Avator))
	write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	write.WriteRaw("del_flag", types.Marshal(p.DelFlag))
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *User) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "union_id":
			p.UnionId = types.String(value.Str)
		case "openid":
			p.Openid = types.String(value.Str)
		case "phone":
			p.Phone = types.String(value.Str)
		case "pass":
			p.Pass = types.String(value.Str)
		case "name":
			p.Name = types.String(value.Str)
		case "avator":
			p.Avator = types.String(value.Str)
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		case "del_flag":
			p.DelFlag = types.Int8(value.Int())
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *User) Free() {
	if p == nil {
		return
	}

	userPool.Put(p)
}

// Reset
func (p *User) Reset() {
	p.Id = 0
	p.UnionId = ""
	p.Openid = ""
	p.Phone = ""
	p.Pass = ""
	p.Name = ""
	p.Avator = ""
	p.CreateTime = types.Time{}
	p.UpdateTime = types.Time{}
	p.DelFlag = 0

}

func (p *User) TableName() string {
	return "user"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var userFieldToPtrFunc = map[string]func(*User) any{
	tbluser.Id.Name:         func(p *User) any { return &p.Id },
	tbluser.UnionId.Name:    func(p *User) any { return &p.UnionId },
	tbluser.Openid.Name:     func(p *User) any { return &p.Openid },
	tbluser.Phone.Name:      func(p *User) any { return &p.Phone },
	tbluser.Pass.Name:       func(p *User) any { return &p.Pass },
	tbluser.Name.Name:       func(p *User) any { return &p.Name },
	tbluser.Avator.Name:     func(p *User) any { return &p.Avator },
	tbluser.CreateTime.Name: func(p *User) any { return &p.CreateTime },
	tbluser.UpdateTime.Name: func(p *User) any { return &p.UpdateTime },
	tbluser.DelFlag.Name:    func(p *User) any { return &p.DelFlag },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *User) fieldPtr(args ...dialect.Field) []func(*User) any {
	if len(args) == 0 {
		args = tbluser.ReadableFields
	}
	fs := make([]func(*User) any, 0, len(args))
	for _, col := range args {
		if f, ok := userFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *User) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *User) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if f, ok := userFieldToPtrFunc[col]; ok {
			_vals = append(_vals, f(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *User) Slice(rows *sql.Rows, args ...dialect.Field) ([]*User, bool, error) {
	defer rows.Close()
	users := make([]*User, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewUser()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		users = append(users, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return users, len(users) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *User) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tbluser.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var userFieldToValueFunc = map[dialect.Field]func(*User) (any, bool){
	tbluser.Id: func(p *User) (any, bool) {
		return p.Id, p.Id == 0
	},
	tbluser.UnionId: func(p *User) (any, bool) {
		return p.UnionId, p.UnionId == ""
	},
	tbluser.Openid: func(p *User) (any, bool) {
		return p.Openid, p.Openid == ""
	},
	tbluser.Phone: func(p *User) (any, bool) {
		return p.Phone, p.Phone == ""
	},
	tbluser.Pass: func(p *User) (any, bool) {
		return p.Pass, p.Pass == ""
	},
	tbluser.Name: func(p *User) (any, bool) {
		return p.Name, p.Name == ""
	},
	tbluser.Avator: func(p *User) (any, bool) {
		return p.Avator, p.Avator == ""
	},
	tbluser.CreateTime: func(p *User) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tbluser.UpdateTime: func(p *User) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
	tbluser.DelFlag: func(p *User) (any, bool) {
		return p.DelFlag, p.DelFlag == 0
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *User) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tbluser.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if f, has := userFieldToValueFunc[arg]; has {
			value, isZero := f(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *User) AssignKeys() (dialect.Field, any) {
	return tbluser.PrimaryKey, p.Id
}

func (p *User) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
