// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblroomtransfer"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

var (
	roomtransferPool = pool.New[*RoomTransfer](func() any {
		_obj := &RoomTransfer{}
		return _obj
	})
)

func NewRoomTransfer() *RoomTransfer {
	_obj := roomtransferPool.Get()
	return _obj
}

// MarshalJSON
func (p *RoomTransfer) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(11 * 50)
	if p.Reason != "" {
		write.WriteRaw("reason", types.Marshal(p.Reason))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.ElderId != 0 {
		write.WriteRaw("elder_id", types.Marshal(p.ElderId))
	}
	if p.FromBedId != 0 {
		write.WriteRaw("from_bed_id", types.Marshal(p.FromBedId))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.TenantId != 0 {
		write.WriteRaw("tenant_id", types.Marshal(p.TenantId))
	}
	if p.ToBedId != 0 {
		write.WriteRaw("to_bed_id", types.Marshal(p.ToBedId))
	}
	if !p.TransferDate.IsZero() {
		write.WriteRaw("transfer_date", types.Marshal(p.TransferDate))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *RoomTransfer) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "reason":
			p.Reason = types.String(value.Str)
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "elder_id":
			p.ElderId = types.BigInt(value.Uint())
		case "from_bed_id":
			p.FromBedId = types.BigInt(value.Uint())
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "tenant_id":
			p.TenantId = types.BigInt(value.Uint())
		case "to_bed_id":
			p.ToBedId = types.BigInt(value.Uint())
		case "transfer_date":
			p.TransferDate = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *RoomTransfer) Free() {
	if p == nil {
		return
	}

	roomtransferPool.Put(p)
}

// Reset
func (p *RoomTransfer) Reset() {
	p.Reason = ""
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.ElderId = 0
	p.FromBedId = 0
	p.Id = 0
	p.TenantId = 0
	p.ToBedId = 0
	p.TransferDate = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}

}

func (p *RoomTransfer) TableName() string {
	return "room_transfer"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var roomtransferFieldToPtrFunc = map[string]func(*RoomTransfer) any{
	tblroomtransfer.Reason.Name:       func(p *RoomTransfer) any { return &p.Reason },
	tblroomtransfer.CreateId.Name:     func(p *RoomTransfer) any { return &p.CreateId },
	tblroomtransfer.CreateTime.Name:   func(p *RoomTransfer) any { return &p.CreateTime },
	tblroomtransfer.ElderId.Name:      func(p *RoomTransfer) any { return &p.ElderId },
	tblroomtransfer.FromBedId.Name:    func(p *RoomTransfer) any { return &p.FromBedId },
	tblroomtransfer.Id.Name:           func(p *RoomTransfer) any { return &p.Id },
	tblroomtransfer.TenantId.Name:     func(p *RoomTransfer) any { return &p.TenantId },
	tblroomtransfer.ToBedId.Name:      func(p *RoomTransfer) any { return &p.ToBedId },
	tblroomtransfer.TransferDate.Name: func(p *RoomTransfer) any { return &p.TransferDate },
	tblroomtransfer.UpdateId.Name:     func(p *RoomTransfer) any { return &p.UpdateId },
	tblroomtransfer.UpdateTime.Name:   func(p *RoomTransfer) any { return &p.UpdateTime },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *RoomTransfer) fieldPtr(args ...dialect.Field) []func(*RoomTransfer) any {
	if len(args) == 0 {
		args = tblroomtransfer.ReadableFields
	}
	fs := make([]func(*RoomTransfer) any, 0, len(args))
	for _, col := range args {
		if f, ok := roomtransferFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *RoomTransfer) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *RoomTransfer) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if f, ok := roomtransferFieldToPtrFunc[col]; ok {
			_vals = append(_vals, f(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *RoomTransfer) Slice(rows *sql.Rows, args ...dialect.Field) ([]*RoomTransfer, bool, error) {
	defer rows.Close()
	room_transfers := make([]*RoomTransfer, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewRoomTransfer()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		room_transfers = append(room_transfers, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return room_transfers, len(room_transfers) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *RoomTransfer) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblroomtransfer.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var roomtransferFieldToValueFunc = map[dialect.Field]func(*RoomTransfer) (any, bool){
	tblroomtransfer.Reason: func(p *RoomTransfer) (any, bool) {
		return p.Reason, p.Reason == ""
	},
	tblroomtransfer.CreateId: func(p *RoomTransfer) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblroomtransfer.CreateTime: func(p *RoomTransfer) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblroomtransfer.ElderId: func(p *RoomTransfer) (any, bool) {
		return p.ElderId, p.ElderId == 0
	},
	tblroomtransfer.FromBedId: func(p *RoomTransfer) (any, bool) {
		return p.FromBedId, p.FromBedId == 0
	},
	tblroomtransfer.Id: func(p *RoomTransfer) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblroomtransfer.TenantId: func(p *RoomTransfer) (any, bool) {
		return p.TenantId, p.TenantId == 0
	},
	tblroomtransfer.ToBedId: func(p *RoomTransfer) (any, bool) {
		return p.ToBedId, p.ToBedId == 0
	},
	tblroomtransfer.TransferDate: func(p *RoomTransfer) (any, bool) {
		return p.TransferDate, p.TransferDate.IsZero()
	},
	tblroomtransfer.UpdateId: func(p *RoomTransfer) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblroomtransfer.UpdateTime: func(p *RoomTransfer) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *RoomTransfer) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblroomtransfer.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if f, has := roomtransferFieldToValueFunc[arg]; has {
			value, isZero := f(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *RoomTransfer) AssignKeys() (dialect.Field, any) {
	return tblroomtransfer.PrimaryKey, p.Id
}

func (p *RoomTransfer) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
