// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblemergencycontact"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

var (
	emergencycontactPool = pool.New[*EmergencyContact](func() any {
		_obj := &EmergencyContact{}
		return _obj
	})
)

func NewEmergencyContact() *EmergencyContact {
	_obj := emergencycontactPool.Get()
	return _obj
}

// MarshalJSON
func (p *EmergencyContact) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(12 * 50)
	if p.Email != "" {
		write.WriteRaw("email", types.Marshal(p.Email))
	}
	if p.Name != "" {
		write.WriteRaw("name", types.Marshal(p.Name))
	}
	if p.Phone != "" {
		write.WriteRaw("phone", types.Marshal(p.Phone))
	}
	if p.Relation != "" {
		write.WriteRaw("relation", types.Marshal(p.Relation))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.ElderId != 0 {
		write.WriteRaw("elder_id", types.Marshal(p.ElderId))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.TenantId != 0 {
		write.WriteRaw("tenant_id", types.Marshal(p.TenantId))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	if p.Status != 0 {
		write.WriteRaw("status", types.Marshal(p.Status))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *EmergencyContact) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "email":
			p.Email = types.String(value.Str)
		case "name":
			p.Name = types.String(value.Str)
		case "phone":
			p.Phone = types.String(value.Str)
		case "relation":
			p.Relation = types.String(value.Str)
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "elder_id":
			p.ElderId = types.BigInt(value.Uint())
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "tenant_id":
			p.TenantId = types.BigInt(value.Uint())
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		case "status":
			p.Status = types.Int8(value.Int())
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *EmergencyContact) Free() {
	if p == nil {
		return
	}

	emergencycontactPool.Put(p)
}

// Reset
func (p *EmergencyContact) Reset() {
	p.Email = ""
	p.Name = ""
	p.Phone = ""
	p.Relation = ""
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.ElderId = 0
	p.Id = 0
	p.TenantId = 0
	p.UpdateId = 0
	p.UpdateTime = types.Time{}
	p.Status = 0

}

func (p *EmergencyContact) TableName() string {
	return "emergency_contact"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var emergencycontactFieldToPtrFunc = map[string]func(*EmergencyContact) any{
	tblemergencycontact.Email.Name:      func(p *EmergencyContact) any { return &p.Email },
	tblemergencycontact.Name.Name:       func(p *EmergencyContact) any { return &p.Name },
	tblemergencycontact.Phone.Name:      func(p *EmergencyContact) any { return &p.Phone },
	tblemergencycontact.Relation.Name:   func(p *EmergencyContact) any { return &p.Relation },
	tblemergencycontact.CreateId.Name:   func(p *EmergencyContact) any { return &p.CreateId },
	tblemergencycontact.CreateTime.Name: func(p *EmergencyContact) any { return &p.CreateTime },
	tblemergencycontact.ElderId.Name:    func(p *EmergencyContact) any { return &p.ElderId },
	tblemergencycontact.Id.Name:         func(p *EmergencyContact) any { return &p.Id },
	tblemergencycontact.TenantId.Name:   func(p *EmergencyContact) any { return &p.TenantId },
	tblemergencycontact.UpdateId.Name:   func(p *EmergencyContact) any { return &p.UpdateId },
	tblemergencycontact.UpdateTime.Name: func(p *EmergencyContact) any { return &p.UpdateTime },
	tblemergencycontact.Status.Name:     func(p *EmergencyContact) any { return &p.Status },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *EmergencyContact) fieldPtr(args ...dialect.Field) []func(*EmergencyContact) any {
	if len(args) == 0 {
		args = tblemergencycontact.ReadableFields
	}
	fs := make([]func(*EmergencyContact) any, 0, len(args))
	for _, col := range args {
		if f, ok := emergencycontactFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *EmergencyContact) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *EmergencyContact) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if f, ok := emergencycontactFieldToPtrFunc[col]; ok {
			_vals = append(_vals, f(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *EmergencyContact) Slice(rows *sql.Rows, args ...dialect.Field) ([]*EmergencyContact, bool, error) {
	defer rows.Close()
	emergency_contacts := make([]*EmergencyContact, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewEmergencyContact()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		emergency_contacts = append(emergency_contacts, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return emergency_contacts, len(emergency_contacts) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *EmergencyContact) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblemergencycontact.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var emergencycontactFieldToValueFunc = map[dialect.Field]func(*EmergencyContact) (any, bool){
	tblemergencycontact.Email: func(p *EmergencyContact) (any, bool) {
		return p.Email, p.Email == ""
	},
	tblemergencycontact.Name: func(p *EmergencyContact) (any, bool) {
		return p.Name, p.Name == ""
	},
	tblemergencycontact.Phone: func(p *EmergencyContact) (any, bool) {
		return p.Phone, p.Phone == ""
	},
	tblemergencycontact.Relation: func(p *EmergencyContact) (any, bool) {
		return p.Relation, p.Relation == ""
	},
	tblemergencycontact.CreateId: func(p *EmergencyContact) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblemergencycontact.CreateTime: func(p *EmergencyContact) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblemergencycontact.ElderId: func(p *EmergencyContact) (any, bool) {
		return p.ElderId, p.ElderId == 0
	},
	tblemergencycontact.Id: func(p *EmergencyContact) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblemergencycontact.TenantId: func(p *EmergencyContact) (any, bool) {
		return p.TenantId, p.TenantId == 0
	},
	tblemergencycontact.UpdateId: func(p *EmergencyContact) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblemergencycontact.UpdateTime: func(p *EmergencyContact) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
	tblemergencycontact.Status: func(p *EmergencyContact) (any, bool) {
		return p.Status, p.Status == 0
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *EmergencyContact) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblemergencycontact.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if f, has := emergencycontactFieldToValueFunc[arg]; has {
			value, isZero := f(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *EmergencyContact) AssignKeys() (dialect.Field, any) {
	return tblemergencycontact.PrimaryKey, p.Id
}

func (p *EmergencyContact) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
