// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblelder"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

var (
	elderPool = pool.New[*Elder](func() any {
		_obj := &Elder{}
		return _obj
	})
)

func NewElder() *Elder {
	_obj := elderPool.Get()
	return _obj
}

// MarshalJSON
func (p *Elder) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(16 * 50)
	if p.Name != "" {
		write.WriteRaw("name", types.Marshal(p.Name))
	}
	if p.IdNum != "" {
		write.WriteRaw("id_num", types.Marshal(p.IdNum))
	}
	if p.Sex != "" {
		write.WriteRaw("sex", types.Marshal(p.Sex))
	}
	if p.Phone != "" {
		write.WriteRaw("phone", types.Marshal(p.Phone))
	}
	if p.Address != "" {
		write.WriteRaw("address", types.Marshal(p.Address))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.NursingGradeId != 0 {
		write.WriteRaw("nursing_grade_id", types.Marshal(p.NursingGradeId))
	}
	if p.CateringSetId != 0 {
		write.WriteRaw("catering_set_id", types.Marshal(p.CateringSetId))
	}
	if p.BedId != 0 {
		write.WriteRaw("bed_id", types.Marshal(p.BedId))
	}
	if p.Balance != 0 {
		write.WriteRaw("balance", types.Marshal(p.Balance))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	if p.Age != 0 {
		write.WriteRaw("age", types.Marshal(p.Age))
	}
	if p.CheckFlag != 0 {
		write.WriteRaw("check_flag", types.Marshal(p.CheckFlag))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *Elder) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "name":
			p.Name = types.String(value.Str)
		case "id_num":
			p.IdNum = types.String(value.Str)
		case "sex":
			p.Sex = types.String(value.Str)
		case "phone":
			p.Phone = types.String(value.Str)
		case "address":
			p.Address = types.String(value.Str)
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "nursing_grade_id":
			p.NursingGradeId = types.BigInt(value.Uint())
		case "catering_set_id":
			p.CateringSetId = types.BigInt(value.Uint())
		case "bed_id":
			p.BedId = types.BigInt(value.Uint())
		case "balance":
			e = types.Unmarshal(value, &p.Balance)
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		case "age":
			p.Age = types.Int32(value.Int())
		case "check_flag":
			p.CheckFlag = types.Int8(value.Int())
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *Elder) Free() {
	if p == nil {
		return
	}

	elderPool.Put(p)
}

// Reset
func (p *Elder) Reset() {
	p.Name = ""
	p.IdNum = ""
	p.Sex = ""
	p.Phone = ""
	p.Address = ""
	p.Id = 0
	p.NursingGradeId = 0
	p.CateringSetId = 0
	p.BedId = 0
	p.Balance = 0
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}
	p.Age = 0
	p.CheckFlag = 0

}

func (p *Elder) TableName() string {
	return "elder"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var elderFieldToPtrFunc = map[string]func(*Elder) any{
	tblelder.Name.Name:           func(p *Elder) any { return &p.Name },
	tblelder.IdNum.Name:          func(p *Elder) any { return &p.IdNum },
	tblelder.Sex.Name:            func(p *Elder) any { return &p.Sex },
	tblelder.Phone.Name:          func(p *Elder) any { return &p.Phone },
	tblelder.Address.Name:        func(p *Elder) any { return &p.Address },
	tblelder.Id.Name:             func(p *Elder) any { return &p.Id },
	tblelder.NursingGradeId.Name: func(p *Elder) any { return &p.NursingGradeId },
	tblelder.CateringSetId.Name:  func(p *Elder) any { return &p.CateringSetId },
	tblelder.BedId.Name:          func(p *Elder) any { return &p.BedId },
	tblelder.Balance.Name:        func(p *Elder) any { return &p.Balance },
	tblelder.CreateId.Name:       func(p *Elder) any { return &p.CreateId },
	tblelder.CreateTime.Name:     func(p *Elder) any { return &p.CreateTime },
	tblelder.UpdateId.Name:       func(p *Elder) any { return &p.UpdateId },
	tblelder.UpdateTime.Name:     func(p *Elder) any { return &p.UpdateTime },
	tblelder.Age.Name:            func(p *Elder) any { return &p.Age },
	tblelder.CheckFlag.Name:      func(p *Elder) any { return &p.CheckFlag },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *Elder) fieldPtr(args ...dialect.Field) []func(*Elder) any {
	if len(args) == 0 {
		args = tblelder.ReadableFields
	}
	fs := make([]func(*Elder) any, 0, len(args))
	for _, col := range args {
		if f, ok := elderFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *Elder) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *Elder) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if f, ok := elderFieldToPtrFunc[col]; ok {
			_vals = append(_vals, f(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *Elder) Slice(rows *sql.Rows, args ...dialect.Field) ([]*Elder, bool, error) {
	defer rows.Close()
	elders := make([]*Elder, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewElder()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		elders = append(elders, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return elders, len(elders) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Elder) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblelder.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var elderFieldToValueFunc = map[dialect.Field]func(*Elder) (any, bool){
	tblelder.Name: func(p *Elder) (any, bool) {
		return p.Name, p.Name == ""
	},
	tblelder.IdNum: func(p *Elder) (any, bool) {
		return p.IdNum, p.IdNum == ""
	},
	tblelder.Sex: func(p *Elder) (any, bool) {
		return p.Sex, p.Sex == ""
	},
	tblelder.Phone: func(p *Elder) (any, bool) {
		return p.Phone, p.Phone == ""
	},
	tblelder.Address: func(p *Elder) (any, bool) {
		return p.Address, p.Address == ""
	},
	tblelder.Id: func(p *Elder) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblelder.NursingGradeId: func(p *Elder) (any, bool) {
		return p.NursingGradeId, p.NursingGradeId == 0
	},
	tblelder.CateringSetId: func(p *Elder) (any, bool) {
		return p.CateringSetId, p.CateringSetId == 0
	},
	tblelder.BedId: func(p *Elder) (any, bool) {
		return p.BedId, p.BedId == 0
	},
	tblelder.Balance: func(p *Elder) (any, bool) {
		return p.Balance, p.Balance == 0
	},
	tblelder.CreateId: func(p *Elder) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblelder.CreateTime: func(p *Elder) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblelder.UpdateId: func(p *Elder) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblelder.UpdateTime: func(p *Elder) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
	tblelder.Age: func(p *Elder) (any, bool) {
		return p.Age, p.Age == 0
	},
	tblelder.CheckFlag: func(p *Elder) (any, bool) {
		return p.CheckFlag, p.CheckFlag == 0
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Elder) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblelder.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if f, has := elderFieldToValueFunc[arg]; has {
			value, isZero := f(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *Elder) AssignKeys() (dialect.Field, any) {
	return tblelder.PrimaryKey, p.Id
}

func (p *Elder) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
