// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblauditlog"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

var (
	auditlogPool = pool.New[*AuditLog](func() any {
		_obj := &AuditLog{}
		return _obj
	})
)

func NewAuditLog() *AuditLog {
	_obj := auditlogPool.Get()
	return _obj
}

// MarshalJSON
func (p *AuditLog) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(11 * 50)
	if p.Action != "" {
		write.WriteRaw("action", types.Marshal(p.Action))
	}
	if p.ChangeAfter != "" {
		write.WriteRaw("change_after", types.Marshal(p.ChangeAfter))
	}
	if p.ChangeLabel != "" {
		write.WriteRaw("change_label", types.Marshal(p.ChangeLabel))
	}
	if p.Comment != "" {
		write.WriteRaw("comment", types.Marshal(p.Comment))
	}
	if p.OperatorName != "" {
		write.WriteRaw("operator_name", types.Marshal(p.OperatorName))
	}
	if p.Table != "" {
		write.WriteRaw("table", types.Marshal(p.Table))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.OperatorId != 0 {
		write.WriteRaw("operator_id", types.Marshal(p.OperatorId))
	}
	if p.RowId != 0 {
		write.WriteRaw("row_id", types.Marshal(p.RowId))
	}
	if p.TenantId != 0 {
		write.WriteRaw("tenant_id", types.Marshal(p.TenantId))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *AuditLog) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "action":
			p.Action = types.String(value.Str)
		case "change_after":
			p.ChangeAfter = types.String(value.Str)
		case "change_label":
			p.ChangeLabel = types.String(value.Str)
		case "comment":
			p.Comment = types.String(value.Str)
		case "operator_name":
			p.OperatorName = types.String(value.Str)
		case "table":
			p.Table = types.String(value.Str)
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "operator_id":
			p.OperatorId = types.BigInt(value.Uint())
		case "row_id":
			p.RowId = types.BigInt(value.Uint())
		case "tenant_id":
			p.TenantId = types.BigInt(value.Uint())
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *AuditLog) Free() {
	if p == nil {
		return
	}

	auditlogPool.Put(p)
}

// Reset
func (p *AuditLog) Reset() {
	p.Action = ""
	p.ChangeAfter = ""
	p.ChangeLabel = ""
	p.Comment = ""
	p.OperatorName = ""
	p.Table = ""
	p.CreateTime = types.Time{}
	p.Id = 0
	p.OperatorId = 0
	p.RowId = 0
	p.TenantId = 0

}

func (p *AuditLog) TableName() string {
	return "audit_log"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var auditlogFieldToPtrFunc = map[string]func(*AuditLog) any{
	tblauditlog.Action.Name:       func(p *AuditLog) any { return &p.Action },
	tblauditlog.ChangeAfter.Name:  func(p *AuditLog) any { return &p.ChangeAfter },
	tblauditlog.ChangeLabel.Name:  func(p *AuditLog) any { return &p.ChangeLabel },
	tblauditlog.Comment.Name:      func(p *AuditLog) any { return &p.Comment },
	tblauditlog.OperatorName.Name: func(p *AuditLog) any { return &p.OperatorName },
	tblauditlog.Table.Name:        func(p *AuditLog) any { return &p.Table },
	tblauditlog.CreateTime.Name:   func(p *AuditLog) any { return &p.CreateTime },
	tblauditlog.Id.Name:           func(p *AuditLog) any { return &p.Id },
	tblauditlog.OperatorId.Name:   func(p *AuditLog) any { return &p.OperatorId },
	tblauditlog.RowId.Name:        func(p *AuditLog) any { return &p.RowId },
	tblauditlog.TenantId.Name:     func(p *AuditLog) any { return &p.TenantId },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *AuditLog) fieldPtr(args ...dialect.Field) []func(*AuditLog) any {
	if len(args) == 0 {
		args = tblauditlog.ReadableFields
	}
	fs := make([]func(*AuditLog) any, 0, len(args))
	for _, col := range args {
		if f, ok := auditlogFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *AuditLog) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *AuditLog) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if f, ok := auditlogFieldToPtrFunc[col]; ok {
			_vals = append(_vals, f(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *AuditLog) Slice(rows *sql.Rows, args ...dialect.Field) ([]*AuditLog, bool, error) {
	defer rows.Close()
	audit_logs := make([]*AuditLog, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewAuditLog()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		audit_logs = append(audit_logs, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return audit_logs, len(audit_logs) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *AuditLog) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblauditlog.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var auditlogFieldToValueFunc = map[dialect.Field]func(*AuditLog) (any, bool){
	tblauditlog.Action: func(p *AuditLog) (any, bool) {
		return p.Action, p.Action == ""
	},
	tblauditlog.ChangeAfter: func(p *AuditLog) (any, bool) {
		return p.ChangeAfter, p.ChangeAfter == ""
	},
	tblauditlog.ChangeLabel: func(p *AuditLog) (any, bool) {
		return p.ChangeLabel, p.ChangeLabel == ""
	},
	tblauditlog.Comment: func(p *AuditLog) (any, bool) {
		return p.Comment, p.Comment == ""
	},
	tblauditlog.OperatorName: func(p *AuditLog) (any, bool) {
		return p.OperatorName, p.OperatorName == ""
	},
	tblauditlog.Table: func(p *AuditLog) (any, bool) {
		return p.Table, p.Table == ""
	},
	tblauditlog.CreateTime: func(p *AuditLog) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblauditlog.Id: func(p *AuditLog) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblauditlog.OperatorId: func(p *AuditLog) (any, bool) {
		return p.OperatorId, p.OperatorId == 0
	},
	tblauditlog.RowId: func(p *AuditLog) (any, bool) {
		return p.RowId, p.RowId == 0
	},
	tblauditlog.TenantId: func(p *AuditLog) (any, bool) {
		return p.TenantId, p.TenantId == 0
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *AuditLog) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblauditlog.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if f, has := auditlogFieldToValueFunc[arg]; has {
			value, isZero := f(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *AuditLog) AssignKeys() (dialect.Field, any) {
	return tblauditlog.PrimaryKey, p.Id
}

func (p *AuditLog) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
