// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tbloutboundrecorditem"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

var (
	outboundrecorditemPool = pool.New[*OutboundRecordItem](func() any {
		_obj := &OutboundRecordItem{}
		return _obj
	})
)

func NewOutboundRecordItem() *OutboundRecordItem {
	_obj := outboundrecorditemPool.Get()
	return _obj
}

// MarshalJSON
func (p *OutboundRecordItem) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(10 * 50)
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.MaterialId != 0 {
		write.WriteRaw("material_id", types.Marshal(p.MaterialId))
	}
	if p.RecordId != 0 {
		write.WriteRaw("record_id", types.Marshal(p.RecordId))
	}
	if p.StockId != nil {
		write.WriteRaw("stock_id", types.Marshal(p.StockId))
	}
	if p.TenantId != 0 {
		write.WriteRaw("tenant_id", types.Marshal(p.TenantId))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	if p.Qty != 0 {
		write.WriteRaw("qty", types.Marshal(p.Qty))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *OutboundRecordItem) UnmarshalJSON(data []byte) error {
	defer func() {
		if r := recover(); r != nil {
			log.Error(r)
			return
		}
	}()

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "material_id":
			p.MaterialId = types.BigInt(value.Uint())
		case "record_id":
			p.RecordId = types.BigInt(value.Uint())
		case "stock_id":
			e = types.Unmarshal(value, &p.StockId, func(value gjson.Result) *types.BigInt {
				var obj *types.BigInt
				e := types.Unmarshal(value, &obj)
				if e != nil {
					panic(e)
				}
				return obj
			}(value))
		case "tenant_id":
			p.TenantId = types.BigInt(value.Uint())
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		case "qty":
			p.Qty = types.Int32(value.Int())
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *OutboundRecordItem) Free() {
	if p == nil {
		return
	}

	outboundrecorditemPool.Put(p)
}

// Reset
func (p *OutboundRecordItem) Reset() {
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.Id = 0
	p.MaterialId = 0
	p.RecordId = 0
	p.StockId = new(types.BigInt)
	p.TenantId = 0
	p.UpdateId = 0
	p.UpdateTime = types.Time{}
	p.Qty = 0

}

func (p *OutboundRecordItem) TableName() string {
	return "outbound_record_item"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var outboundrecorditemFieldToPtrFunc = map[string]func(*OutboundRecordItem) any{
	tbloutboundrecorditem.CreateId.Name:   func(p *OutboundRecordItem) any { return &p.CreateId },
	tbloutboundrecorditem.CreateTime.Name: func(p *OutboundRecordItem) any { return &p.CreateTime },
	tbloutboundrecorditem.Id.Name:         func(p *OutboundRecordItem) any { return &p.Id },
	tbloutboundrecorditem.MaterialId.Name: func(p *OutboundRecordItem) any { return &p.MaterialId },
	tbloutboundrecorditem.RecordId.Name:   func(p *OutboundRecordItem) any { return &p.RecordId },
	tbloutboundrecorditem.StockId.Name:    func(p *OutboundRecordItem) any { return &p.StockId },
	tbloutboundrecorditem.TenantId.Name:   func(p *OutboundRecordItem) any { return &p.TenantId },
	tbloutboundrecorditem.UpdateId.Name:   func(p *OutboundRecordItem) any { return &p.UpdateId },
	tbloutboundrecorditem.UpdateTime.Name: func(p *OutboundRecordItem) any { return &p.UpdateTime },
	tbloutboundrecorditem.Qty.Name:        func(p *OutboundRecordItem) any { return &p.Qty },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *OutboundRecordItem) fieldPtr(args ...dialect.Field) []func(*OutboundRecordItem) any {
	if len(args) == 0 {
		args = tbloutboundrecorditem.ReadableFields
	}
	fs := make([]func(*OutboundRecordItem) any, 0, len(args))
	for _, col := range args {
		if f, ok := outboundrecorditemFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *OutboundRecordItem) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *OutboundRecordItem) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if f, ok := outboundrecorditemFieldToPtrFunc[col]; ok {
			_vals = append(_vals, f(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *OutboundRecordItem) Slice(rows *sql.Rows, args ...dialect.Field) ([]*OutboundRecordItem, bool, error) {
	defer rows.Close()
	outbound_record_items := make([]*OutboundRecordItem, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewOutboundRecordItem()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		outbound_record_items = append(outbound_record_items, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return outbound_record_items, len(outbound_record_items) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *OutboundRecordItem) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tbloutboundrecorditem.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var outboundrecorditemFieldToValueFunc = map[dialect.Field]func(*OutboundRecordItem) (any, bool){
	tbloutboundrecorditem.CreateId: func(p *OutboundRecordItem) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tbloutboundrecorditem.CreateTime: func(p *OutboundRecordItem) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tbloutboundrecorditem.Id: func(p *OutboundRecordItem) (any, bool) {
		return p.Id, p.Id == 0
	},
	tbloutboundrecorditem.MaterialId: func(p *OutboundRecordItem) (any, bool) {
		return p.MaterialId, p.MaterialId == 0
	},
	tbloutboundrecorditem.RecordId: func(p *OutboundRecordItem) (any, bool) {
		return p.RecordId, p.RecordId == 0
	},
	tbloutboundrecorditem.TenantId: func(p *OutboundRecordItem) (any, bool) {
		return p.TenantId, p.TenantId == 0
	},
	tbloutboundrecorditem.UpdateId: func(p *OutboundRecordItem) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tbloutboundrecorditem.UpdateTime: func(p *OutboundRecordItem) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
	tbloutboundrecorditem.Qty: func(p *OutboundRecordItem) (any, bool) {
		return p.Qty, p.Qty == 0
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *OutboundRecordItem) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tbloutboundrecorditem.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if f, has := outboundrecorditemFieldToValueFunc[arg]; has {
			value, isZero := f(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *OutboundRecordItem) AssignKeys() (dialect.Field, any) {
	return tbloutboundrecorditem.PrimaryKey, p.Id
}

func (p *OutboundRecordItem) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
