// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblorder"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

var (
	orderPool = pool.New[*Order](func() any {
		_obj := &Order{}
		return _obj
	})
)

func NewOrder() *Order {
	_obj := orderPool.Get()
	return _obj
}

// MarshalJSON
func (p *Order) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(14 * 50)
	if p.DineType != "" {
		write.WriteRaw("dine_type", types.Marshal(p.DineType))
	}
	if p.OutTradeNo != "" {
		write.WriteRaw("out_trade_no", types.Marshal(p.OutTradeNo))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if !p.DeliverDishesDate.IsZero() {
		write.WriteRaw("deliver_dishes_date", types.Marshal(p.DeliverDishesDate))
	}
	if !p.DineDate.IsZero() {
		write.WriteRaw("dine_date", types.Marshal(p.DineDate))
	}
	if p.ElderId != 0 {
		write.WriteRaw("elder_id", types.Marshal(p.ElderId))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.PayAmount != 0 {
		write.WriteRaw("pay_amount", types.Marshal(p.PayAmount))
	}
	if p.StaffId != 0 {
		write.WriteRaw("staff_id", types.Marshal(p.StaffId))
	}
	if p.TenantId != 0 {
		write.WriteRaw("tenant_id", types.Marshal(p.TenantId))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	if p.Status != 0 {
		write.WriteRaw("status", types.Marshal(p.Status))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *Order) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "dine_type":
			p.DineType = types.String(value.Str)
		case "out_trade_no":
			p.OutTradeNo = types.String(value.Str)
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "deliver_dishes_date":
			p.DeliverDishesDate = types.Time{Time: value.Time()}
		case "dine_date":
			p.DineDate = types.Time{Time: value.Time()}
		case "elder_id":
			p.ElderId = types.BigInt(value.Uint())
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "pay_amount":
			e = types.Unmarshal(value, &p.PayAmount)
		case "staff_id":
			p.StaffId = types.BigInt(value.Uint())
		case "tenant_id":
			p.TenantId = types.BigInt(value.Uint())
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		case "status":
			p.Status = types.Uint8(value.Uint())
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *Order) Free() {
	if p == nil {
		return
	}

	orderPool.Put(p)
}

// Reset
func (p *Order) Reset() {
	p.DineType = ""
	p.OutTradeNo = ""
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.DeliverDishesDate = types.Time{}
	p.DineDate = types.Time{}
	p.ElderId = 0
	p.Id = 0
	p.PayAmount = 0
	p.StaffId = 0
	p.TenantId = 0
	p.UpdateId = 0
	p.UpdateTime = types.Time{}
	p.Status = 0

}

func (p *Order) TableName() string {
	return "order"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var orderFieldToPtrFunc = map[string]func(*Order) any{
	tblorder.DineType.Name:          func(p *Order) any { return &p.DineType },
	tblorder.OutTradeNo.Name:        func(p *Order) any { return &p.OutTradeNo },
	tblorder.CreateId.Name:          func(p *Order) any { return &p.CreateId },
	tblorder.CreateTime.Name:        func(p *Order) any { return &p.CreateTime },
	tblorder.DeliverDishesDate.Name: func(p *Order) any { return &p.DeliverDishesDate },
	tblorder.DineDate.Name:          func(p *Order) any { return &p.DineDate },
	tblorder.ElderId.Name:           func(p *Order) any { return &p.ElderId },
	tblorder.Id.Name:                func(p *Order) any { return &p.Id },
	tblorder.PayAmount.Name:         func(p *Order) any { return &p.PayAmount },
	tblorder.StaffId.Name:           func(p *Order) any { return &p.StaffId },
	tblorder.TenantId.Name:          func(p *Order) any { return &p.TenantId },
	tblorder.UpdateId.Name:          func(p *Order) any { return &p.UpdateId },
	tblorder.UpdateTime.Name:        func(p *Order) any { return &p.UpdateTime },
	tblorder.Status.Name:            func(p *Order) any { return &p.Status },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *Order) fieldPtr(args ...dialect.Field) []func(*Order) any {
	if len(args) == 0 {
		args = tblorder.ReadableFields
	}
	fs := make([]func(*Order) any, 0, len(args))
	for _, col := range args {
		if f, ok := orderFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *Order) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *Order) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if f, ok := orderFieldToPtrFunc[col]; ok {
			_vals = append(_vals, f(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *Order) Slice(rows *sql.Rows, args ...dialect.Field) ([]*Order, bool, error) {
	defer rows.Close()
	orders := make([]*Order, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewOrder()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		orders = append(orders, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return orders, len(orders) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Order) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblorder.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var orderFieldToValueFunc = map[dialect.Field]func(*Order) (any, bool){
	tblorder.DineType: func(p *Order) (any, bool) {
		return p.DineType, p.DineType == ""
	},
	tblorder.OutTradeNo: func(p *Order) (any, bool) {
		return p.OutTradeNo, p.OutTradeNo == ""
	},
	tblorder.CreateId: func(p *Order) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblorder.CreateTime: func(p *Order) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblorder.DeliverDishesDate: func(p *Order) (any, bool) {
		return p.DeliverDishesDate, p.DeliverDishesDate.IsZero()
	},
	tblorder.DineDate: func(p *Order) (any, bool) {
		return p.DineDate, p.DineDate.IsZero()
	},
	tblorder.ElderId: func(p *Order) (any, bool) {
		return p.ElderId, p.ElderId == 0
	},
	tblorder.Id: func(p *Order) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblorder.PayAmount: func(p *Order) (any, bool) {
		return p.PayAmount, p.PayAmount == 0
	},
	tblorder.StaffId: func(p *Order) (any, bool) {
		return p.StaffId, p.StaffId == 0
	},
	tblorder.TenantId: func(p *Order) (any, bool) {
		return p.TenantId, p.TenantId == 0
	},
	tblorder.UpdateId: func(p *Order) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblorder.UpdateTime: func(p *Order) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
	tblorder.Status: func(p *Order) (any, bool) {
		return p.Status, p.Status == 0
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Order) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblorder.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if f, has := orderFieldToValueFunc[arg]; has {
			value, isZero := f(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *Order) AssignKeys() (dialect.Field, any) {
	return tblorder.PrimaryKey, p.Id
}

func (p *Order) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
