// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblmember"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

var (
	memberPool = pool.New[*Member](func() any {
		_obj := &Member{}
		return _obj
	})
)

func NewMember() *Member {
	_obj := memberPool.Get()
	return _obj
}

// MarshalJSON
func (p *Member) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(11 * 50)
	write.WriteRaw("id", types.Marshal(p.Id))
	write.WriteRaw("user_id", types.Marshal(p.UserId))
	write.WriteRaw("tenant_id", types.Marshal(p.TenantId))
	write.WriteRaw("role_id", types.Marshal(p.RoleId))
	write.WriteRaw("permissions", types.Marshal(p.Permissions))
	write.WriteRaw("status", types.Marshal(p.Status))
	write.WriteRaw("create_id", types.Marshal(p.CreateId))
	write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	write.WriteRaw("del_flag", types.Marshal(p.DelFlag))
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *Member) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "user_id":
			p.UserId = types.BigInt(value.Uint())
		case "tenant_id":
			p.TenantId = types.BigInt(value.Uint())
		case "role_id":
			p.RoleId = types.BigInt(value.Uint())
		case "permissions":
			p.Permissions = types.String(value.Str)
		case "status":
			p.Status = types.Int8(value.Int())
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		case "del_flag":
			p.DelFlag = types.Int8(value.Int())
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *Member) Free() {
	if p == nil {
		return
	}

	memberPool.Put(p)
}

// Reset
func (p *Member) Reset() {
	p.Id = 0
	p.UserId = 0
	p.TenantId = 0
	p.RoleId = 0
	p.Permissions = ""
	p.Status = 0
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}
	p.DelFlag = 0

}

func (p *Member) TableName() string {
	return "member"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var memberFieldToPtrFunc = map[string]func(*Member) any{
	tblmember.Id.Name:          func(p *Member) any { return &p.Id },
	tblmember.UserId.Name:      func(p *Member) any { return &p.UserId },
	tblmember.TenantId.Name:    func(p *Member) any { return &p.TenantId },
	tblmember.RoleId.Name:      func(p *Member) any { return &p.RoleId },
	tblmember.Permissions.Name: func(p *Member) any { return &p.Permissions },
	tblmember.Status.Name:      func(p *Member) any { return &p.Status },
	tblmember.CreateId.Name:    func(p *Member) any { return &p.CreateId },
	tblmember.CreateTime.Name:  func(p *Member) any { return &p.CreateTime },
	tblmember.UpdateId.Name:    func(p *Member) any { return &p.UpdateId },
	tblmember.UpdateTime.Name:  func(p *Member) any { return &p.UpdateTime },
	tblmember.DelFlag.Name:     func(p *Member) any { return &p.DelFlag },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *Member) fieldPtr(args ...dialect.Field) []func(*Member) any {
	if len(args) == 0 {
		args = tblmember.ReadableFields
	}
	fs := make([]func(*Member) any, 0, len(args))
	for _, col := range args {
		if f, ok := memberFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *Member) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *Member) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if f, ok := memberFieldToPtrFunc[col]; ok {
			_vals = append(_vals, f(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *Member) Slice(rows *sql.Rows, args ...dialect.Field) ([]*Member, bool, error) {
	defer rows.Close()
	members := make([]*Member, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewMember()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		members = append(members, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return members, len(members) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Member) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblmember.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var memberFieldToValueFunc = map[dialect.Field]func(*Member) (any, bool){
	tblmember.Id: func(p *Member) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblmember.UserId: func(p *Member) (any, bool) {
		return p.UserId, p.UserId == 0
	},
	tblmember.TenantId: func(p *Member) (any, bool) {
		return p.TenantId, p.TenantId == 0
	},
	tblmember.RoleId: func(p *Member) (any, bool) {
		return p.RoleId, p.RoleId == 0
	},
	tblmember.Permissions: func(p *Member) (any, bool) {
		return p.Permissions, p.Permissions == ""
	},
	tblmember.Status: func(p *Member) (any, bool) {
		return p.Status, p.Status == 0
	},
	tblmember.CreateId: func(p *Member) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblmember.CreateTime: func(p *Member) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblmember.UpdateId: func(p *Member) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblmember.UpdateTime: func(p *Member) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
	tblmember.DelFlag: func(p *Member) (any, bool) {
		return p.DelFlag, p.DelFlag == 0
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Member) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblmember.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if f, has := memberFieldToValueFunc[arg]; has {
			value, isZero := f(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *Member) AssignKeys() (dialect.Field, any) {
	return tblmember.PrimaryKey, p.Id
}

func (p *Member) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
