// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblbill"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

var (
	billPool = pool.New[*Bill](func() any {
		_obj := &Bill{}
		return _obj
	})
)

func NewBill() *Bill {
	_obj := billPool.Get()
	return _obj
}

// MarshalJSON
func (p *Bill) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(13 * 50)
	if p.BillNo != "" {
		write.WriteRaw("bill_no", types.Marshal(p.BillNo))
	}
	if p.BillPeriod != "" {
		write.WriteRaw("bill_period", types.Marshal(p.BillPeriod))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if !p.DueDate.IsZero() {
		write.WriteRaw("due_date", types.Marshal(p.DueDate))
	}
	if p.ElderId != 0 {
		write.WriteRaw("elder_id", types.Marshal(p.ElderId))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.PaidAmount != 0 {
		write.WriteRaw("paid_amount", types.Marshal(p.PaidAmount))
	}
	if p.TenantId != 0 {
		write.WriteRaw("tenant_id", types.Marshal(p.TenantId))
	}
	if p.TotalAmount != 0 {
		write.WriteRaw("total_amount", types.Marshal(p.TotalAmount))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	if p.Status != 0 {
		write.WriteRaw("status", types.Marshal(p.Status))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *Bill) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "bill_no":
			p.BillNo = types.String(value.Str)
		case "bill_period":
			p.BillPeriod = types.String(value.Str)
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "due_date":
			p.DueDate = types.Time{Time: value.Time()}
		case "elder_id":
			p.ElderId = types.BigInt(value.Uint())
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "paid_amount":
			e = types.Unmarshal(value, &p.PaidAmount)
		case "tenant_id":
			p.TenantId = types.BigInt(value.Uint())
		case "total_amount":
			e = types.Unmarshal(value, &p.TotalAmount)
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		case "status":
			p.Status = types.Uint8(value.Uint())
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *Bill) Free() {
	if p == nil {
		return
	}

	billPool.Put(p)
}

// Reset
func (p *Bill) Reset() {
	p.BillNo = ""
	p.BillPeriod = ""
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.DueDate = types.Time{}
	p.ElderId = 0
	p.Id = 0
	p.PaidAmount = 0
	p.TenantId = 0
	p.TotalAmount = 0
	p.UpdateId = 0
	p.UpdateTime = types.Time{}
	p.Status = 0

}

func (p *Bill) TableName() string {
	return "bill"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var billFieldToPtrFunc = map[string]func(*Bill) any{
	tblbill.BillNo.Name:      func(p *Bill) any { return &p.BillNo },
	tblbill.BillPeriod.Name:  func(p *Bill) any { return &p.BillPeriod },
	tblbill.CreateId.Name:    func(p *Bill) any { return &p.CreateId },
	tblbill.CreateTime.Name:  func(p *Bill) any { return &p.CreateTime },
	tblbill.DueDate.Name:     func(p *Bill) any { return &p.DueDate },
	tblbill.ElderId.Name:     func(p *Bill) any { return &p.ElderId },
	tblbill.Id.Name:          func(p *Bill) any { return &p.Id },
	tblbill.PaidAmount.Name:  func(p *Bill) any { return &p.PaidAmount },
	tblbill.TenantId.Name:    func(p *Bill) any { return &p.TenantId },
	tblbill.TotalAmount.Name: func(p *Bill) any { return &p.TotalAmount },
	tblbill.UpdateId.Name:    func(p *Bill) any { return &p.UpdateId },
	tblbill.UpdateTime.Name:  func(p *Bill) any { return &p.UpdateTime },
	tblbill.Status.Name:      func(p *Bill) any { return &p.Status },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *Bill) fieldPtr(args ...dialect.Field) []func(*Bill) any {
	if len(args) == 0 {
		args = tblbill.ReadableFields
	}
	fs := make([]func(*Bill) any, 0, len(args))
	for _, col := range args {
		if f, ok := billFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *Bill) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *Bill) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if f, ok := billFieldToPtrFunc[col]; ok {
			_vals = append(_vals, f(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *Bill) Slice(rows *sql.Rows, args ...dialect.Field) ([]*Bill, bool, error) {
	defer rows.Close()
	bills := make([]*Bill, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewBill()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		bills = append(bills, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return bills, len(bills) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Bill) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblbill.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var billFieldToValueFunc = map[dialect.Field]func(*Bill) (any, bool){
	tblbill.BillNo: func(p *Bill) (any, bool) {
		return p.BillNo, p.BillNo == ""
	},
	tblbill.BillPeriod: func(p *Bill) (any, bool) {
		return p.BillPeriod, p.BillPeriod == ""
	},
	tblbill.CreateId: func(p *Bill) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblbill.CreateTime: func(p *Bill) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblbill.DueDate: func(p *Bill) (any, bool) {
		return p.DueDate, p.DueDate.IsZero()
	},
	tblbill.ElderId: func(p *Bill) (any, bool) {
		return p.ElderId, p.ElderId == 0
	},
	tblbill.Id: func(p *Bill) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblbill.PaidAmount: func(p *Bill) (any, bool) {
		return p.PaidAmount, p.PaidAmount == 0
	},
	tblbill.TenantId: func(p *Bill) (any, bool) {
		return p.TenantId, p.TenantId == 0
	},
	tblbill.TotalAmount: func(p *Bill) (any, bool) {
		return p.TotalAmount, p.TotalAmount == 0
	},
	tblbill.UpdateId: func(p *Bill) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblbill.UpdateTime: func(p *Bill) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
	tblbill.Status: func(p *Bill) (any, bool) {
		return p.Status, p.Status == 0
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Bill) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblbill.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if f, has := billFieldToValueFunc[arg]; has {
			value, isZero := f(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *Bill) AssignKeys() (dialect.Field, any) {
	return tblbill.PrimaryKey, p.Id
}

func (p *Bill) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
