// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tblsource

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

const TableName = "source"

var (
	Name       = dialect.Field{Name: "name", Json: "name", Table: "source", Type: "types.String", IsRelation: false}
	CreateId   = dialect.Field{Name: "create_id", Json: "create_id", Table: "source", Type: "types.BigInt", IsRelation: false}
	CreateTime = dialect.Field{Name: "create_time", Json: "create_time", Table: "source", Type: "types.Time", IsRelation: false}
	Id         = dialect.Field{Name: "id", Json: "id", Table: "source", Type: "types.BigInt", IsRelation: false}
	TenantId   = dialect.Field{Name: "tenant_id", Json: "tenant_id", Table: "source", Type: "types.BigInt", IsRelation: false}
	UpdateId   = dialect.Field{Name: "update_id", Json: "update_id", Table: "source", Type: "types.BigInt", IsRelation: false}
	UpdateTime = dialect.Field{Name: "update_time", Json: "update_time", Table: "source", Type: "types.Time", IsRelation: false}
	State      = dialect.Field{Name: "state", Json: "state", Table: "source", Type: "types.Int8", IsRelation: false}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		Name,
		CreateId,
		CreateTime,
		Id,
		TenantId,
		UpdateId,
		UpdateTime,
		State,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		Name,
		CreateId,
		CreateTime,
		Id,
		TenantId,
		UpdateId,
		UpdateTime,
		State,
	}
)
