// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tblroom

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

var (
	Name       = dialect.Field{Name: "name", Json: "name", Table: "room", Type: "types.String", IsRelation: false}
	DelFlag    = dialect.Field{Name: "del_flag", Json: "del_flag", Table: "room", Type: "types.String", IsRelation: false}
	Id         = dialect.Field{Name: "id", Json: "id", Table: "room", Type: "types.BigInt", IsRelation: false}
	TypeId     = dialect.Field{Name: "type_id", Json: "type_id", Table: "room", Type: "types.BigInt", IsRelation: false}
	FloorId    = dialect.Field{Name: "floor_id", Json: "floor_id", Table: "room", Type: "types.BigInt", IsRelation: false}
	CreateId   = dialect.Field{Name: "create_id", Json: "create_id", Table: "room", Type: "types.BigInt", IsRelation: false}
	CreateTime = dialect.Field{Name: "create_time", Json: "create_time", Table: "room", Type: "types.Time", IsRelation: false}
	UpdateId   = dialect.Field{Name: "update_id", Json: "update_id", Table: "room", Type: "types.BigInt", IsRelation: false}
	UpdateTime = dialect.Field{Name: "update_time", Json: "update_time", Table: "room", Type: "types.Time", IsRelation: false}
	BedNum     = dialect.Field{Name: "bed_num", Json: "bed_num", Table: "room", Type: "types.Int32", IsRelation: false}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		Name,
		DelFlag,
		Id,
		TypeId,
		FloorId,
		CreateId,
		CreateTime,
		UpdateId,
		UpdateTime,
		BedNum,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		Name,
		DelFlag,
		Id,
		TypeId,
		FloorId,
		CreateId,
		CreateTime,
		UpdateId,
		UpdateTime,
		BedNum,
	}
)
