// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tblassessment

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

const TableName = "assessment"

var (
	ResultLevel    = dialect.Field{Name: "result_level", Json: "result_level", Table: "assessment", Type: "types.String", IsRelation: false}
	ScaleData      = dialect.Field{Name: "scale_data", Json: "scale_data", Table: "assessment", Type: "types.String", IsRelation: false}
	AssessmentDate = dialect.Field{Name: "assessment_date", Json: "assessment_date", Table: "assessment", Type: "types.Time", IsRelation: false}
	CreatedAt      = dialect.Field{Name: "created_at", Json: "created_at", Table: "assessment", Type: "types.Time", IsRelation: false}
	DeletedAt      = dialect.Field{Name: "deleted_at", Json: "deleted_at", Table: "assessment", Type: "types.Time", IsRelation: false}
	ElderId        = dialect.Field{Name: "elder_id", Json: "elder_id", Table: "assessment", Type: "types.BigInt", IsRelation: false}
	EvaluatorId    = dialect.Field{Name: "evaluator_id", Json: "evaluator_id", Table: "assessment", Type: "types.BigInt", IsRelation: false}
	Id             = dialect.Field{Name: "id", Json: "id", Table: "assessment", Type: "types.BigInt", IsRelation: false}
	TenantId       = dialect.Field{Name: "tenant_id", Json: "tenant_id", Table: "assessment", Type: "types.BigInt", IsRelation: false}
	UpdatedAt      = dialect.Field{Name: "updated_at", Json: "updated_at", Table: "assessment", Type: "types.Time", IsRelation: false}
	AssessmentType = dialect.Field{Name: "assessment_type", Json: "assessment_type", Table: "assessment", Type: "types.Int8", IsRelation: false}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		ResultLevel,
		ScaleData,
		AssessmentDate,
		DeletedAt,
		ElderId,
		EvaluatorId,
		Id,
		TenantId,
		AssessmentType,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		ResultLevel,
		ScaleData,
		AssessmentDate,
		CreatedAt,
		DeletedAt,
		ElderId,
		EvaluatorId,
		Id,
		TenantId,
		UpdatedAt,
		AssessmentType,
	}
)
