// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tblroommaterial

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

const TableName = "room_material"

var (
	CreateId       = dialect.Field{Name: "create_id", Json: "create_id", Table: "room_material", Type: "types.BigInt", IsRelation: false}
	CreateTime     = dialect.Field{Name: "create_time", Json: "create_time", Table: "room_material", Type: "types.Time", IsRelation: false}
	Id             = dialect.Field{Name: "id", Json: "id", Table: "room_material", Type: "types.BigInt", IsRelation: false}
	MaterialTypeId = dialect.Field{Name: "material_type_id", Json: "material_type_id", Table: "room_material", Type: "types.BigInt", IsRelation: false}
	RoomId         = dialect.Field{Name: "room_id", Json: "room_id", Table: "room_material", Type: "types.BigInt", IsRelation: false}
	TenantId       = dialect.Field{Name: "tenant_id", Json: "tenant_id", Table: "room_material", Type: "types.BigInt", IsRelation: false}
	UpdateId       = dialect.Field{Name: "update_id", Json: "update_id", Table: "room_material", Type: "types.BigInt", IsRelation: false}
	UpdateTime     = dialect.Field{Name: "update_time", Json: "update_time", Table: "room_material", Type: "types.Time", IsRelation: false}
	State          = dialect.Field{Name: "state", Json: "state", Table: "room_material", Type: "types.Int8", IsRelation: false}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		CreateId,
		CreateTime,
		Id,
		MaterialTypeId,
		RoomId,
		TenantId,
		UpdateId,
		UpdateTime,
		State,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		CreateId,
		CreateTime,
		Id,
		MaterialTypeId,
		RoomId,
		TenantId,
		UpdateId,
		UpdateTime,
		State,
	}
)
