// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tblactiveparticipant

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

const TableName = "active_participant"

var (
	Id         = dialect.Field{Name: "id", Json: "id", Table: "active_participant", Type: "types.BigInt", IsRelation: false}
	ActiveId   = dialect.Field{Name: "active_id", Json: "active_id", Table: "active_participant", Type: "types.BigInt", IsRelation: false}
	ElderId    = dialect.Field{Name: "elder_id", Json: "elder_id", Table: "active_participant", Type: "types.BigInt", IsRelation: false}
	CreateId   = dialect.Field{Name: "create_id", Json: "create_id", Table: "active_participant", Type: "types.BigInt", IsRelation: false}
	CreateTime = dialect.Field{Name: "create_time", Json: "create_time", Table: "active_participant", Type: "types.Time", IsRelation: false}
	UpdateId   = dialect.Field{Name: "update_id", Json: "update_id", Table: "active_participant", Type: "types.BigInt", IsRelation: false}
	UpdateTime = dialect.Field{Name: "update_time", Json: "update_time", Table: "active_participant", Type: "types.Time", IsRelation: false}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		Id,
		ActiveId,
		ElderId,
		CreateId,
		CreateTime,
		UpdateId,
		UpdateTime,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		Id,
		ActiveId,
		ElderId,
		CreateId,
		CreateTime,
		UpdateId,
		UpdateTime,
	}
)
