// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tblemergencycontact

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

var (
	Name        = dialect.Field{Name: "name", Json: "name", Table: "emergency_contact", Type: "types.String", IsRelation: false}
	Phone       = dialect.Field{Name: "phone", Json: "phone", Table: "emergency_contact", Type: "types.String", IsRelation: false}
	Email       = dialect.Field{Name: "email", Json: "email", Table: "emergency_contact", Type: "types.String", IsRelation: false}
	Relation    = dialect.Field{Name: "relation", Json: "relation", Table: "emergency_contact", Type: "types.String", IsRelation: false}
	Id          = dialect.Field{Name: "id", Json: "id", Table: "emergency_contact", Type: "types.BigInt", IsRelation: false}
	ElderId     = dialect.Field{Name: "elder_id", Json: "elder_id", Table: "emergency_contact", Type: "types.BigInt", IsRelation: false}
	CreateId    = dialect.Field{Name: "create_id", Json: "create_id", Table: "emergency_contact", Type: "types.BigInt", IsRelation: false}
	CreateTime  = dialect.Field{Name: "create_time", Json: "create_time", Table: "emergency_contact", Type: "types.Time", IsRelation: false}
	UpdateId    = dialect.Field{Name: "update_id", Json: "update_id", Table: "emergency_contact", Type: "types.BigInt", IsRelation: false}
	UpdateTime  = dialect.Field{Name: "update_time", Json: "update_time", Table: "emergency_contact", Type: "types.Time", IsRelation: false}
	ReceiveFlag = dialect.Field{Name: "receive_flag", Json: "receive_flag", Table: "emergency_contact", Type: "types.Int8", IsRelation: false}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		Name,
		Phone,
		Email,
		Relation,
		Id,
		ElderId,
		CreateId,
		CreateTime,
		UpdateId,
		UpdateTime,
		ReceiveFlag,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		Name,
		Phone,
		Email,
		Relation,
		Id,
		ElderId,
		CreateId,
		CreateTime,
		UpdateId,
		UpdateTime,
		ReceiveFlag,
	}
)
