// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblcontract"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

var (
	contractPool = pool.New[*Contract](func() any {
		_obj := &Contract{}
		return _obj
	})
)

func NewContract() *Contract {
	_obj := contractPool.Get()
	return _obj
}

// MarshalJSON
func (p *Contract) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(10 * 50)
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.ElderId != 0 {
		write.WriteRaw("elder_id", types.Marshal(p.ElderId))
	}
	if p.StaffId != 0 {
		write.WriteRaw("staff_id", types.Marshal(p.StaffId))
	}
	if !p.SignDate.IsZero() {
		write.WriteRaw("sign_date", types.Marshal(p.SignDate))
	}
	if !p.StartDate.IsZero() {
		write.WriteRaw("start_date", types.Marshal(p.StartDate))
	}
	if !p.EndDate.IsZero() {
		write.WriteRaw("end_date", types.Marshal(p.EndDate))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *Contract) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "elder_id":
			p.ElderId = types.BigInt(value.Uint())
		case "staff_id":
			p.StaffId = types.BigInt(value.Uint())
		case "sign_date":
			p.SignDate = types.Time{Time: value.Time()}
		case "start_date":
			p.StartDate = types.Time{Time: value.Time()}
		case "end_date":
			p.EndDate = types.Time{Time: value.Time()}
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *Contract) Free() {
	if p == nil {
		return
	}

	contractPool.Put(p)
}

// Reset
func (p *Contract) Reset() {
	p.Id = 0
	p.ElderId = 0
	p.StaffId = 0
	p.SignDate = types.Time{}
	p.StartDate = types.Time{}
	p.EndDate = types.Time{}
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}

}

func (p *Contract) TableName() string {
	return "contract"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var contractFieldToPtrFunc = map[string]func(*Contract) any{
	tblcontract.Id.Name:         func(p *Contract) any { return &p.Id },
	tblcontract.ElderId.Name:    func(p *Contract) any { return &p.ElderId },
	tblcontract.StaffId.Name:    func(p *Contract) any { return &p.StaffId },
	tblcontract.SignDate.Name:   func(p *Contract) any { return &p.SignDate },
	tblcontract.StartDate.Name:  func(p *Contract) any { return &p.StartDate },
	tblcontract.EndDate.Name:    func(p *Contract) any { return &p.EndDate },
	tblcontract.CreateId.Name:   func(p *Contract) any { return &p.CreateId },
	tblcontract.CreateTime.Name: func(p *Contract) any { return &p.CreateTime },
	tblcontract.UpdateId.Name:   func(p *Contract) any { return &p.UpdateId },
	tblcontract.UpdateTime.Name: func(p *Contract) any { return &p.UpdateTime },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *Contract) fieldPtr(args ...dialect.Field) []func(*Contract) any {
	if len(args) == 0 {
		args = tblcontract.ReadableFields
	}
	fs := make([]func(*Contract) any, 0, len(args))
	for _, col := range args {
		if f, ok := contractFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *Contract) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *Contract) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if f, ok := contractFieldToPtrFunc[col]; ok {
			_vals = append(_vals, f(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *Contract) Slice(rows *sql.Rows, args ...dialect.Field) ([]*Contract, bool, error) {
	defer rows.Close()
	contracts := make([]*Contract, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewContract()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		contracts = append(contracts, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return contracts, len(contracts) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Contract) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblcontract.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var contractFieldToValueFunc = map[dialect.Field]func(*Contract) (any, bool){
	tblcontract.Id: func(p *Contract) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblcontract.ElderId: func(p *Contract) (any, bool) {
		return p.ElderId, p.ElderId == 0
	},
	tblcontract.StaffId: func(p *Contract) (any, bool) {
		return p.StaffId, p.StaffId == 0
	},
	tblcontract.SignDate: func(p *Contract) (any, bool) {
		return p.SignDate, p.SignDate.IsZero()
	},
	tblcontract.StartDate: func(p *Contract) (any, bool) {
		return p.StartDate, p.StartDate.IsZero()
	},
	tblcontract.EndDate: func(p *Contract) (any, bool) {
		return p.EndDate, p.EndDate.IsZero()
	},
	tblcontract.CreateId: func(p *Contract) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblcontract.CreateTime: func(p *Contract) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblcontract.UpdateId: func(p *Contract) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblcontract.UpdateTime: func(p *Contract) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Contract) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblcontract.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if f, has := contractFieldToValueFunc[arg]; has {
			value, isZero := f(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *Contract) AssignKeys() (dialect.Field, any) {
	return tblcontract.PrimaryKey, p.Id
}

func (p *Contract) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
