// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblrolecopy1"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

const RoleCopy1TableName = "role_copy1"

var (
	rolecopy1Pool = pool.New[*RoleCopy1](func() any {
		_obj := &RoleCopy1{}
		return _obj
	})
)

func NewRoleCopy1() *RoleCopy1 {
	_obj := rolecopy1Pool.Get()
	return _obj
}

// MarshalJSON
func (p *RoleCopy1) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(6 * 50)
	if p.Name != "" {
		write.WriteRaw("name", types.Marshal(p.Name))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *RoleCopy1) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "name":
			p.Name = types.String(value.Str)
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *RoleCopy1) Free() {
	if p == nil {
		return
	}

	rolecopy1Pool.Put(p)
}

// Reset
func (p *RoleCopy1) Reset() {
	p.Name = ""
	p.Id = 0
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}

}

func (p *RoleCopy1) TableName() string {
	return RoleCopy1TableName
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var rolecopy1FieldToPtrFunc = map[dialect.Field]func(*RoleCopy1) any{
	tblrolecopy1.Name:       func(p *RoleCopy1) any { return &p.Name },
	tblrolecopy1.Id:         func(p *RoleCopy1) any { return &p.Id },
	tblrolecopy1.CreateId:   func(p *RoleCopy1) any { return &p.CreateId },
	tblrolecopy1.CreateTime: func(p *RoleCopy1) any { return &p.CreateTime },
	tblrolecopy1.UpdateId:   func(p *RoleCopy1) any { return &p.UpdateId },
	tblrolecopy1.UpdateTime: func(p *RoleCopy1) any { return &p.UpdateTime },
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *RoleCopy1) AssignPtr(args ...dialect.Field) []any {
	if len(args) == 0 {
		args = tblrolecopy1.ReadableFields
	}

	_vals := make([]any, 0, len(args))
	for _, col := range args {
		if ptrFunc, ok := rolecopy1FieldToPtrFunc[col]; ok {
			_vals = append(_vals, ptrFunc(p))
		}
	}

	return _vals
}

func (p *RoleCopy1) Scan(rows *sql.Rows, args ...dialect.Field) ([]*RoleCopy1, bool, error) {
	defer rows.Close()
	role_copy1s := make([]*RoleCopy1, 0)

	if len(args) == 0 {
		args = tblrolecopy1.ReadableFields
	}

	for rows.Next() {
		_p := NewRoleCopy1()
		_vals := _p.AssignPtr(args...)
		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		role_copy1s = append(role_copy1s, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return role_copy1s, len(role_copy1s) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *RoleCopy1) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblrolecopy1.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var rolecopy1FieldToValueFunc = map[dialect.Field]func(*RoleCopy1) (any, bool){
	tblrolecopy1.Name: func(p *RoleCopy1) (any, bool) {
		return p.Name, p.Name == ""
	},
	tblrolecopy1.Id: func(p *RoleCopy1) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblrolecopy1.CreateId: func(p *RoleCopy1) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblrolecopy1.CreateTime: func(p *RoleCopy1) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblrolecopy1.UpdateId: func(p *RoleCopy1) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblrolecopy1.UpdateTime: func(p *RoleCopy1) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *RoleCopy1) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblrolecopy1.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if valueFunc, exists := rolecopy1FieldToValueFunc[arg]; exists {
			value, isZero := valueFunc(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

//
func (p *RoleCopy1) AssignKeys() (dialect.Field, any) {
	return tblrolecopy1.PrimaryKey, p.Id
}

//
func (p *RoleCopy1) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
