// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblbuilding"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

const BuildingTableName = "building"

var (
	buildingPool = pool.New[*Building](func() any {
		_obj := &Building{}
		return _obj
	})
)

func NewBuilding() *Building {
	_obj := buildingPool.Get()
	return _obj
}

// MarshalJSON
func (p *Building) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(8 * 50)
	if p.Name != "" {
		write.WriteRaw("name", types.Marshal(p.Name))
	}
	if p.DelFlag != "" {
		write.WriteRaw("del_flag", types.Marshal(p.DelFlag))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	if p.FloorNum != 0 {
		write.WriteRaw("floor_num", types.Marshal(p.FloorNum))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *Building) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "name":
			p.Name = types.String(value.Str)
		case "del_flag":
			p.DelFlag = types.String(value.Str)
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		case "floor_num":
			p.FloorNum = types.Int32(value.Int())
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *Building) Free() {
	if p == nil {
		return
	}

	buildingPool.Put(p)
}

// Reset
func (p *Building) Reset() {
	p.Name = ""
	p.DelFlag = ""
	p.Id = 0
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}
	p.FloorNum = 0

}

func (p *Building) TableName() string {
	return BuildingTableName
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var buildingFieldToPtrFunc = map[string]func(*Building) any{
	tblbuilding.Name.Name:       func(p *Building) any { return &p.Name },
	tblbuilding.DelFlag.Name:    func(p *Building) any { return &p.DelFlag },
	tblbuilding.Id.Name:         func(p *Building) any { return &p.Id },
	tblbuilding.CreateId.Name:   func(p *Building) any { return &p.CreateId },
	tblbuilding.CreateTime.Name: func(p *Building) any { return &p.CreateTime },
	tblbuilding.UpdateId.Name:   func(p *Building) any { return &p.UpdateId },
	tblbuilding.UpdateTime.Name: func(p *Building) any { return &p.UpdateTime },
	tblbuilding.FloorNum.Name:   func(p *Building) any { return &p.FloorNum },
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *Building) AssignPtr(args ...dialect.Field) []any {
	if len(args) == 0 {
		args = tblbuilding.ReadableFields
	}

	_vals := make([]any, 0, len(args))
	for _, col := range args {
		if ptrFunc, ok := buildingFieldToPtrFunc[col.Name]; ok {
			_vals = append(_vals, ptrFunc(p))
		}
	}

	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *Building) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if ptrFunc, ok := buildingFieldToPtrFunc[col]; ok {
			_vals = append(_vals, ptrFunc(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *Building) Scan(rows *sql.Rows, args ...dialect.Field) ([]*Building, bool, error) {
	defer rows.Close()
	buildings := make([]*Building, 0)

	if len(args) == 0 {
		args = tblbuilding.ReadableFields
	}

	for rows.Next() {
		_p := NewBuilding()
		_vals := _p.AssignPtr(args...)
		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		buildings = append(buildings, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return buildings, len(buildings) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Building) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblbuilding.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var buildingFieldToValueFunc = map[dialect.Field]func(*Building) (any, bool){
	tblbuilding.Name: func(p *Building) (any, bool) {
		return p.Name, p.Name == ""
	},
	tblbuilding.DelFlag: func(p *Building) (any, bool) {
		return p.DelFlag, p.DelFlag == ""
	},
	tblbuilding.Id: func(p *Building) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblbuilding.CreateId: func(p *Building) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblbuilding.CreateTime: func(p *Building) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblbuilding.UpdateId: func(p *Building) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblbuilding.UpdateTime: func(p *Building) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
	tblbuilding.FloorNum: func(p *Building) (any, bool) {
		return p.FloorNum, p.FloorNum == 0
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Building) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblbuilding.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if valueFunc, exists := buildingFieldToValueFunc[arg]; exists {
			value, isZero := valueFunc(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *Building) AssignKeys() (dialect.Field, any) {
	return tblbuilding.PrimaryKey, p.Id
}

func (p *Building) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
