// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblsource"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

const SourceTableName = "source"

var (
	sourcePool = pool.New[*Source](func() any {
		_obj := &Source{}
		return _obj
	})
)

func NewSource() *Source {
	_obj := sourcePool.Get()
	return _obj
}

// MarshalJSON
func (p *Source) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(7 * 50)
	if p.Name != "" {
		write.WriteRaw("name", types.Marshal(p.Name))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	if p.DelFlag != 0 {
		write.WriteRaw("del_flag", types.Marshal(p.DelFlag))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *Source) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "name":
			p.Name = types.String(value.Str)
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		case "del_flag":
			p.DelFlag = types.Int8(value.Int())
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *Source) Free() {
	if p == nil {
		return
	}

	sourcePool.Put(p)
}

// Reset
func (p *Source) Reset() {
	p.Name = ""
	p.Id = 0
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}
	p.DelFlag = 0

}

func (p *Source) TableName() string {
	return SourceTableName
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var sourceFieldToPtrFunc = map[string]func(*Source) any{
	tblsource.Name.Name:       func(p *Source) any { return &p.Name },
	tblsource.Id.Name:         func(p *Source) any { return &p.Id },
	tblsource.CreateId.Name:   func(p *Source) any { return &p.CreateId },
	tblsource.CreateTime.Name: func(p *Source) any { return &p.CreateTime },
	tblsource.UpdateId.Name:   func(p *Source) any { return &p.UpdateId },
	tblsource.UpdateTime.Name: func(p *Source) any { return &p.UpdateTime },
	tblsource.DelFlag.Name:    func(p *Source) any { return &p.DelFlag },
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *Source) AssignPtr(args ...dialect.Field) []any {
	if len(args) == 0 {
		args = tblsource.ReadableFields
	}

	_vals := make([]any, 0, len(args))
	for _, col := range args {
		if ptrFunc, ok := sourceFieldToPtrFunc[col.Name]; ok {
			_vals = append(_vals, ptrFunc(p))
		}
	}

	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *Source) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if ptrFunc, ok := sourceFieldToPtrFunc[col]; ok {
			_vals = append(_vals, ptrFunc(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *Source) Scan(rows *sql.Rows, args ...dialect.Field) ([]*Source, bool, error) {
	defer rows.Close()
	sources := make([]*Source, 0)

	if len(args) == 0 {
		args = tblsource.ReadableFields
	}

	for rows.Next() {
		_p := NewSource()
		_vals := _p.AssignPtr(args...)
		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		sources = append(sources, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return sources, len(sources) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Source) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblsource.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var sourceFieldToValueFunc = map[dialect.Field]func(*Source) (any, bool){
	tblsource.Name: func(p *Source) (any, bool) {
		return p.Name, p.Name == ""
	},
	tblsource.Id: func(p *Source) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblsource.CreateId: func(p *Source) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblsource.CreateTime: func(p *Source) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblsource.UpdateId: func(p *Source) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblsource.UpdateTime: func(p *Source) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
	tblsource.DelFlag: func(p *Source) (any, bool) {
		return p.DelFlag, p.DelFlag == 0
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Source) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblsource.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if valueFunc, exists := sourceFieldToValueFunc[arg]; exists {
			value, isZero := valueFunc(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *Source) AssignKeys() (dialect.Field, any) {
	return tblsource.PrimaryKey, p.Id
}

func (p *Source) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
