// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblauth"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

const AuthTableName = "auth"

var (
	authPool = pool.New[*Auth](func() any {
		_obj := &Auth{}
		return _obj
	})
)

func NewAuth() *Auth {
	_obj := authPool.Get()
	return _obj
}

// MarshalJSON
func (p *Auth) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(13 * 50)
	if p.Title != "" {
		write.WriteRaw("title", types.Marshal(p.Title))
	}
	if p.Name != "" {
		write.WriteRaw("name", types.Marshal(p.Name))
	}
	if p.Path != "" {
		write.WriteRaw("path", types.Marshal(p.Path))
	}
	if p.Icon != "" {
		write.WriteRaw("icon", types.Marshal(p.Icon))
	}
	if p.Url != "" {
		write.WriteRaw("url", types.Marshal(p.Url))
	}
	if p.Type != "" {
		write.WriteRaw("type", types.Marshal(p.Type))
	}
	if p.Method != "" {
		write.WriteRaw("method", types.Marshal(p.Method))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.ParentId != 0 {
		write.WriteRaw("parent_id", types.Marshal(p.ParentId))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *Auth) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "title":
			p.Title = types.String(value.Str)
		case "name":
			p.Name = types.String(value.Str)
		case "path":
			p.Path = types.String(value.Str)
		case "icon":
			p.Icon = types.String(value.Str)
		case "url":
			p.Url = types.String(value.Str)
		case "type":
			p.Type = types.String(value.Str)
		case "method":
			p.Method = types.String(value.Str)
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "parent_id":
			p.ParentId = types.BigInt(value.Uint())
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *Auth) Free() {
	if p == nil {
		return
	}

	authPool.Put(p)
}

// Reset
func (p *Auth) Reset() {
	p.Title = ""
	p.Name = ""
	p.Path = ""
	p.Icon = ""
	p.Url = ""
	p.Type = ""
	p.Method = ""
	p.Id = 0
	p.ParentId = 0
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}

}

func (p *Auth) TableName() string {
	return AuthTableName
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var authFieldToPtrFunc = map[dialect.Field]func(*Auth) any{
	tblauth.Title:      func(p *Auth) any { return &p.Title },
	tblauth.Name:       func(p *Auth) any { return &p.Name },
	tblauth.Path:       func(p *Auth) any { return &p.Path },
	tblauth.Icon:       func(p *Auth) any { return &p.Icon },
	tblauth.Url:        func(p *Auth) any { return &p.Url },
	tblauth.Type:       func(p *Auth) any { return &p.Type },
	tblauth.Method:     func(p *Auth) any { return &p.Method },
	tblauth.Id:         func(p *Auth) any { return &p.Id },
	tblauth.ParentId:   func(p *Auth) any { return &p.ParentId },
	tblauth.CreateId:   func(p *Auth) any { return &p.CreateId },
	tblauth.CreateTime: func(p *Auth) any { return &p.CreateTime },
	tblauth.UpdateId:   func(p *Auth) any { return &p.UpdateId },
	tblauth.UpdateTime: func(p *Auth) any { return &p.UpdateTime },
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *Auth) AssignPtr(args ...dialect.Field) []any {
	if len(args) == 0 {
		args = tblauth.ReadableFields
	}

	_vals := make([]any, 0, len(args))
	for _, col := range args {
		if ptrFunc, ok := authFieldToPtrFunc[col]; ok {
			_vals = append(_vals, ptrFunc(p))
		}
	}

	return _vals
}

func (p *Auth) Scan(rows *sql.Rows, args ...dialect.Field) ([]*Auth, bool, error) {
	defer rows.Close()
	auths := make([]*Auth, 0)

	if len(args) == 0 {
		args = tblauth.ReadableFields
	}

	for rows.Next() {
		_p := NewAuth()
		_vals := _p.AssignPtr(args...)
		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		auths = append(auths, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return auths, len(auths) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Auth) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblauth.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var authFieldToValueFunc = map[dialect.Field]func(*Auth) (any, bool){
	tblauth.Title: func(p *Auth) (any, bool) {
		return p.Title, p.Title == ""
	},
	tblauth.Name: func(p *Auth) (any, bool) {
		return p.Name, p.Name == ""
	},
	tblauth.Path: func(p *Auth) (any, bool) {
		return p.Path, p.Path == ""
	},
	tblauth.Icon: func(p *Auth) (any, bool) {
		return p.Icon, p.Icon == ""
	},
	tblauth.Url: func(p *Auth) (any, bool) {
		return p.Url, p.Url == ""
	},
	tblauth.Type: func(p *Auth) (any, bool) {
		return p.Type, p.Type == ""
	},
	tblauth.Method: func(p *Auth) (any, bool) {
		return p.Method, p.Method == ""
	},
	tblauth.Id: func(p *Auth) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblauth.ParentId: func(p *Auth) (any, bool) {
		return p.ParentId, p.ParentId == 0
	},
	tblauth.CreateId: func(p *Auth) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblauth.CreateTime: func(p *Auth) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblauth.UpdateId: func(p *Auth) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblauth.UpdateTime: func(p *Auth) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Auth) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblauth.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if valueFunc, exists := authFieldToValueFunc[arg]; exists {
			value, isZero := valueFunc(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

//
func (p *Auth) AssignKeys() (dialect.Field, any) {
	return tblauth.PrimaryKey, p.Id
}

//
func (p *Auth) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
