// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblmaterialtype"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

var (
	materialtypePool = pool.New[*MaterialType](func() any {
		_obj := &MaterialType{}
		return _obj
	})
)

func NewMaterialType() *MaterialType {
	_obj := materialtypePool.Get()
	return _obj
}

// MarshalJSON
func (p *MaterialType) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(7 * 50)
	if p.Name != "" {
		write.WriteRaw("name", types.Marshal(p.Name))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	if p.DelFlag != 0 {
		write.WriteRaw("del_flag", types.Marshal(p.DelFlag))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *MaterialType) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "name":
			p.Name = types.String(value.Str)
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		case "del_flag":
			p.DelFlag = types.Int8(value.Int())
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *MaterialType) Free() {
	if p == nil {
		return
	}

	materialtypePool.Put(p)
}

// Reset
func (p *MaterialType) Reset() {
	p.Name = ""
	p.Id = 0
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}
	p.DelFlag = 0

}

func (p *MaterialType) TableName() string {
	return "material_type"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var materialtypeFieldToPtrFunc = map[string]func(*MaterialType) any{
	tblmaterialtype.Name.Name:       func(p *MaterialType) any { return &p.Name },
	tblmaterialtype.Id.Name:         func(p *MaterialType) any { return &p.Id },
	tblmaterialtype.CreateId.Name:   func(p *MaterialType) any { return &p.CreateId },
	tblmaterialtype.CreateTime.Name: func(p *MaterialType) any { return &p.CreateTime },
	tblmaterialtype.UpdateId.Name:   func(p *MaterialType) any { return &p.UpdateId },
	tblmaterialtype.UpdateTime.Name: func(p *MaterialType) any { return &p.UpdateTime },
	tblmaterialtype.DelFlag.Name:    func(p *MaterialType) any { return &p.DelFlag },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *MaterialType) fieldPtr(args ...dialect.Field) []func(*MaterialType) any {
	if len(args) == 0 {
		args = tblmaterialtype.ReadableFields
	}
	fs := make([]func(*MaterialType) any, 0, len(args))
	for _, col := range args {
		if f, ok := materialtypeFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *MaterialType) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *MaterialType) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if f, ok := materialtypeFieldToPtrFunc[col]; ok {
			_vals = append(_vals, f(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *MaterialType) Slice(rows *sql.Rows, args ...dialect.Field) ([]*MaterialType, bool, error) {
	defer rows.Close()
	material_types := make([]*MaterialType, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewMaterialType()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		material_types = append(material_types, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return material_types, len(material_types) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *MaterialType) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblmaterialtype.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var materialtypeFieldToValueFunc = map[dialect.Field]func(*MaterialType) (any, bool){
	tblmaterialtype.Name: func(p *MaterialType) (any, bool) {
		return p.Name, p.Name == ""
	},
	tblmaterialtype.Id: func(p *MaterialType) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblmaterialtype.CreateId: func(p *MaterialType) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblmaterialtype.CreateTime: func(p *MaterialType) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblmaterialtype.UpdateId: func(p *MaterialType) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblmaterialtype.UpdateTime: func(p *MaterialType) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
	tblmaterialtype.DelFlag: func(p *MaterialType) (any, bool) {
		return p.DelFlag, p.DelFlag == 0
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *MaterialType) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblmaterialtype.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if f, has := materialtypeFieldToValueFunc[arg]; has {
			value, isZero := f(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *MaterialType) AssignKeys() (dialect.Field, any) {
	return tblmaterialtype.PrimaryKey, p.Id
}

func (p *MaterialType) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
