// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblnursegroupmember"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

const NurseGroupMemberTableName = "nurse_group_member"

var (
	nursegroupmemberPool = pool.New[*NurseGroupMember](func() any {
		_obj := &NurseGroupMember{}
		return _obj
	})
)

func NewNurseGroupMember() *NurseGroupMember {
	_obj := nursegroupmemberPool.Get()
	return _obj
}

// MarshalJSON
func (p *NurseGroupMember) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(7 * 50)
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.GroupId != 0 {
		write.WriteRaw("group_id", types.Marshal(p.GroupId))
	}
	if p.StaffId != 0 {
		write.WriteRaw("staff_id", types.Marshal(p.StaffId))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *NurseGroupMember) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "group_id":
			p.GroupId = types.BigInt(value.Uint())
		case "staff_id":
			p.StaffId = types.BigInt(value.Uint())
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *NurseGroupMember) Free() {
	if p == nil {
		return
	}

	nursegroupmemberPool.Put(p)
}

// Reset
func (p *NurseGroupMember) Reset() {
	p.Id = 0
	p.GroupId = 0
	p.StaffId = 0
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}

}

func (p *NurseGroupMember) TableName() string {
	return NurseGroupMemberTableName
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var nursegroupmemberFieldToPtrFunc = map[string]func(*NurseGroupMember) any{
	tblnursegroupmember.Id.Name:         func(p *NurseGroupMember) any { return &p.Id },
	tblnursegroupmember.GroupId.Name:    func(p *NurseGroupMember) any { return &p.GroupId },
	tblnursegroupmember.StaffId.Name:    func(p *NurseGroupMember) any { return &p.StaffId },
	tblnursegroupmember.CreateId.Name:   func(p *NurseGroupMember) any { return &p.CreateId },
	tblnursegroupmember.CreateTime.Name: func(p *NurseGroupMember) any { return &p.CreateTime },
	tblnursegroupmember.UpdateId.Name:   func(p *NurseGroupMember) any { return &p.UpdateId },
	tblnursegroupmember.UpdateTime.Name: func(p *NurseGroupMember) any { return &p.UpdateTime },
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *NurseGroupMember) AssignPtr(args ...dialect.Field) []any {
	if len(args) == 0 {
		args = tblnursegroupmember.ReadableFields
	}

	_vals := make([]any, 0, len(args))
	for _, col := range args {
		if ptrFunc, ok := nursegroupmemberFieldToPtrFunc[col.Name]; ok {
			_vals = append(_vals, ptrFunc(p))
		}
	}

	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *NurseGroupMember) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if ptrFunc, ok := nursegroupmemberFieldToPtrFunc[col]; ok {
			_vals = append(_vals, ptrFunc(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *NurseGroupMember) Scan(rows *sql.Rows, args ...dialect.Field) ([]*NurseGroupMember, bool, error) {
	defer rows.Close()
	nurse_group_members := make([]*NurseGroupMember, 0)

	if len(args) == 0 {
		args = tblnursegroupmember.ReadableFields
	}

	for rows.Next() {
		_p := NewNurseGroupMember()
		_vals := _p.AssignPtr(args...)
		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		nurse_group_members = append(nurse_group_members, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return nurse_group_members, len(nurse_group_members) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *NurseGroupMember) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblnursegroupmember.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var nursegroupmemberFieldToValueFunc = map[dialect.Field]func(*NurseGroupMember) (any, bool){
	tblnursegroupmember.Id: func(p *NurseGroupMember) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblnursegroupmember.GroupId: func(p *NurseGroupMember) (any, bool) {
		return p.GroupId, p.GroupId == 0
	},
	tblnursegroupmember.StaffId: func(p *NurseGroupMember) (any, bool) {
		return p.StaffId, p.StaffId == 0
	},
	tblnursegroupmember.CreateId: func(p *NurseGroupMember) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblnursegroupmember.CreateTime: func(p *NurseGroupMember) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblnursegroupmember.UpdateId: func(p *NurseGroupMember) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblnursegroupmember.UpdateTime: func(p *NurseGroupMember) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *NurseGroupMember) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblnursegroupmember.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if valueFunc, exists := nursegroupmemberFieldToValueFunc[arg]; exists {
			value, isZero := valueFunc(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *NurseGroupMember) AssignKeys() (dialect.Field, any) {
	return tblnursegroupmember.PrimaryKey, p.Id
}

func (p *NurseGroupMember) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
