// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblmedicinerecord"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

// const MedicineRecordTableName = "medicine_record"

var (
	medicinerecordPool = pool.New[*MedicineRecord](func() any {
		_obj := &MedicineRecord{}
		return _obj
	})
)

func NewMedicineRecord() *MedicineRecord {
	_obj := medicinerecordPool.Get()
	return _obj
}

// MarshalJSON
func (p *MedicineRecord) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(9 * 50)
	if p.MedicineTime != "" {
		write.WriteRaw("medicine_time", types.Marshal(p.MedicineTime))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.ElderId != 0 {
		write.WriteRaw("elder_id", types.Marshal(p.ElderId))
	}
	if p.DepositInfoId != 0 {
		write.WriteRaw("deposit_info_id", types.Marshal(p.DepositInfoId))
	}
	if !p.MedicineDate.IsZero() {
		write.WriteRaw("medicine_date", types.Marshal(p.MedicineDate))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *MedicineRecord) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "medicine_time":
			p.MedicineTime = types.String(value.Str)
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "elder_id":
			p.ElderId = types.BigInt(value.Uint())
		case "deposit_info_id":
			p.DepositInfoId = types.BigInt(value.Uint())
		case "medicine_date":
			p.MedicineDate = types.Time{Time: value.Time()}
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *MedicineRecord) Free() {
	if p == nil {
		return
	}

	medicinerecordPool.Put(p)
}

// Reset
func (p *MedicineRecord) Reset() {
	p.MedicineTime = ""
	p.Id = 0
	p.ElderId = 0
	p.DepositInfoId = 0
	p.MedicineDate = types.Time{}
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}

}

func (p *MedicineRecord) TableName() string {
	return "medicine_record"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var medicinerecordFieldToPtrFunc = map[string]func(*MedicineRecord) any{
	tblmedicinerecord.MedicineTime.Name:  func(p *MedicineRecord) any { return &p.MedicineTime },
	tblmedicinerecord.Id.Name:            func(p *MedicineRecord) any { return &p.Id },
	tblmedicinerecord.ElderId.Name:       func(p *MedicineRecord) any { return &p.ElderId },
	tblmedicinerecord.DepositInfoId.Name: func(p *MedicineRecord) any { return &p.DepositInfoId },
	tblmedicinerecord.MedicineDate.Name:  func(p *MedicineRecord) any { return &p.MedicineDate },
	tblmedicinerecord.CreateId.Name:      func(p *MedicineRecord) any { return &p.CreateId },
	tblmedicinerecord.CreateTime.Name:    func(p *MedicineRecord) any { return &p.CreateTime },
	tblmedicinerecord.UpdateId.Name:      func(p *MedicineRecord) any { return &p.UpdateId },
	tblmedicinerecord.UpdateTime.Name:    func(p *MedicineRecord) any { return &p.UpdateTime },
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *MedicineRecord) AssignPtr(args ...dialect.Field) []any {
	if len(args) == 0 {
		args = tblmedicinerecord.ReadableFields
	}

	_vals := make([]any, 0, len(args))
	for _, col := range args {
		if ptrFunc, ok := medicinerecordFieldToPtrFunc[col.Name]; ok {
			_vals = append(_vals, ptrFunc(p))
		}
	}

	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *MedicineRecord) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if ptrFunc, ok := medicinerecordFieldToPtrFunc[col]; ok {
			_vals = append(_vals, ptrFunc(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *MedicineRecord) Scan(rows *sql.Rows, args ...dialect.Field) ([]*MedicineRecord, bool, error) {
	defer rows.Close()
	medicine_records := make([]*MedicineRecord, 0)

	if len(args) == 0 {
		args = tblmedicinerecord.ReadableFields
	}

	for rows.Next() {
		_p := NewMedicineRecord()
		_vals := _p.AssignPtr(args...)
		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		medicine_records = append(medicine_records, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return medicine_records, len(medicine_records) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *MedicineRecord) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblmedicinerecord.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var medicinerecordFieldToValueFunc = map[dialect.Field]func(*MedicineRecord) (any, bool){
	tblmedicinerecord.MedicineTime: func(p *MedicineRecord) (any, bool) {
		return p.MedicineTime, p.MedicineTime == ""
	},
	tblmedicinerecord.Id: func(p *MedicineRecord) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblmedicinerecord.ElderId: func(p *MedicineRecord) (any, bool) {
		return p.ElderId, p.ElderId == 0
	},
	tblmedicinerecord.DepositInfoId: func(p *MedicineRecord) (any, bool) {
		return p.DepositInfoId, p.DepositInfoId == 0
	},
	tblmedicinerecord.MedicineDate: func(p *MedicineRecord) (any, bool) {
		return p.MedicineDate, p.MedicineDate.IsZero()
	},
	tblmedicinerecord.CreateId: func(p *MedicineRecord) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblmedicinerecord.CreateTime: func(p *MedicineRecord) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblmedicinerecord.UpdateId: func(p *MedicineRecord) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblmedicinerecord.UpdateTime: func(p *MedicineRecord) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *MedicineRecord) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblmedicinerecord.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if valueFunc, exists := medicinerecordFieldToValueFunc[arg]; exists {
			value, isZero := valueFunc(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *MedicineRecord) AssignKeys() (dialect.Field, any) {
	return tblmedicinerecord.PrimaryKey, p.Id
}

func (p *MedicineRecord) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
