// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblbaseattachment"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

const BaseAttachmentTableName = "base_attachment"

var (
	baseattachmentPool = pool.New[*BaseAttachment](func() any {
		_obj := &BaseAttachment{}
		return _obj
	})
)

func NewBaseAttachment() *BaseAttachment {
	_obj := baseattachmentPool.Get()
	return _obj
}

// MarshalJSON
func (p *BaseAttachment) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(12 * 50)
	if p.Name != "" {
		write.WriteRaw("name", types.Marshal(p.Name))
	}
	if p.RealName != "" {
		write.WriteRaw("real_name", types.Marshal(p.RealName))
	}
	if p.Path != "" {
		write.WriteRaw("path", types.Marshal(p.Path))
	}
	if p.Url != "" {
		write.WriteRaw("url", types.Marshal(p.Url))
	}
	if p.Suff != "" {
		write.WriteRaw("suff", types.Marshal(p.Suff))
	}
	if p.DelFlag != "" {
		write.WriteRaw("del_flag", types.Marshal(p.DelFlag))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.Size != 0 {
		write.WriteRaw("size", types.Marshal(p.Size))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *BaseAttachment) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "name":
			p.Name = types.String(value.Str)
		case "real_name":
			p.RealName = types.String(value.Str)
		case "path":
			p.Path = types.String(value.Str)
		case "url":
			p.Url = types.String(value.Str)
		case "suff":
			p.Suff = types.String(value.Str)
		case "del_flag":
			p.DelFlag = types.String(value.Str)
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "size":
			p.Size = types.BigInt(value.Uint())
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *BaseAttachment) Free() {
	if p == nil {
		return
	}

	baseattachmentPool.Put(p)
}

// Reset
func (p *BaseAttachment) Reset() {
	p.Name = ""
	p.RealName = ""
	p.Path = ""
	p.Url = ""
	p.Suff = ""
	p.DelFlag = ""
	p.Id = 0
	p.Size = 0
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}

}

func (p *BaseAttachment) TableName() string {
	return BaseAttachmentTableName
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var baseattachmentFieldToPtrFunc = map[string]func(*BaseAttachment) any{
	tblbaseattachment.Name.Name:       func(p *BaseAttachment) any { return &p.Name },
	tblbaseattachment.RealName.Name:   func(p *BaseAttachment) any { return &p.RealName },
	tblbaseattachment.Path.Name:       func(p *BaseAttachment) any { return &p.Path },
	tblbaseattachment.Url.Name:        func(p *BaseAttachment) any { return &p.Url },
	tblbaseattachment.Suff.Name:       func(p *BaseAttachment) any { return &p.Suff },
	tblbaseattachment.DelFlag.Name:    func(p *BaseAttachment) any { return &p.DelFlag },
	tblbaseattachment.Id.Name:         func(p *BaseAttachment) any { return &p.Id },
	tblbaseattachment.Size.Name:       func(p *BaseAttachment) any { return &p.Size },
	tblbaseattachment.CreateId.Name:   func(p *BaseAttachment) any { return &p.CreateId },
	tblbaseattachment.CreateTime.Name: func(p *BaseAttachment) any { return &p.CreateTime },
	tblbaseattachment.UpdateId.Name:   func(p *BaseAttachment) any { return &p.UpdateId },
	tblbaseattachment.UpdateTime.Name: func(p *BaseAttachment) any { return &p.UpdateTime },
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *BaseAttachment) AssignPtr(args ...dialect.Field) []any {
	if len(args) == 0 {
		args = tblbaseattachment.ReadableFields
	}

	_vals := make([]any, 0, len(args))
	for _, col := range args {
		if ptrFunc, ok := baseattachmentFieldToPtrFunc[col.Name]; ok {
			_vals = append(_vals, ptrFunc(p))
		}
	}

	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *BaseAttachment) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if ptrFunc, ok := baseattachmentFieldToPtrFunc[col]; ok {
			_vals = append(_vals, ptrFunc(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *BaseAttachment) Scan(rows *sql.Rows, args ...dialect.Field) ([]*BaseAttachment, bool, error) {
	defer rows.Close()
	base_attachments := make([]*BaseAttachment, 0)

	if len(args) == 0 {
		args = tblbaseattachment.ReadableFields
	}

	for rows.Next() {
		_p := NewBaseAttachment()
		_vals := _p.AssignPtr(args...)
		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		base_attachments = append(base_attachments, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return base_attachments, len(base_attachments) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *BaseAttachment) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblbaseattachment.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var baseattachmentFieldToValueFunc = map[dialect.Field]func(*BaseAttachment) (any, bool){
	tblbaseattachment.Name: func(p *BaseAttachment) (any, bool) {
		return p.Name, p.Name == ""
	},
	tblbaseattachment.RealName: func(p *BaseAttachment) (any, bool) {
		return p.RealName, p.RealName == ""
	},
	tblbaseattachment.Path: func(p *BaseAttachment) (any, bool) {
		return p.Path, p.Path == ""
	},
	tblbaseattachment.Url: func(p *BaseAttachment) (any, bool) {
		return p.Url, p.Url == ""
	},
	tblbaseattachment.Suff: func(p *BaseAttachment) (any, bool) {
		return p.Suff, p.Suff == ""
	},
	tblbaseattachment.DelFlag: func(p *BaseAttachment) (any, bool) {
		return p.DelFlag, p.DelFlag == ""
	},
	tblbaseattachment.Id: func(p *BaseAttachment) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblbaseattachment.Size: func(p *BaseAttachment) (any, bool) {
		return p.Size, p.Size == 0
	},
	tblbaseattachment.CreateId: func(p *BaseAttachment) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblbaseattachment.CreateTime: func(p *BaseAttachment) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblbaseattachment.UpdateId: func(p *BaseAttachment) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblbaseattachment.UpdateTime: func(p *BaseAttachment) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *BaseAttachment) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblbaseattachment.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if valueFunc, exists := baseattachmentFieldToValueFunc[arg]; exists {
			value, isZero := valueFunc(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *BaseAttachment) AssignKeys() (dialect.Field, any) {
	return tblbaseattachment.PrimaryKey, p.Id
}

func (p *BaseAttachment) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
