// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblsetdishes"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

const SetDishesTableName = "set_dishes"

var (
	setdishesPool = pool.New[*SetDishes](func() any {
		_obj := &SetDishes{}
		return _obj
	})
)

func NewSetDishes() *SetDishes {
	_obj := setdishesPool.Get()
	return _obj
}

// MarshalJSON
func (p *SetDishes) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(7 * 50)
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.SetId != 0 {
		write.WriteRaw("set_id", types.Marshal(p.SetId))
	}
	if p.DishesId != 0 {
		write.WriteRaw("dishes_id", types.Marshal(p.DishesId))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *SetDishes) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "set_id":
			p.SetId = types.BigInt(value.Uint())
		case "dishes_id":
			p.DishesId = types.BigInt(value.Uint())
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *SetDishes) Free() {
	if p == nil {
		return
	}

	setdishesPool.Put(p)
}

// Reset
func (p *SetDishes) Reset() {
	p.Id = 0
	p.SetId = 0
	p.DishesId = 0
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}

}

func (p *SetDishes) TableName() string {
	return SetDishesTableName
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var setdishesFieldToPtrFunc = map[dialect.Field]func(*SetDishes) any{
	tblsetdishes.Id:         func(p *SetDishes) any { return &p.Id },
	tblsetdishes.SetId:      func(p *SetDishes) any { return &p.SetId },
	tblsetdishes.DishesId:   func(p *SetDishes) any { return &p.DishesId },
	tblsetdishes.CreateId:   func(p *SetDishes) any { return &p.CreateId },
	tblsetdishes.CreateTime: func(p *SetDishes) any { return &p.CreateTime },
	tblsetdishes.UpdateId:   func(p *SetDishes) any { return &p.UpdateId },
	tblsetdishes.UpdateTime: func(p *SetDishes) any { return &p.UpdateTime },
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *SetDishes) AssignPtr(args ...dialect.Field) []any {
	if len(args) == 0 {
		args = tblsetdishes.ReadableFields
	}

	_vals := make([]any, 0, len(args))
	for _, col := range args {
		if ptrFunc, ok := setdishesFieldToPtrFunc[col]; ok {
			_vals = append(_vals, ptrFunc(p))
		}
	}

	return _vals
}

func (p *SetDishes) Scan(rows *sql.Rows, args ...dialect.Field) ([]*SetDishes, bool, error) {
	defer rows.Close()
	set_dishess := make([]*SetDishes, 0)

	if len(args) == 0 {
		args = tblsetdishes.ReadableFields
	}

	for rows.Next() {
		_p := NewSetDishes()
		_vals := _p.AssignPtr(args...)
		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		set_dishess = append(set_dishess, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return set_dishess, len(set_dishess) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *SetDishes) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblsetdishes.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var setdishesFieldToValueFunc = map[dialect.Field]func(*SetDishes) (any, bool){
	tblsetdishes.Id: func(p *SetDishes) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblsetdishes.SetId: func(p *SetDishes) (any, bool) {
		return p.SetId, p.SetId == 0
	},
	tblsetdishes.DishesId: func(p *SetDishes) (any, bool) {
		return p.DishesId, p.DishesId == 0
	},
	tblsetdishes.CreateId: func(p *SetDishes) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblsetdishes.CreateTime: func(p *SetDishes) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblsetdishes.UpdateId: func(p *SetDishes) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblsetdishes.UpdateTime: func(p *SetDishes) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *SetDishes) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblsetdishes.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if valueFunc, exists := setdishesFieldToValueFunc[arg]; exists {
			value, isZero := valueFunc(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

//
func (p *SetDishes) AssignKeys() (dialect.Field, any) {
	return tblsetdishes.PrimaryKey, p.Id
}

//
func (p *SetDishes) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
