// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblelderlabel"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

const ElderLabelTableName = "elder_label"

var (
	elderlabelPool = pool.New[*ElderLabel](func() any {
		_obj := &ElderLabel{}
		return _obj
	})
)

func NewElderLabel() *ElderLabel {
	_obj := elderlabelPool.Get()
	return _obj
}

// MarshalJSON
func (p *ElderLabel) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(7 * 50)
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.ElderId != 0 {
		write.WriteRaw("elder_id", types.Marshal(p.ElderId))
	}
	if p.LabelId != 0 {
		write.WriteRaw("label_id", types.Marshal(p.LabelId))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *ElderLabel) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "elder_id":
			p.ElderId = types.BigInt(value.Uint())
		case "label_id":
			p.LabelId = types.BigInt(value.Uint())
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *ElderLabel) Free() {
	if p == nil {
		return
	}

	elderlabelPool.Put(p)
}

// Reset
func (p *ElderLabel) Reset() {
	p.Id = 0
	p.ElderId = 0
	p.LabelId = 0
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}

}

func (p *ElderLabel) TableName() string {
	return ElderLabelTableName
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var elderlabelFieldToPtrFunc = map[dialect.Field]func(*ElderLabel) any{
	tblelderlabel.Id:         func(p *ElderLabel) any { return &p.Id },
	tblelderlabel.ElderId:    func(p *ElderLabel) any { return &p.ElderId },
	tblelderlabel.LabelId:    func(p *ElderLabel) any { return &p.LabelId },
	tblelderlabel.CreateId:   func(p *ElderLabel) any { return &p.CreateId },
	tblelderlabel.CreateTime: func(p *ElderLabel) any { return &p.CreateTime },
	tblelderlabel.UpdateId:   func(p *ElderLabel) any { return &p.UpdateId },
	tblelderlabel.UpdateTime: func(p *ElderLabel) any { return &p.UpdateTime },
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *ElderLabel) AssignPtr(args ...dialect.Field) []any {
	if len(args) == 0 {
		args = tblelderlabel.ReadableFields
	}

	_vals := make([]any, 0, len(args))
	for _, col := range args {
		if ptrFunc, ok := elderlabelFieldToPtrFunc[col]; ok {
			_vals = append(_vals, ptrFunc(p))
		}
	}

	return _vals
}

func (p *ElderLabel) Scan(rows *sql.Rows, args ...dialect.Field) ([]*ElderLabel, bool, error) {
	defer rows.Close()
	elder_labels := make([]*ElderLabel, 0)

	if len(args) == 0 {
		args = tblelderlabel.ReadableFields
	}

	for rows.Next() {
		_p := NewElderLabel()
		_vals := _p.AssignPtr(args...)
		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		elder_labels = append(elder_labels, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return elder_labels, len(elder_labels) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *ElderLabel) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblelderlabel.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var elderlabelFieldToValueFunc = map[dialect.Field]func(*ElderLabel) (any, bool){
	tblelderlabel.Id: func(p *ElderLabel) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblelderlabel.ElderId: func(p *ElderLabel) (any, bool) {
		return p.ElderId, p.ElderId == 0
	},
	tblelderlabel.LabelId: func(p *ElderLabel) (any, bool) {
		return p.LabelId, p.LabelId == 0
	},
	tblelderlabel.CreateId: func(p *ElderLabel) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblelderlabel.CreateTime: func(p *ElderLabel) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblelderlabel.UpdateId: func(p *ElderLabel) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblelderlabel.UpdateTime: func(p *ElderLabel) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *ElderLabel) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblelderlabel.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if valueFunc, exists := elderlabelFieldToValueFunc[arg]; exists {
			value, isZero := valueFunc(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

//
func (p *ElderLabel) AssignKeys() (dialect.Field, any) {
	return tblelderlabel.PrimaryKey, p.Id
}

//
func (p *ElderLabel) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
