// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tbldrugdeposit"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

const DrugDepositTableName = "drug_deposit"

var (
	drugdepositPool = pool.New[*DrugDeposit](func() any {
		_obj := &DrugDeposit{}
		return _obj
	})
)

func NewDrugDeposit() *DrugDeposit {
	_obj := drugdepositPool.Get()
	return _obj
}

// MarshalJSON
func (p *DrugDeposit) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(9 * 50)
	if p.Mode != "" {
		write.WriteRaw("mode", types.Marshal(p.Mode))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.ElderId != 0 {
		write.WriteRaw("elder_id", types.Marshal(p.ElderId))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	if p.DepositFlag != 0 {
		write.WriteRaw("deposit_flag", types.Marshal(p.DepositFlag))
	}
	if p.DelFlag != 0 {
		write.WriteRaw("del_flag", types.Marshal(p.DelFlag))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *DrugDeposit) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "mode":
			p.Mode = types.String(value.Str)
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "elder_id":
			p.ElderId = types.BigInt(value.Uint())
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		case "deposit_flag":
			p.DepositFlag = types.Int8(value.Int())
		case "del_flag":
			p.DelFlag = types.Int8(value.Int())
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *DrugDeposit) Free() {
	if p == nil {
		return
	}

	drugdepositPool.Put(p)
}

// Reset
func (p *DrugDeposit) Reset() {
	p.Mode = ""
	p.Id = 0
	p.ElderId = 0
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}
	p.DepositFlag = 0
	p.DelFlag = 0

}

func (p *DrugDeposit) TableName() string {
	return DrugDepositTableName
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var drugdepositFieldToPtrFunc = map[string]func(*DrugDeposit) any{
	tbldrugdeposit.Mode.Name:        func(p *DrugDeposit) any { return &p.Mode },
	tbldrugdeposit.Id.Name:          func(p *DrugDeposit) any { return &p.Id },
	tbldrugdeposit.ElderId.Name:     func(p *DrugDeposit) any { return &p.ElderId },
	tbldrugdeposit.CreateId.Name:    func(p *DrugDeposit) any { return &p.CreateId },
	tbldrugdeposit.CreateTime.Name:  func(p *DrugDeposit) any { return &p.CreateTime },
	tbldrugdeposit.UpdateId.Name:    func(p *DrugDeposit) any { return &p.UpdateId },
	tbldrugdeposit.UpdateTime.Name:  func(p *DrugDeposit) any { return &p.UpdateTime },
	tbldrugdeposit.DepositFlag.Name: func(p *DrugDeposit) any { return &p.DepositFlag },
	tbldrugdeposit.DelFlag.Name:     func(p *DrugDeposit) any { return &p.DelFlag },
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *DrugDeposit) AssignPtr(args ...dialect.Field) []any {
	if len(args) == 0 {
		args = tbldrugdeposit.ReadableFields
	}

	_vals := make([]any, 0, len(args))
	for _, col := range args {
		if ptrFunc, ok := drugdepositFieldToPtrFunc[col.Name]; ok {
			_vals = append(_vals, ptrFunc(p))
		}
	}

	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *DrugDeposit) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if ptrFunc, ok := drugdepositFieldToPtrFunc[col]; ok {
			_vals = append(_vals, ptrFunc(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *DrugDeposit) Scan(rows *sql.Rows, args ...dialect.Field) ([]*DrugDeposit, bool, error) {
	defer rows.Close()
	drug_deposits := make([]*DrugDeposit, 0)

	if len(args) == 0 {
		args = tbldrugdeposit.ReadableFields
	}

	for rows.Next() {
		_p := NewDrugDeposit()
		_vals := _p.AssignPtr(args...)
		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		drug_deposits = append(drug_deposits, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return drug_deposits, len(drug_deposits) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *DrugDeposit) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tbldrugdeposit.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var drugdepositFieldToValueFunc = map[dialect.Field]func(*DrugDeposit) (any, bool){
	tbldrugdeposit.Mode: func(p *DrugDeposit) (any, bool) {
		return p.Mode, p.Mode == ""
	},
	tbldrugdeposit.Id: func(p *DrugDeposit) (any, bool) {
		return p.Id, p.Id == 0
	},
	tbldrugdeposit.ElderId: func(p *DrugDeposit) (any, bool) {
		return p.ElderId, p.ElderId == 0
	},
	tbldrugdeposit.CreateId: func(p *DrugDeposit) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tbldrugdeposit.CreateTime: func(p *DrugDeposit) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tbldrugdeposit.UpdateId: func(p *DrugDeposit) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tbldrugdeposit.UpdateTime: func(p *DrugDeposit) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
	tbldrugdeposit.DepositFlag: func(p *DrugDeposit) (any, bool) {
		return p.DepositFlag, p.DepositFlag == 0
	},
	tbldrugdeposit.DelFlag: func(p *DrugDeposit) (any, bool) {
		return p.DelFlag, p.DelFlag == 0
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *DrugDeposit) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tbldrugdeposit.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if valueFunc, exists := drugdepositFieldToValueFunc[arg]; exists {
			value, isZero := valueFunc(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *DrugDeposit) AssignKeys() (dialect.Field, any) {
	return tbldrugdeposit.PrimaryKey, p.Id
}

func (p *DrugDeposit) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
