// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblorderdishes"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

const OrderDishesTableName = "order_dishes"

var (
	orderdishesPool = pool.New[*OrderDishes](func() any {
		_obj := &OrderDishes{}
		return _obj
	})
)

func NewOrderDishes() *OrderDishes {
	_obj := orderdishesPool.Get()
	return _obj
}

// MarshalJSON
func (p *OrderDishes) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(12 * 50)
	if p.DishesName != "" {
		write.WriteRaw("dishes_name", types.Marshal(p.DishesName))
	}
	if p.SetFlag != "" {
		write.WriteRaw("set_flag", types.Marshal(p.SetFlag))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.OrderId != 0 {
		write.WriteRaw("order_id", types.Marshal(p.OrderId))
	}
	if p.DishesPrice != 0.0 {
		write.WriteRaw("dishes_price", types.Marshal(p.DishesPrice))
	}
	if p.TotalAmount != 0.0 {
		write.WriteRaw("total_amount", types.Marshal(p.TotalAmount))
	}
	if p.ReallyAmount != 0.0 {
		write.WriteRaw("really_amount", types.Marshal(p.ReallyAmount))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	if p.OrderNum != 0 {
		write.WriteRaw("order_num", types.Marshal(p.OrderNum))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *OrderDishes) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "dishes_name":
			p.DishesName = types.String(value.Str)
		case "set_flag":
			p.SetFlag = types.String(value.Str)
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "order_id":
			p.OrderId = types.BigInt(value.Uint())
		case "dishes_price":
			p.DishesPrice = types.Float64(value.Float())
		case "total_amount":
			p.TotalAmount = types.Float64(value.Float())
		case "really_amount":
			p.ReallyAmount = types.Float64(value.Float())
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		case "order_num":
			p.OrderNum = types.Int32(value.Int())
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *OrderDishes) Free() {
	if p == nil {
		return
	}

	orderdishesPool.Put(p)
}

// Reset
func (p *OrderDishes) Reset() {
	p.DishesName = ""
	p.SetFlag = ""
	p.Id = 0
	p.OrderId = 0
	p.DishesPrice = 0
	p.TotalAmount = 0
	p.ReallyAmount = 0
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}
	p.OrderNum = 0

}

func (p *OrderDishes) TableName() string {
	return OrderDishesTableName
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var orderdishesFieldToPtrFunc = map[string]func(*OrderDishes) any{
	tblorderdishes.DishesName.Name:   func(p *OrderDishes) any { return &p.DishesName },
	tblorderdishes.SetFlag.Name:      func(p *OrderDishes) any { return &p.SetFlag },
	tblorderdishes.Id.Name:           func(p *OrderDishes) any { return &p.Id },
	tblorderdishes.OrderId.Name:      func(p *OrderDishes) any { return &p.OrderId },
	tblorderdishes.DishesPrice.Name:  func(p *OrderDishes) any { return &p.DishesPrice },
	tblorderdishes.TotalAmount.Name:  func(p *OrderDishes) any { return &p.TotalAmount },
	tblorderdishes.ReallyAmount.Name: func(p *OrderDishes) any { return &p.ReallyAmount },
	tblorderdishes.CreateId.Name:     func(p *OrderDishes) any { return &p.CreateId },
	tblorderdishes.CreateTime.Name:   func(p *OrderDishes) any { return &p.CreateTime },
	tblorderdishes.UpdateId.Name:     func(p *OrderDishes) any { return &p.UpdateId },
	tblorderdishes.UpdateTime.Name:   func(p *OrderDishes) any { return &p.UpdateTime },
	tblorderdishes.OrderNum.Name:     func(p *OrderDishes) any { return &p.OrderNum },
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *OrderDishes) AssignPtr(args ...dialect.Field) []any {
	if len(args) == 0 {
		args = tblorderdishes.ReadableFields
	}

	_vals := make([]any, 0, len(args))
	for _, col := range args {
		if ptrFunc, ok := orderdishesFieldToPtrFunc[col.Name]; ok {
			_vals = append(_vals, ptrFunc(p))
		}
	}

	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *OrderDishes) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if ptrFunc, ok := orderdishesFieldToPtrFunc[col]; ok {
			_vals = append(_vals, ptrFunc(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *OrderDishes) Scan(rows *sql.Rows, args ...dialect.Field) ([]*OrderDishes, bool, error) {
	defer rows.Close()
	order_dishess := make([]*OrderDishes, 0)

	if len(args) == 0 {
		args = tblorderdishes.ReadableFields
	}

	for rows.Next() {
		_p := NewOrderDishes()
		_vals := _p.AssignPtr(args...)
		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		order_dishess = append(order_dishess, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return order_dishess, len(order_dishess) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *OrderDishes) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblorderdishes.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var orderdishesFieldToValueFunc = map[dialect.Field]func(*OrderDishes) (any, bool){
	tblorderdishes.DishesName: func(p *OrderDishes) (any, bool) {
		return p.DishesName, p.DishesName == ""
	},
	tblorderdishes.SetFlag: func(p *OrderDishes) (any, bool) {
		return p.SetFlag, p.SetFlag == ""
	},
	tblorderdishes.Id: func(p *OrderDishes) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblorderdishes.OrderId: func(p *OrderDishes) (any, bool) {
		return p.OrderId, p.OrderId == 0
	},
	tblorderdishes.DishesPrice: func(p *OrderDishes) (any, bool) {
		return p.DishesPrice, p.DishesPrice == 0.0
	},
	tblorderdishes.TotalAmount: func(p *OrderDishes) (any, bool) {
		return p.TotalAmount, p.TotalAmount == 0.0
	},
	tblorderdishes.ReallyAmount: func(p *OrderDishes) (any, bool) {
		return p.ReallyAmount, p.ReallyAmount == 0.0
	},
	tblorderdishes.CreateId: func(p *OrderDishes) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblorderdishes.CreateTime: func(p *OrderDishes) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblorderdishes.UpdateId: func(p *OrderDishes) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblorderdishes.UpdateTime: func(p *OrderDishes) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
	tblorderdishes.OrderNum: func(p *OrderDishes) (any, bool) {
		return p.OrderNum, p.OrderNum == 0
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *OrderDishes) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblorderdishes.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if valueFunc, exists := orderdishesFieldToValueFunc[arg]; exists {
			value, isZero := valueFunc(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *OrderDishes) AssignKeys() (dialect.Field, any) {
	return tblorderdishes.PrimaryKey, p.Id
}

func (p *OrderDishes) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
