// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tbloutboundrecord"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

const OutboundRecordTableName = "outbound_record"

var (
	outboundrecordPool = pool.New[*OutboundRecord](func() any {
		_obj := &OutboundRecord{}
		return _obj
	})
)

func NewOutboundRecord() *OutboundRecord {
	_obj := outboundrecordPool.Get()
	return _obj
}

// MarshalJSON
func (p *OutboundRecord) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(13 * 50)
	if p.RecipientType != "" {
		write.WriteRaw("recipient_type", types.Marshal(p.RecipientType))
	}
	if p.MaterialUse != "" {
		write.WriteRaw("material_use", types.Marshal(p.MaterialUse))
	}
	if p.OutboundFlag != "" {
		write.WriteRaw("outbound_flag", types.Marshal(p.OutboundFlag))
	}
	if p.DelFlag != "" {
		write.WriteRaw("del_flag", types.Marshal(p.DelFlag))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.WarehouseId != 0 {
		write.WriteRaw("warehouse_id", types.Marshal(p.WarehouseId))
	}
	if p.StaffId != 0 {
		write.WriteRaw("staff_id", types.Marshal(p.StaffId))
	}
	if p.RecipientId != 0 {
		write.WriteRaw("recipient_id", types.Marshal(p.RecipientId))
	}
	if !p.OutboundDate.IsZero() {
		write.WriteRaw("outbound_date", types.Marshal(p.OutboundDate))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *OutboundRecord) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "recipient_type":
			p.RecipientType = types.String(value.Str)
		case "material_use":
			p.MaterialUse = types.String(value.Str)
		case "outbound_flag":
			p.OutboundFlag = types.String(value.Str)
		case "del_flag":
			p.DelFlag = types.String(value.Str)
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "warehouse_id":
			p.WarehouseId = types.BigInt(value.Uint())
		case "staff_id":
			p.StaffId = types.BigInt(value.Uint())
		case "recipient_id":
			p.RecipientId = types.BigInt(value.Uint())
		case "outbound_date":
			p.OutboundDate = types.Time{Time: value.Time()}
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *OutboundRecord) Free() {
	if p == nil {
		return
	}

	outboundrecordPool.Put(p)
}

// Reset
func (p *OutboundRecord) Reset() {
	p.RecipientType = ""
	p.MaterialUse = ""
	p.OutboundFlag = ""
	p.DelFlag = ""
	p.Id = 0
	p.WarehouseId = 0
	p.StaffId = 0
	p.RecipientId = 0
	p.OutboundDate = types.Time{}
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}

}

func (p *OutboundRecord) TableName() string {
	return OutboundRecordTableName
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var outboundrecordFieldToPtrFunc = map[dialect.Field]func(*OutboundRecord) any{
	tbloutboundrecord.RecipientType: func(p *OutboundRecord) any { return &p.RecipientType },
	tbloutboundrecord.MaterialUse:   func(p *OutboundRecord) any { return &p.MaterialUse },
	tbloutboundrecord.OutboundFlag:  func(p *OutboundRecord) any { return &p.OutboundFlag },
	tbloutboundrecord.DelFlag:       func(p *OutboundRecord) any { return &p.DelFlag },
	tbloutboundrecord.Id:            func(p *OutboundRecord) any { return &p.Id },
	tbloutboundrecord.WarehouseId:   func(p *OutboundRecord) any { return &p.WarehouseId },
	tbloutboundrecord.StaffId:       func(p *OutboundRecord) any { return &p.StaffId },
	tbloutboundrecord.RecipientId:   func(p *OutboundRecord) any { return &p.RecipientId },
	tbloutboundrecord.OutboundDate:  func(p *OutboundRecord) any { return &p.OutboundDate },
	tbloutboundrecord.CreateId:      func(p *OutboundRecord) any { return &p.CreateId },
	tbloutboundrecord.CreateTime:    func(p *OutboundRecord) any { return &p.CreateTime },
	tbloutboundrecord.UpdateId:      func(p *OutboundRecord) any { return &p.UpdateId },
	tbloutboundrecord.UpdateTime:    func(p *OutboundRecord) any { return &p.UpdateTime },
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *OutboundRecord) AssignPtr(args ...dialect.Field) []any {
	if len(args) == 0 {
		args = tbloutboundrecord.ReadableFields
	}

	_vals := make([]any, 0, len(args))
	for _, col := range args {
		if ptrFunc, ok := outboundrecordFieldToPtrFunc[col]; ok {
			_vals = append(_vals, ptrFunc(p))
		}
	}

	return _vals
}

func (p *OutboundRecord) Scan(rows *sql.Rows, args ...dialect.Field) ([]*OutboundRecord, bool, error) {
	defer rows.Close()
	outbound_records := make([]*OutboundRecord, 0)

	if len(args) == 0 {
		args = tbloutboundrecord.ReadableFields
	}

	for rows.Next() {
		_p := NewOutboundRecord()
		_vals := _p.AssignPtr(args...)
		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		outbound_records = append(outbound_records, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return outbound_records, len(outbound_records) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *OutboundRecord) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tbloutboundrecord.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var outboundrecordFieldToValueFunc = map[dialect.Field]func(*OutboundRecord) (any, bool){
	tbloutboundrecord.RecipientType: func(p *OutboundRecord) (any, bool) {
		return p.RecipientType, p.RecipientType == ""
	},
	tbloutboundrecord.MaterialUse: func(p *OutboundRecord) (any, bool) {
		return p.MaterialUse, p.MaterialUse == ""
	},
	tbloutboundrecord.OutboundFlag: func(p *OutboundRecord) (any, bool) {
		return p.OutboundFlag, p.OutboundFlag == ""
	},
	tbloutboundrecord.DelFlag: func(p *OutboundRecord) (any, bool) {
		return p.DelFlag, p.DelFlag == ""
	},
	tbloutboundrecord.Id: func(p *OutboundRecord) (any, bool) {
		return p.Id, p.Id == 0
	},
	tbloutboundrecord.WarehouseId: func(p *OutboundRecord) (any, bool) {
		return p.WarehouseId, p.WarehouseId == 0
	},
	tbloutboundrecord.StaffId: func(p *OutboundRecord) (any, bool) {
		return p.StaffId, p.StaffId == 0
	},
	tbloutboundrecord.RecipientId: func(p *OutboundRecord) (any, bool) {
		return p.RecipientId, p.RecipientId == 0
	},
	tbloutboundrecord.OutboundDate: func(p *OutboundRecord) (any, bool) {
		return p.OutboundDate, p.OutboundDate.IsZero()
	},
	tbloutboundrecord.CreateId: func(p *OutboundRecord) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tbloutboundrecord.CreateTime: func(p *OutboundRecord) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tbloutboundrecord.UpdateId: func(p *OutboundRecord) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tbloutboundrecord.UpdateTime: func(p *OutboundRecord) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *OutboundRecord) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tbloutboundrecord.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if valueFunc, exists := outboundrecordFieldToValueFunc[arg]; exists {
			value, isZero := valueFunc(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

//
func (p *OutboundRecord) AssignKeys() (dialect.Field, any) {
	return tbloutboundrecord.PrimaryKey, p.Id
}

//
func (p *OutboundRecord) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
