// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblaccident"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

const AccidentTableName = "accident"

var (
	accidentPool = pool.New[*Accident](func() any {
		_obj := &Accident{}
		return _obj
	})
)

func NewAccident() *Accident {
	_obj := accidentPool.Get()
	return _obj
}

// MarshalJSON
func (p *Accident) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(11 * 50)
	if p.Description != "" {
		write.WriteRaw("description", types.Marshal(p.Description))
	}
	if p.Picture != "" {
		write.WriteRaw("picture", types.Marshal(p.Picture))
	}
	if p.DelFlag != "" {
		write.WriteRaw("del_flag", types.Marshal(p.DelFlag))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.ElderId != 0 {
		write.WriteRaw("elder_id", types.Marshal(p.ElderId))
	}
	if p.StaffId != 0 {
		write.WriteRaw("staff_id", types.Marshal(p.StaffId))
	}
	if !p.OccurDate.IsZero() {
		write.WriteRaw("occur_date", types.Marshal(p.OccurDate))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *Accident) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "description":
			p.Description = types.String(value.Str)
		case "picture":
			p.Picture = types.String(value.Str)
		case "del_flag":
			p.DelFlag = types.String(value.Str)
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "elder_id":
			p.ElderId = types.BigInt(value.Uint())
		case "staff_id":
			p.StaffId = types.BigInt(value.Uint())
		case "occur_date":
			p.OccurDate = types.Time{Time: value.Time()}
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *Accident) Free() {
	if p == nil {
		return
	}

	accidentPool.Put(p)
}

// Reset
func (p *Accident) Reset() {
	p.Description = ""
	p.Picture = ""
	p.DelFlag = ""
	p.Id = 0
	p.ElderId = 0
	p.StaffId = 0
	p.OccurDate = types.Time{}
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}

}

func (p *Accident) TableName() string {
	return AccidentTableName
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var accidentFieldToPtrFunc = map[dialect.Field]func(*Accident) any{
	tblaccident.Description: func(p *Accident) any { return &p.Description },
	tblaccident.Picture:     func(p *Accident) any { return &p.Picture },
	tblaccident.DelFlag:     func(p *Accident) any { return &p.DelFlag },
	tblaccident.Id:          func(p *Accident) any { return &p.Id },
	tblaccident.ElderId:     func(p *Accident) any { return &p.ElderId },
	tblaccident.StaffId:     func(p *Accident) any { return &p.StaffId },
	tblaccident.OccurDate:   func(p *Accident) any { return &p.OccurDate },
	tblaccident.CreateId:    func(p *Accident) any { return &p.CreateId },
	tblaccident.CreateTime:  func(p *Accident) any { return &p.CreateTime },
	tblaccident.UpdateId:    func(p *Accident) any { return &p.UpdateId },
	tblaccident.UpdateTime:  func(p *Accident) any { return &p.UpdateTime },
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *Accident) AssignPtr(args ...dialect.Field) []any {
	if len(args) == 0 {
		args = tblaccident.ReadableFields
	}

	_vals := make([]any, 0, len(args))
	for _, col := range args {
		if ptrFunc, ok := accidentFieldToPtrFunc[col]; ok {
			_vals = append(_vals, ptrFunc(p))
		}
	}

	return _vals
}

func (p *Accident) Scan(rows *sql.Rows, args ...dialect.Field) ([]*Accident, bool, error) {
	defer rows.Close()
	accidents := make([]*Accident, 0)

	if len(args) == 0 {
		args = tblaccident.ReadableFields
	}

	for rows.Next() {
		_p := NewAccident()
		_vals := _p.AssignPtr(args...)
		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		accidents = append(accidents, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return accidents, len(accidents) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Accident) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblaccident.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var accidentFieldToValueFunc = map[dialect.Field]func(*Accident) (any, bool){
	tblaccident.Description: func(p *Accident) (any, bool) {
		return p.Description, p.Description == ""
	},
	tblaccident.Picture: func(p *Accident) (any, bool) {
		return p.Picture, p.Picture == ""
	},
	tblaccident.DelFlag: func(p *Accident) (any, bool) {
		return p.DelFlag, p.DelFlag == ""
	},
	tblaccident.Id: func(p *Accident) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblaccident.ElderId: func(p *Accident) (any, bool) {
		return p.ElderId, p.ElderId == 0
	},
	tblaccident.StaffId: func(p *Accident) (any, bool) {
		return p.StaffId, p.StaffId == 0
	},
	tblaccident.OccurDate: func(p *Accident) (any, bool) {
		return p.OccurDate, p.OccurDate.IsZero()
	},
	tblaccident.CreateId: func(p *Accident) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblaccident.CreateTime: func(p *Accident) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblaccident.UpdateId: func(p *Accident) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblaccident.UpdateTime: func(p *Accident) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Accident) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblaccident.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if valueFunc, exists := accidentFieldToValueFunc[arg]; exists {
			value, isZero := valueFunc(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

//
func (p *Accident) AssignKeys() (dialect.Field, any) {
	return tblaccident.PrimaryKey, p.Id
}

//
func (p *Accident) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
