// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblroomtype"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

const RoomTypeTableName = "room_type"

var (
	roomtypePool = pool.New[*RoomType](func() any {
		_obj := &RoomType{}
		return _obj
	})
)

func NewRoomType() *RoomType {
	_obj := roomtypePool.Get()
	return _obj
}

// MarshalJSON
func (p *RoomType) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(8 * 50)
	if p.Name != "" {
		write.WriteRaw("name", types.Marshal(p.Name))
	}
	if p.DelFlag != "" {
		write.WriteRaw("del_flag", types.Marshal(p.DelFlag))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.MonthPrice != 0.0 {
		write.WriteRaw("month_price", types.Marshal(p.MonthPrice))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *RoomType) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "name":
			p.Name = types.String(value.Str)
		case "del_flag":
			p.DelFlag = types.String(value.Str)
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "month_price":
			p.MonthPrice = types.Float64(value.Float())
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *RoomType) Free() {
	if p == nil {
		return
	}

	roomtypePool.Put(p)
}

// Reset
func (p *RoomType) Reset() {
	p.Name = ""
	p.DelFlag = ""
	p.Id = 0
	p.MonthPrice = 0
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}

}

func (p *RoomType) TableName() string {
	return RoomTypeTableName
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var roomtypeFieldToPtrFunc = map[dialect.Field]func(*RoomType) any{
	tblroomtype.Name:       func(p *RoomType) any { return &p.Name },
	tblroomtype.DelFlag:    func(p *RoomType) any { return &p.DelFlag },
	tblroomtype.Id:         func(p *RoomType) any { return &p.Id },
	tblroomtype.MonthPrice: func(p *RoomType) any { return &p.MonthPrice },
	tblroomtype.CreateId:   func(p *RoomType) any { return &p.CreateId },
	tblroomtype.CreateTime: func(p *RoomType) any { return &p.CreateTime },
	tblroomtype.UpdateId:   func(p *RoomType) any { return &p.UpdateId },
	tblroomtype.UpdateTime: func(p *RoomType) any { return &p.UpdateTime },
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *RoomType) AssignPtr(args ...dialect.Field) []any {
	if len(args) == 0 {
		args = tblroomtype.ReadableFields
	}

	_vals := make([]any, 0, len(args))
	for _, col := range args {
		if ptrFunc, ok := roomtypeFieldToPtrFunc[col]; ok {
			_vals = append(_vals, ptrFunc(p))
		}
	}

	return _vals
}

func (p *RoomType) Scan(rows *sql.Rows, args ...dialect.Field) ([]*RoomType, bool, error) {
	defer rows.Close()
	room_types := make([]*RoomType, 0)

	if len(args) == 0 {
		args = tblroomtype.ReadableFields
	}

	for rows.Next() {
		_p := NewRoomType()
		_vals := _p.AssignPtr(args...)
		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		room_types = append(room_types, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return room_types, len(room_types) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *RoomType) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblroomtype.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var roomtypeFieldToValueFunc = map[dialect.Field]func(*RoomType) (any, bool){
	tblroomtype.Name: func(p *RoomType) (any, bool) {
		return p.Name, p.Name == ""
	},
	tblroomtype.DelFlag: func(p *RoomType) (any, bool) {
		return p.DelFlag, p.DelFlag == ""
	},
	tblroomtype.Id: func(p *RoomType) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblroomtype.MonthPrice: func(p *RoomType) (any, bool) {
		return p.MonthPrice, p.MonthPrice == 0.0
	},
	tblroomtype.CreateId: func(p *RoomType) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblroomtype.CreateTime: func(p *RoomType) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblroomtype.UpdateId: func(p *RoomType) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblroomtype.UpdateTime: func(p *RoomType) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *RoomType) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblroomtype.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if valueFunc, exists := roomtypeFieldToValueFunc[arg]; exists {
			value, isZero := valueFunc(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

//
func (p *RoomType) AssignKeys() (dialect.Field, any) {
	return tblroomtype.PrimaryKey, p.Id
}

//
func (p *RoomType) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
