// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"api/internal/model/define/table/tblconsult"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

var (
	consultPool = pool.New[*Consult](func() any {
		_obj := &Consult{}
		return _obj
	})
)

func NewConsult() *Consult {
	_obj := consultPool.Get()
	return _obj
}

// MarshalJSON
func (p *Consult) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(13 * 50)
	if p.Name != "" {
		write.WriteRaw("name", types.Marshal(p.Name))
	}
	if p.Phone != "" {
		write.WriteRaw("phone", types.Marshal(p.Phone))
	}
	if p.Relation != "" {
		write.WriteRaw("relation", types.Marshal(p.Relation))
	}
	if p.ConsultContent != "" {
		write.WriteRaw("consult_content", types.Marshal(p.ConsultContent))
	}
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.ElderId != 0 {
		write.WriteRaw("elder_id", types.Marshal(p.ElderId))
	}
	if p.SourceId != 0 {
		write.WriteRaw("source_id", types.Marshal(p.SourceId))
	}
	if p.StaffId != 0 {
		write.WriteRaw("staff_id", types.Marshal(p.StaffId))
	}
	if !p.ConsultDate.IsZero() {
		write.WriteRaw("consult_date", types.Marshal(p.ConsultDate))
	}
	if p.CreateId != 0 {
		write.WriteRaw("create_id", types.Marshal(p.CreateId))
	}
	if !p.CreateTime.IsZero() {
		write.WriteRaw("create_time", types.Marshal(p.CreateTime))
	}
	if p.UpdateId != 0 {
		write.WriteRaw("update_id", types.Marshal(p.UpdateId))
	}
	if !p.UpdateTime.IsZero() {
		write.WriteRaw("update_time", types.Marshal(p.UpdateTime))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *Consult) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "name":
			p.Name = types.String(value.Str)
		case "phone":
			p.Phone = types.String(value.Str)
		case "relation":
			p.Relation = types.String(value.Str)
		case "consult_content":
			p.ConsultContent = types.String(value.Str)
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "elder_id":
			p.ElderId = types.BigInt(value.Uint())
		case "source_id":
			p.SourceId = types.BigInt(value.Uint())
		case "staff_id":
			p.StaffId = types.BigInt(value.Uint())
		case "consult_date":
			p.ConsultDate = types.Time{Time: value.Time()}
		case "create_id":
			p.CreateId = types.BigInt(value.Uint())
		case "create_time":
			p.CreateTime = types.Time{Time: value.Time()}
		case "update_id":
			p.UpdateId = types.BigInt(value.Uint())
		case "update_time":
			p.UpdateTime = types.Time{Time: value.Time()}
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *Consult) Free() {
	if p == nil {
		return
	}

	consultPool.Put(p)
}

// Reset
func (p *Consult) Reset() {
	p.Name = ""
	p.Phone = ""
	p.Relation = ""
	p.ConsultContent = ""
	p.Id = 0
	p.ElderId = 0
	p.SourceId = 0
	p.StaffId = 0
	p.ConsultDate = types.Time{}
	p.CreateId = 0
	p.CreateTime = types.Time{}
	p.UpdateId = 0
	p.UpdateTime = types.Time{}

}

func (p *Consult) TableName() string {
	return "consult"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var consultFieldToPtrFunc = map[string]func(*Consult) any{
	tblconsult.Name.Name:           func(p *Consult) any { return &p.Name },
	tblconsult.Phone.Name:          func(p *Consult) any { return &p.Phone },
	tblconsult.Relation.Name:       func(p *Consult) any { return &p.Relation },
	tblconsult.ConsultContent.Name: func(p *Consult) any { return &p.ConsultContent },
	tblconsult.Id.Name:             func(p *Consult) any { return &p.Id },
	tblconsult.ElderId.Name:        func(p *Consult) any { return &p.ElderId },
	tblconsult.SourceId.Name:       func(p *Consult) any { return &p.SourceId },
	tblconsult.StaffId.Name:        func(p *Consult) any { return &p.StaffId },
	tblconsult.ConsultDate.Name:    func(p *Consult) any { return &p.ConsultDate },
	tblconsult.CreateId.Name:       func(p *Consult) any { return &p.CreateId },
	tblconsult.CreateTime.Name:     func(p *Consult) any { return &p.CreateTime },
	tblconsult.UpdateId.Name:       func(p *Consult) any { return &p.UpdateId },
	tblconsult.UpdateTime.Name:     func(p *Consult) any { return &p.UpdateTime },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *Consult) fieldPtr(args ...dialect.Field) []func(*Consult) any {
	if len(args) == 0 {
		args = tblconsult.ReadableFields
	}
	fs := make([]func(*Consult) any, 0, len(args))
	for _, col := range args {
		if f, ok := consultFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *Consult) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *Consult) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if f, ok := consultFieldToPtrFunc[col]; ok {
			_vals = append(_vals, f(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *Consult) Slice(rows *sql.Rows, args ...dialect.Field) ([]*Consult, bool, error) {
	defer rows.Close()
	consults := make([]*Consult, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewConsult()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		consults = append(consults, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return consults, len(consults) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Consult) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblconsult.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var consultFieldToValueFunc = map[dialect.Field]func(*Consult) (any, bool){
	tblconsult.Name: func(p *Consult) (any, bool) {
		return p.Name, p.Name == ""
	},
	tblconsult.Phone: func(p *Consult) (any, bool) {
		return p.Phone, p.Phone == ""
	},
	tblconsult.Relation: func(p *Consult) (any, bool) {
		return p.Relation, p.Relation == ""
	},
	tblconsult.ConsultContent: func(p *Consult) (any, bool) {
		return p.ConsultContent, p.ConsultContent == ""
	},
	tblconsult.Id: func(p *Consult) (any, bool) {
		return p.Id, p.Id == 0
	},
	tblconsult.ElderId: func(p *Consult) (any, bool) {
		return p.ElderId, p.ElderId == 0
	},
	tblconsult.SourceId: func(p *Consult) (any, bool) {
		return p.SourceId, p.SourceId == 0
	},
	tblconsult.StaffId: func(p *Consult) (any, bool) {
		return p.StaffId, p.StaffId == 0
	},
	tblconsult.ConsultDate: func(p *Consult) (any, bool) {
		return p.ConsultDate, p.ConsultDate.IsZero()
	},
	tblconsult.CreateId: func(p *Consult) (any, bool) {
		return p.CreateId, p.CreateId == 0
	},
	tblconsult.CreateTime: func(p *Consult) (any, bool) {
		return p.CreateTime, p.CreateTime.IsZero()
	},
	tblconsult.UpdateId: func(p *Consult) (any, bool) {
		return p.UpdateId, p.UpdateId == 0
	},
	tblconsult.UpdateTime: func(p *Consult) (any, bool) {
		return p.UpdateTime, p.UpdateTime.IsZero()
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Consult) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tblconsult.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if f, has := consultFieldToValueFunc[arg]; has {
			value, isZero := f(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *Consult) AssignKeys() (dialect.Field, any) {
	return tblconsult.PrimaryKey, p.Id
}

func (p *Consult) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
