// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tblactive

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

var (
	Theme         = dialect.Field{Name: "theme", Json: "theme", Table: "active", Type: "types.String", IsRelation: false}
	Name          = dialect.Field{Name: "name", Json: "name", Table: "active", Type: "types.String", IsRelation: false}
	Content       = dialect.Field{Name: "content", Json: "content", Table: "active", Type: "types.String", IsRelation: false}
	Address       = dialect.Field{Name: "address", Json: "address", Table: "active", Type: "types.String", IsRelation: false}
	Organizer     = dialect.Field{Name: "organizer", Json: "organizer", Table: "active", Type: "types.String", IsRelation: false}
	Phone         = dialect.Field{Name: "phone", Json: "phone", Table: "active", Type: "types.String", IsRelation: false}
	ActivePicture = dialect.Field{Name: "active_picture", Json: "active_picture", Table: "active", Type: "types.String", IsRelation: false}
	DelFlag       = dialect.Field{Name: "del_flag", Json: "del_flag", Table: "active", Type: "types.String", IsRelation: false}
	Id            = dialect.Field{Name: "id", Json: "id", Table: "active", Type: "types.BigInt", IsRelation: false}
	TypeId        = dialect.Field{Name: "type_id", Json: "type_id", Table: "active", Type: "types.BigInt", IsRelation: false}
	ActiveDate    = dialect.Field{Name: "active_date", Json: "active_date", Table: "active", Type: "types.Time", IsRelation: false}
	CreateId      = dialect.Field{Name: "create_id", Json: "create_id", Table: "active", Type: "types.BigInt", IsRelation: false}
	CreateTime    = dialect.Field{Name: "create_time", Json: "create_time", Table: "active", Type: "types.Time", IsRelation: false}
	UpdateId      = dialect.Field{Name: "update_id", Json: "update_id", Table: "active", Type: "types.BigInt", IsRelation: false}
	UpdateTime    = dialect.Field{Name: "update_time", Json: "update_time", Table: "active", Type: "types.Time", IsRelation: false}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		Theme,
		Name,
		Content,
		Address,
		Organizer,
		Phone,
		ActivePicture,
		DelFlag,
		Id,
		TypeId,
		ActiveDate,
		CreateId,
		CreateTime,
		UpdateId,
		UpdateTime,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		Theme,
		Name,
		Content,
		Address,
		Organizer,
		Phone,
		ActivePicture,
		DelFlag,
		Id,
		TypeId,
		ActiveDate,
		CreateId,
		CreateTime,
		UpdateId,
		UpdateTime,
	}
)
