// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tblconsult

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

const TableName = "consult"

var (
	ConsultContent = dialect.Field{Name: "consult_content", Json: "consult_content", Table: "consult", Type: "types.String", IsRelation: false}
	Name           = dialect.Field{Name: "name", Json: "name", Table: "consult", Type: "types.String", IsRelation: false}
	Phone          = dialect.Field{Name: "phone", Json: "phone", Table: "consult", Type: "types.String", IsRelation: false}
	Relation       = dialect.Field{Name: "relation", Json: "relation", Table: "consult", Type: "types.String", IsRelation: false}
	ConsultDate    = dialect.Field{Name: "consult_date", Json: "consult_date", Table: "consult", Type: "types.Time", IsRelation: false}
	CreateId       = dialect.Field{Name: "create_id", Json: "create_id", Table: "consult", Type: "types.BigInt", IsRelation: false}
	CreateTime     = dialect.Field{Name: "create_time", Json: "create_time", Table: "consult", Type: "types.Time", IsRelation: false}
	ElderId        = dialect.Field{Name: "elder_id", Json: "elder_id", Table: "consult", Type: "types.BigInt", IsRelation: false}
	Id             = dialect.Field{Name: "id", Json: "id", Table: "consult", Type: "types.BigInt", IsRelation: false}
	SourceId       = dialect.Field{Name: "source_id", Json: "source_id", Table: "consult", Type: "types.BigInt", IsRelation: false}
	StaffId        = dialect.Field{Name: "staff_id", Json: "staff_id", Table: "consult", Type: "types.BigInt", IsRelation: false}
	TenantId       = dialect.Field{Name: "tenant_id", Json: "tenant_id", Table: "consult", Type: "types.BigInt", IsRelation: false}
	UpdateId       = dialect.Field{Name: "update_id", Json: "update_id", Table: "consult", Type: "types.BigInt", IsRelation: false}
	UpdateTime     = dialect.Field{Name: "update_time", Json: "update_time", Table: "consult", Type: "types.Time", IsRelation: false}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		ConsultContent,
		Name,
		Phone,
		Relation,
		ConsultDate,
		CreateId,
		CreateTime,
		ElderId,
		Id,
		SourceId,
		StaffId,
		TenantId,
		UpdateId,
		UpdateTime,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		ConsultContent,
		Name,
		Phone,
		Relation,
		ConsultDate,
		CreateId,
		CreateTime,
		ElderId,
		Id,
		SourceId,
		StaffId,
		TenantId,
		UpdateId,
		UpdateTime,
	}
)
