// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tblretreatapply

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

const TableName = "retreat_apply"

var (
	CreateId   = dialect.Field{Name: "create_id", Json: "create_id", Table: "retreat_apply", Type: "types.BigInt", IsRelation: false}
	CreateTime = dialect.Field{Name: "create_time", Json: "create_time", Table: "retreat_apply", Type: "types.Time", IsRelation: false}
	ElderId    = dialect.Field{Name: "elder_id", Json: "elder_id", Table: "retreat_apply", Type: "types.BigInt", IsRelation: false}
	Id         = dialect.Field{Name: "id", Json: "id", Table: "retreat_apply", Type: "types.BigInt", IsRelation: false}
	TenantId   = dialect.Field{Name: "tenant_id", Json: "tenant_id", Table: "retreat_apply", Type: "types.BigInt", IsRelation: false}
	UpdateId   = dialect.Field{Name: "update_id", Json: "update_id", Table: "retreat_apply", Type: "types.BigInt", IsRelation: false}
	UpdateTime = dialect.Field{Name: "update_time", Json: "update_time", Table: "retreat_apply", Type: "types.Time", IsRelation: false}
	State      = dialect.Field{Name: "state", Json: "state", Table: "retreat_apply", Type: "types.Int8", IsRelation: false}
	Status     = dialect.Field{Name: "status", Json: "status", Table: "retreat_apply", Type: "types.Int8", IsRelation: false}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		CreateId,
		CreateTime,
		ElderId,
		Id,
		TenantId,
		UpdateId,
		State,
		Status,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		CreateId,
		CreateTime,
		ElderId,
		Id,
		TenantId,
		UpdateId,
		UpdateTime,
		State,
		Status,
	}
)
