// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package dao //label

import (
	"api/internal/model/define/table/tbllabel"
	"api/internal/model/do"
	"context"
	"database/sql"
	"github.com/linbaozhong/gentity/pkg/ace"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/types"
)

type label struct {
	pool.Model
	x     ace.Executer
	toSql bool
}

var (
	labelPool = pool.New[*label](func() any {
		_obj := &label{}
		return _obj
	})
)

// New 实例化label
// exec: 执行器，用于执行sql语句，如：db,tx
// 如果不传入，则使用默认的db
func Label(x ace.Executer) *label {
	_obj := labelPool.Get()
	_obj.x = x
	return _obj
}

// Free 释放对象
func (p *label) Free() {
	if p == nil {
		return
	}

	labelPool.Put(p)
}

// Reset 重置对象
func (p *label) Reset() {
	p.toSql = false
}

// Debug 仅打印SQL语句，不执行
func (p *label) Debug() *label {
	p.toSql = true
	return p
}

// Insert 返回 LastInsertId
func (p *label) Insert(ctx context.Context, sets ...dialect.Setter) (int64, error) {
	defer p.Free()
	if len(sets) == 0 {
		return 0, dialect.ErrSetterEmpty
	}
	_result, e := p.x.Table(do.LabelTableName).
		Set(sets...).
		Debug(p.toSql).
		Create().
		Exec(ctx)
	if e != nil {
		return 0, e
	}
	return _result.LastInsertId()
}

// InsertOne
// cols: 要插入的列名
func (p *label) InsertOne(ctx context.Context, bean *do.Label, cols ...dialect.Field) (bool, error) {
	defer p.Free()
	_result, e := p.x.Table(do.LabelTableName).
		Cols(cols...).
		Debug(p.toSql).
		Create().
		Struct(ctx, bean)
	if e != nil {
		return false, e
	}

	bean.AssignPrimaryKeyValues(_result)

	_n, e := _result.RowsAffected()
	return _n > 0, e
}

// InsertBatch 批量插入,返回 RowsAffected。禁止在事务中使用
// cols: 要插入的列名，如果为空，则插入结构体字段对应所有列
func (p *label) InsertBatch(ctx context.Context, beans []*do.Label, cols ...dialect.Field) (int64, error) {
	defer p.Free()
	_lens := len(beans)
	if _lens == 0 {
		return 0, dialect.ErrBeanEmpty
	}
	_args := make([]dialect.Modeler, 0, _lens)
	for _, _bean := range beans {
		_args = append(_args, _bean)
	}
	_result, e := p.x.Table(do.LabelTableName).
		Cols(cols...).
		Debug(p.toSql).
		Create().
		BatchStruct(ctx, _args...)
	if e != nil {
		return 0, e
	}

	return _result.RowsAffected()
}

// Update
func (p *label) Update(ctx context.Context, sets []dialect.Setter, cond ...dialect.Condition) (bool, error) {
	defer p.Free()
	if len(sets) == 0 {
		return true, nil
	}
	_result, e := p.x.Table(do.LabelTableName).
		Where(cond...).
		Set(sets...).
		Debug(p.toSql).
		Update().
		Exec(ctx)
	if e != nil {
		return false, e
	}
	_n, e := _result.RowsAffected()
	return _n >= 0, e
}

// UpdateById
func (p *label) UpdateById(ctx context.Context, id types.BigInt, sets ...dialect.Setter) (bool, error) {
	return p.Update(ctx,
		sets,
		tbllabel.PrimaryKey.Eq(id),
	)
}

// UpdateOne
// cols: 要插入的列名
func (p *label) UpdateOne(ctx context.Context, bean *do.Label, cols ...dialect.Field) (bool, error) {
	defer p.Free()
	_result, e := p.x.Table(do.LabelTableName).
		Cols(cols...).
		Debug(p.toSql).
		Update().
		Struct(ctx, bean)
	if e != nil {
		return false, e
	}

	_n, e := _result.RowsAffected()
	return _n >= 0, e
}

// UpdateBatch 批量更新,禁止在事务中使用
// cols: 要更新的列名，如果为空，则更新结构体所有字段对应列，包含零值字段
func (p *label) UpdateBatch(ctx context.Context, beans []*do.Label, cols ...dialect.Field) (bool, error) {
	defer p.Free()
	_lens := len(beans)
	if _lens == 0 {
		return false, dialect.ErrBeanEmpty
	}
	_args := make([]dialect.Modeler, 0, _lens)
	for _, _bean := range beans {
		_args = append(_args, _bean)
	}
	_result, e := p.x.Table(do.LabelTableName).
		Cols(cols...).
		Debug(p.toSql).
		Update().
		BatchStruct(ctx, _args...)
	if e != nil {
		return false, e
	}
	_n, e := _result.RowsAffected()
	return _n >= 0, e
}

// Delete
func (p *label) Delete(ctx context.Context, cond ...dialect.Condition) (bool, error) {
	defer p.Free()
	_result, e := p.x.Table(do.LabelTableName).
		Where(cond...).
		Debug(p.toSql).
		Delete().
		Exec(ctx)
	if e != nil {
		return false, e
	}
	_n, e := _result.RowsAffected()
	return _n >= 0, e
}

// DeleteById
func (p *label) DeleteById(ctx context.Context, id types.BigInt) (bool, error) {
	return p.Delete(ctx,
		tbllabel.PrimaryKey.Eq(id),
	)
}

// DeleteByIds 按主键列表批量删除
// ids: 主键列表
// 返回值: 影响的行数，错误信息
func (p *label) DeleteByIds(ctx context.Context, ids []any) (int64, error) {
	defer p.Free()
	if len(ids) == 0 {
		return 0, nil
	}

	_result, e := p.x.Table(do.LabelTableName).
		Where(tbllabel.PrimaryKey.In(ids...)).
		Debug(p.toSql).
		Delete().
		Exec(ctx)
	if e != nil {
		return 0, e
	}
	return _result.RowsAffected()
}

// Get 查询第一个符合条件的记录
//
//	s: 选择器，用于构建sql语句
//
// 返回值:
//  1. *do.Label: 第一个符合条件的记录
//  2. bool: 是否存在记录
//  3. error: 错误信息
//
// 注意:
//  1. 如果没有指定表名，则默认使用do.LabelTableName
//  2. 如果没有指定查询列，则默认使用tbllabel.ReadableFields
//  3. 如果没有指定排序方式，则默认使用dialect.OrderAsc
//  4. 如果没有指定条件，则默认查询所有记录
//  5. 如果查询出错，则返回nil, false, error
//  6. 如果没有查询到记录，则返回nil, false, nil
//  7. 如果查询到记录，则返回记录, true, nil
//  8. 如果查询到多条记录，则返回第一条记录, true, nil
func (p *label) Get(ctx context.Context, s ace.SelectBuilder) (*do.Label, bool, error) {
	defer p.Free()
	if len(s.GetTableName()) == 0 {
		s.Table(do.LabelTableName)
	}

	_cols := s.GetCols()
	l := len(_cols)
	if l == 0 {
		_cols = tbllabel.ReadableFields
		s.Cols(_cols...)
	}
	if s.GetDB() == nil {
		s.SetDB(p.x)
	}
	_row, e := s.Debug(p.toSql).
		Select().
		QueryRow(ctx)
	if e != nil {
		return nil, false, e
	}

	_obj := do.NewLabel()
	e = _row.Scan(_obj.AssignPtr(_cols...)...)
	switch e {
	case nil:
		return _obj, true, nil
	case sql.ErrNoRows:
		return _obj, false, nil
	default:
		return _obj, false, e
	}
}

// GetByID 按主键读取一个label对象,先判断第二返回值是否为true,再判断是否第三返回值为nil
func (p *label) GetByID(ctx context.Context, id types.BigInt, cols ...dialect.Field) (*do.Label, bool, error) {
	defer p.Free()
	return p.Get(ctx, p.x.Table(do.LabelTableName).Where(tbllabel.PrimaryKey.Eq(id)).Cols(cols...))
}

// GetByIds 按主键列表批量查询
// ids: 主键列表
// cols: 要查询的列名，如果为空，则查询所有可读列
func (p *label) GetByIds(ctx context.Context, ids []any, cols ...dialect.Field) ([]*do.Label, error) {
	_objs, _, e := p.List(ctx, ace.Where(tbllabel.PrimaryKey.In(ids...)).Cols(cols...))
	return _objs, e
}

// Cell 查询第一个符合条件的记录的第一个列
//
//	s: 选择器，用于构建sql语句
//
// 返回值:
//  1. any: 第一个符合条件的记录的第一个列
//  2. bool: 是否存在记录
//  3. error: 错误信息
//
// 注意:
//  1. 如果没有指定表名，则默认使用do.LabelTableName
//  2. 如果没有指定查询列，则默认使用tbllabel.PrimaryKey
func (p *label) Cell(ctx context.Context, s ace.SelectBuilder) (any, bool, error) {
	defer p.Free()
	if len(s.GetTableName()) == 0 {
		s.Table(do.LabelTableName)
	}

	_cols := s.GetCols()
	if len(_cols) == 0 {
		s.Cols(tbllabel.PrimaryKey)
	} else {
		s.PureCols(_cols[0])
	}

	if s.GetDB() == nil {
		s.SetDB(p.x)
	}
	_row, e := s.Debug(p.toSql).
		Select().
		QueryRow(ctx)
	if e != nil {
		return nil, false, e
	}
	var _v any
	e = _row.Scan(&_v)
	switch e {
	case nil:
		return _v, true, nil
	case sql.ErrNoRows:
		return _v, false, nil
	default:
		return _v, false, e
	}
}

// List 查询所有符合条件的记录
func (p *label) List(ctx context.Context, s ace.SelectBuilder) ([]*do.Label, bool, error) {
	defer p.Free()
	if len(s.GetTableName()) == 0 {
		s.Table(do.LabelTableName)
	}

	_cols := s.GetCols()

	l := len(_cols)
	if l == 0 {
		_cols = tbllabel.ReadableFields
		s.Cols(_cols...)
	}

	if s.GetDB() == nil {
		s.SetDB(p.x)
	}
	_rows, e := s.Debug(p.toSql).
		Select().
		Query(ctx)
	if e != nil {
		return nil, false, e
	}
	defer _rows.Close()

	_obj := do.NewLabel()
	_objs, has, e := _obj.Scan(_rows, _cols...)
	if has {
		return _objs, true, nil
	}
	if e == nil || e == sql.ErrNoRows {
		return _objs, false, nil
	}

	return _objs, false, e
}

// Column 查询所有符合条件的记录的指定列
func (p *label) Column(ctx context.Context, s ace.SelectBuilder) ([]any, error) {
	defer p.Free()
	if len(s.GetTableName()) == 0 {
		s.Table(do.LabelTableName)
	}

	_cols := s.GetCols()
	if len(_cols) == 0 {
		s.PureCols(tbllabel.PrimaryKey)
	} else {
		s.PureCols(_cols[0])
	}

	if s.GetDB() == nil {
		s.SetDB(p.x)
	}
	_rows, e := s.Debug(p.toSql).
		Select().
		Query(ctx)
	if e != nil {
		return nil, e
	}
	defer _rows.Close()

	_objs := []any{}
	for _rows.Next() {
		var _v any
		e := _rows.Scan(&_v)
		if e != nil {
			return nil, e
		}
		_objs = append(_objs, _v)
	}
	return _objs, nil
}

// Count
func (p *label) Count(ctx context.Context, cond ...dialect.Condition) (int64, error) {
	defer p.Free()
	return p.x.Table(do.LabelTableName).
		Debug(p.toSql).
		Select().
		Count(ctx, cond...)
}

// Sum
func (p *label) Sum(ctx context.Context, cols []dialect.Field, cond ...dialect.Condition) (map[string]any, error) {
	defer p.Free()
	return p.x.Table(do.LabelTableName).
		Debug(p.toSql).
		Select().
		Sum(ctx, cols, cond...)
}

// Exists
func (p *label) Exists(ctx context.Context, cond ...dialect.Condition) (bool, error) {
	defer p.Free()
	_c := p.x.Table(do.LabelTableName).Cols(tbllabel.PrimaryKey).Where(cond...)
	_row, e := _c.Debug(p.toSql).
		Select().
		QueryRow(ctx)
	if e != nil {
		return false, e
	}

	var id types.BigInt
	e = _row.Scan(&id)
	switch e {
	case nil:
		return true, nil
	case sql.ErrNoRows:
		return false, nil
	default:
		return false, e
	}
}
