// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tbldepositinfo

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

const TableName = "deposit_info"

var (
	Id         = dialect.Field{Name: "id", Json: "id", Table: "deposit_info", Type: "types.BigInt", IsRelation: false}
	DepositId  = dialect.Field{Name: "deposit_id", Json: "deposit_id", Table: "deposit_info", Type: "types.BigInt", IsRelation: false}
	MedicineId = dialect.Field{Name: "medicine_id", Json: "medicine_id", Table: "deposit_info", Type: "types.BigInt", IsRelation: false}
	CreateId   = dialect.Field{Name: "create_id", Json: "create_id", Table: "deposit_info", Type: "types.BigInt", IsRelation: false}
	CreateTime = dialect.Field{Name: "create_time", Json: "create_time", Table: "deposit_info", Type: "types.Time", IsRelation: false}
	UpdateId   = dialect.Field{Name: "update_id", Json: "update_id", Table: "deposit_info", Type: "types.BigInt", IsRelation: false}
	UpdateTime = dialect.Field{Name: "update_time", Json: "update_time", Table: "deposit_info", Type: "types.Time", IsRelation: false}
	DepositNum = dialect.Field{Name: "deposit_num", Json: "deposit_num", Table: "deposit_info", Type: "types.Int32", IsRelation: false}
	SurplusNum = dialect.Field{Name: "surplus_num", Json: "surplus_num", Table: "deposit_info", Type: "types.Int32", IsRelation: false}
	WarnNum    = dialect.Field{Name: "warn_num", Json: "warn_num", Table: "deposit_info", Type: "types.Int32", IsRelation: false}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		Id,
		DepositId,
		MedicineId,
		CreateId,
		CreateTime,
		UpdateId,
		UpdateTime,
		DepositNum,
		SurplusNum,
		WarnNum,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		Id,
		DepositId,
		MedicineId,
		CreateId,
		CreateTime,
		UpdateId,
		UpdateTime,
		DepositNum,
		SurplusNum,
		WarnNum,
	}
)
