// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tblretreat

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

const TableName = "retreat"

var (
	RetreatForm  = dialect.Field{Name: "retreat_form", Json: "retreat_form", Table: "retreat", Type: "types.String", IsRelation: false}
	RetreatCause = dialect.Field{Name: "retreat_cause", Json: "retreat_cause", Table: "retreat", Type: "types.String", IsRelation: false}
	Id           = dialect.Field{Name: "id", Json: "id", Table: "retreat", Type: "types.BigInt", IsRelation: false}
	ElderId      = dialect.Field{Name: "elder_id", Json: "elder_id", Table: "retreat", Type: "types.BigInt", IsRelation: false}
	CreateId     = dialect.Field{Name: "create_id", Json: "create_id", Table: "retreat", Type: "types.BigInt", IsRelation: false}
	CreateTime   = dialect.Field{Name: "create_time", Json: "create_time", Table: "retreat", Type: "types.Time", IsRelation: false}
	UpdateId     = dialect.Field{Name: "update_id", Json: "update_id", Table: "retreat", Type: "types.BigInt", IsRelation: false}
	UpdateTime   = dialect.Field{Name: "update_time", Json: "update_time", Table: "retreat", Type: "types.Time", IsRelation: false}
	Evaluate     = dialect.Field{Name: "evaluate", Json: "evaluate", Table: "retreat", Type: "types.Int32", IsRelation: false}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		RetreatForm,
		RetreatCause,
		Id,
		ElderId,
		CreateId,
		CreateTime,
		UpdateId,
		UpdateTime,
		Evaluate,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		RetreatForm,
		RetreatCause,
		Id,
		ElderId,
		CreateId,
		CreateTime,
		UpdateId,
		UpdateTime,
		Evaluate,
	}
)
