// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tblnurseitem

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

var (
	Id         = dialect.Field{Name: "id", Json: "id", Table: "nurse_item", Type: "types.BigInt", IsRelation: false}
	GradeId    = dialect.Field{Name: "grade_id", Json: "grade_id", Table: "nurse_item", Type: "types.BigInt", IsRelation: false}
	ServiceId  = dialect.Field{Name: "service_id", Json: "service_id", Table: "nurse_item", Type: "types.BigInt", IsRelation: false}
	CreateId   = dialect.Field{Name: "create_id", Json: "create_id", Table: "nurse_item", Type: "types.BigInt", IsRelation: false}
	CreateTime = dialect.Field{Name: "create_time", Json: "create_time", Table: "nurse_item", Type: "types.Time", IsRelation: false}
	UpdateId   = dialect.Field{Name: "update_id", Json: "update_id", Table: "nurse_item", Type: "types.BigInt", IsRelation: false}
	UpdateTime = dialect.Field{Name: "update_time", Json: "update_time", Table: "nurse_item", Type: "types.Time", IsRelation: false}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		Id,
		GradeId,
		ServiceId,
		CreateId,
		CreateTime,
		UpdateId,
		UpdateTime,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		Id,
		GradeId,
		ServiceId,
		CreateId,
		CreateTime,
		UpdateId,
		UpdateTime,
	}
)
