// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tbloutward

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

var (
	ChaperoneName  = dialect.Field{Name: "chaperone_name", Json: "chaperone_name", Table: "outward", Type: "types.String", IsRelation: false}
	ChaperonePhone = dialect.Field{Name: "chaperone_phone", Json: "chaperone_phone", Table: "outward", Type: "types.String", IsRelation: false}
	ChaperoneType  = dialect.Field{Name: "chaperone_type", Json: "chaperone_type", Table: "outward", Type: "types.String", IsRelation: false}
	Id             = dialect.Field{Name: "id", Json: "id", Table: "outward", Type: "types.BigInt", IsRelation: false}
	ElderId        = dialect.Field{Name: "elder_id", Json: "elder_id", Table: "outward", Type: "types.BigInt", IsRelation: false}
	OutwardDate    = dialect.Field{Name: "outward_date", Json: "outward_date", Table: "outward", Type: "types.Time", IsRelation: false}
	PlanReturnDate = dialect.Field{Name: "plan_return_date", Json: "plan_return_date", Table: "outward", Type: "types.Time", IsRelation: false}
	RealReturnDate = dialect.Field{Name: "real_return_date", Json: "real_return_date", Table: "outward", Type: "types.Time", IsRelation: false}
	CreateId       = dialect.Field{Name: "create_id", Json: "create_id", Table: "outward", Type: "types.BigInt", IsRelation: false}
	CreateTime     = dialect.Field{Name: "create_time", Json: "create_time", Table: "outward", Type: "types.Time", IsRelation: false}
	UpdateId       = dialect.Field{Name: "update_id", Json: "update_id", Table: "outward", Type: "types.BigInt", IsRelation: false}
	UpdateTime     = dialect.Field{Name: "update_time", Json: "update_time", Table: "outward", Type: "types.Time", IsRelation: false}
	DelFlag        = dialect.Field{Name: "del_flag", Json: "del_flag", Table: "outward", Type: "types.Int8", IsRelation: false}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		ChaperoneName,
		ChaperonePhone,
		ChaperoneType,
		Id,
		ElderId,
		OutwardDate,
		PlanReturnDate,
		RealReturnDate,
		CreateId,
		CreateTime,
		UpdateId,
		UpdateTime,
		DelFlag,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		ChaperoneName,
		ChaperonePhone,
		ChaperoneType,
		Id,
		ElderId,
		OutwardDate,
		PlanReturnDate,
		RealReturnDate,
		CreateId,
		CreateTime,
		UpdateId,
		UpdateTime,
		DelFlag,
	}
)
